---
- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted

- name: Restart health timer
  ansible.builtin.systemd_service:
    name: dev-netcup-health.timer
    state: restarted
    daemon_reload: true

- name: Restart Docker cleanup timer
  ansible.builtin.systemd_service:
    name: dev-netcup-docker-prune.timer
    state: restarted
    daemon_reload: true

- name: Validate and reload SSH
  ansible.builtin.command: sshd -t
  changed_when: false
  notify: Reload SSH

- name: Reload SSH
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded

- name: Restart Netcup administration firewall
  ansible.builtin.systemd_service:
    name: netcup-ssh-zerotier-firewall.service
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode
