# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML syntax
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-json
        description: Check JSON syntax
      - id: check-toml
        description: Check TOML syntax
      - id: check-xml
        description: Check XML syntax
      - id: check-merge-conflict
        description: Check for merge conflicts
      - id: check-case-conflict
        description: Check for case conflicts
      - id: check-added-large-files
        description: Check for large files
        args: ['--maxkb=1000']
      - id: detect-private-key
        description: Detect private keys
      - id: no-commit-to-branch
        description: Protect main branch
        args: ['--branch', 'main', '--branch', 'master']

  # Secret detection with gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        description: Scan for secrets with gitleaks
        entry: gitleaks
        language: golang
        types: [text]

  # Python hooks (if Python files are present)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        description: Format Python code with Black
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        description: Sort Python imports
        files: \.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        description: Python linting with flake8
        files: \.py$

  # JavaScript/TypeScript hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        description: Format JS/TS/CSS/JSON with Prettier
        files: \.(js|jsx|ts|tsx|css|scss|json|md|yml|yaml)$
        exclude: |
          (?x)^(
            .*\.min\.(js|css)$|
            package-lock\.json$|
            yarn\.lock$|
            .*node_modules/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        description: Lint JavaScript/TypeScript
        files: \.(js|jsx|ts|tsx)$
        exclude: |
          (?x)^(
            .*\.min\.js$|
            .*node_modules/.*|
            .*dist/.*|
            .*build/.*
          )$

  # Java hooks
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        description: Format Java code
        args: [--aosp, --autofix]
        files: \.java$

  # Docker hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        description: Lint Dockerfiles
        files: Dockerfile.*

  # Shell script hooks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        description: Lint shell scripts
        files: \.(sh|bash)$

  # Markdown hooks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        description: Lint Markdown files
        files: \.md$
        args: [--fix]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        description: Detect secrets in committed files
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock$|
            .*package-lock\.json$|
            .*yarn\.lock$|
            .*\.min\.(js|css)$|
            .*node_modules/.*|
            .*target/.*|
            .*build/.*|
            .*dist/.*
          )$

  # Kubernetes manifest validation
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        description: Lint YAML files
        files: \.(yaml|yml)$
        args: [-c, .yamllint.yml]

# Global configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
