# Production Environment Values for Modulo API
replicaCount: 3

image:
  tag: "prod-v1.0.0"

ingress:
  hosts:
    - host: api.modulo.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: modulo-api-prod-tls
      hosts:
        - api.modulo.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20

config:
  profile: production
  database:
    host: postgresql-prod
    name: modulo_prod

env:
  - name: SPRING_PROFILES_ACTIVE
    value: production
  - name: LOG_LEVEL
    value: INFO

# Enable Argo Rollouts for production
rollouts:
  enabled: true
  strategy: canary
