# Production Environment Values for Modulo Web
replicaCount: 3

image:
  tag: "prod-v1.0.0"

ingress:
  hosts:
    - host: modulo.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: modulo-web-prod-tls
      hosts:
        - modulo.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

env:
  - name: VITE_API_URL
    value: "https://api.modulo.com"
  - name: VITE_ENV
    value: "production"
