-- Current Hibernate 5 / BIGINT schema. Do not edit after deployment.
-- Legacy database/migrations V1 (UUID) is intentionally not in this location.
create schema if not exists application;

    create table application.attachments (
       attachment_id int8 not null,
        blob_name varchar(255) not null,
        blob_url varchar(255) not null,
        cdn_url varchar(255),
        container_name varchar(255) not null,
        content_type varchar(255),
        file_size int8,
        is_active boolean,
        original_filename varchar(255) not null,
        uploaded_at timestamp,
        uploaded_by varchar(255),
        note_id int8,
        primary key (attachment_id)
    );

    create table application.comment_mentions (
       comment_id int8 not null,
        user_id varchar(255)
    );

    create table application.note_comments (
       id int8 generated by default as identity,
        anchor_end int4,
        anchor_start int4,
        author_id varchar(255) not null,
        author_name varchar(255),
        content TEXT not null,
        created_at timestamp,
        note_id int8 not null,
        parent_id int8,
        resolved boolean,
        updated_at timestamp,
        primary key (id)
    );

    create table application.note_links (
       link_id uuid not null,
        link_type varchar(255) not null,
        source_note_id int8 not null,
        target_note_id int8 not null,
        primary key (link_id)
    );

    create table application.note_metadata (
       note_id int8 not null,
        metadata_value TEXT,
        metadata_key varchar(255) not null,
        primary key (note_id, metadata_key)
    );

    create table application.note_tags (
       note_id int8 not null,
        tag_id uuid not null,
        primary key (note_id, tag_id)
    );

    create table application.note_tasks (
       note_id int8 not null,
        task_id int8 not null,
        primary key (note_id, task_id)
    );

    create table application.notes (
       note_id int8 not null,
        access_control_enabled boolean,
        access_control_tx_hash varchar(255),
        blockchain_note_id int8,
        blockchain_registered_at timestamp,
        blockchain_tx_hash varchar(255),
        content TEXT,
        content_hash varchar(255),
        created_at timestamp,
        ipfs_cid varchar(255),
        ipfs_uploaded_at timestamp,
        is_decentralized boolean,
        is_on_blockchain boolean,
        is_public boolean,
        last_editor varchar(255),
        last_viewed_at timestamp,
        markdown_content TEXT,
        owner_address varchar(255),
        title varchar(255),
        updated_at timestamp,
        user_id int8,
        version int8,
        primary key (note_id)
    );

    create table application.share_tokens (
       id int8 generated by default as identity,
        created_at timestamp not null,
        expires_at timestamp,
        note_id int8 not null,
        owner_id varchar(128),
        password_hash varchar(256),
        revoked boolean not null,
        token varchar(64) not null,
        primary key (id)
    );

    create table application.tags (
       tag_id uuid not null,
        name varchar(255) not null,
        primary key (tag_id)
    );

    alter table if exists application.attachments 
       add constraint UK_9q71nru0ohxfpe0t4ltqww0xu unique (blob_name);

    alter table if exists application.share_tokens 
       add constraint UK_a8th0vqx5bwfys3ot61ie4rcv unique (token);

    alter table if exists application.tags 
       add constraint UK_t48xdq560gs3gap9g7jg36kgc unique (name);
create sequence hibernate_sequence start 1 increment 1;

    create table audit_events (
       id int8 generated by default as identity,
        created_at timestamp not null,
        detail TEXT,
        event_type varchar(64) not null,
        ip_address varchar(64),
        note_id int8,
        outcome varchar(16),
        user_id varchar(128),
        user_name varchar(256),
        primary key (id)
    );

    create table note_templates (
       id int8 generated by default as identity,
        content TEXT not null,
        created_at timestamp,
        description varchar(255),
        name varchar(255) not null,
        owner_id varchar(255),
        updated_at timestamp,
        variables TEXT,
        primary key (id)
    );

    create table notifications (
       id int8 generated by default as identity,
        comment_id int8,
        created_at timestamp,
        message TEXT,
        note_id int8,
        is_read boolean,
        type varchar(255) not null,
        user_id varchar(255) not null,
        primary key (id)
    );

    create table offline_notes (
       id int8 generated by default as identity,
        content TEXT,
        created_at timestamp,
        is_deleted boolean,
        last_synced timestamp,
        markdown_content TEXT,
        server_id int8,
        sync_status varchar(255),
        tags TEXT,
        title varchar(255),
        updated_at timestamp,
        version int4,
        primary key (id)
    );

    create table plugin_submissions (
       submission_id varchar(255) not null,
        approved_at timestamp,
        category varchar(50),
        checksum varchar(64),
        compatibility_check_passed boolean not null,
        description varchar(1000) not null,
        developer_email varchar(255) not null,
        developer_name varchar(100) not null,
        documentation_url varchar(500),
        file_size int8 not null,
        homepage_url varchar(500),
        icon_file_path varchar(500),
        image_digest varchar(80),
        image_reference varchar(500),
        jar_file_path varchar(1000),
        license_type varchar(50),
        max_platform_version varchar(50),
        min_platform_version varchar(50),
        plugin_name varchar(100) not null,
        published_at timestamp,
        rejected_at timestamp,
        required_permissions varchar(500),
        review_notes varchar(2000),
        review_started_at timestamp,
        reviewed_at timestamp,
        reviewer_id varchar(255),
        screenshot_paths varchar(2000),
        security_check_passed boolean not null,
        source_code_url varchar(500),
        status varchar(255) not null,
        submitted_at timestamp not null,
        tags varchar(500),
        validation_errors varchar(2000),
        validation_warnings varchar(2000),
        version varchar(50) not null,
        primary key (submission_id)
    );

    create table tasks (
       id int8 generated by default as identity,
        actual_duration int4,
        completion_date timestamp,
        created_at timestamp not null,
        description varchar(2000),
        due_date timestamp,
        estimated_duration int4,
        google_calendar_event_id varchar(255),
        is_recurring boolean,
        parent_task_id int8,
        priority varchar(255) not null,
        progress_percentage int4,
        recurrence_pattern varchar(255),
        start_date timestamp,
        status varchar(255) not null,
        tags varchar(255),
        title varchar(255) not null,
        updated_at timestamp not null,
        user_id int8 not null,
        primary key (id)
    );

    create table user_auth_providers (
       user_id int8 not null,
        auth_provider varchar(255)
    );

    create table user_custom_attributes (
       user_id int8 not null,
        attribute_value TEXT,
        attribute_key varchar(255) not null,
        primary key (user_id, attribute_key)
    );

    create table user_preferences (
       user_id int8 not null,
        preference_value TEXT,
        preference_key varchar(255) not null,
        primary key (user_id, preference_key)
    );

    create table users (
       id int8 generated by default as identity,
        azure_sub varchar(255),
        created_at timestamp,
        email varchar(255),
        first_name varchar(255),
        google_sub varchar(255),
        keycloak_sub varchar(255),
        last_login_at timestamp,
        last_name varchar(255),
        last_oauth_provider varchar(255),
        legacy_oauth_email varchar(255),
        migration_date timestamp,
        migration_status varchar(255),
        primary_auth_provider varchar(255),
        updated_at timestamp,
        username varchar(255),
        wallet_address varchar(255),
        primary key (id)
    );
create index idx_audit_note_id on audit_events (note_id);
create index idx_audit_user_id on audit_events (user_id);
create index idx_audit_created_at on audit_events (created_at);

    alter table if exists users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists users 
       add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);

    alter table if exists application.attachments 
       add constraint fk_attachment_note 
       foreign key (note_id) 
       references application.notes;

    alter table if exists application.comment_mentions 
       add constraint FKr1pifpe05hf1fjisnjwfr7c9e 
       foreign key (comment_id) 
       references application.note_comments;

    alter table if exists application.note_links 
       add constraint FKv71c5mj1h08r6qwhcm440mmt 
       foreign key (source_note_id) 
       references application.notes;

    alter table if exists application.note_links 
       add constraint FK7tkxq5bkm41r1dcv3d7pj78kk 
       foreign key (target_note_id) 
       references application.notes;

    alter table if exists application.note_metadata 
       add constraint FK2ldkpqvagb5e90ftwqwdq2jfq 
       foreign key (note_id) 
       references application.notes;

    alter table if exists application.note_tags 
       add constraint FK8babdwu6uqiu4rdkeuy8dkna0 
       foreign key (tag_id) 
       references application.tags;

    alter table if exists application.note_tags 
       add constraint FKb15yxop81senc5xs5tjrsy4k4 
       foreign key (note_id) 
       references application.notes;

    alter table if exists application.note_tasks 
       add constraint FKfr9cuj2ebpm7cvrdw2nn63oxe 
       foreign key (task_id) 
       references tasks;

    alter table if exists application.note_tasks 
       add constraint FKm7n42phmobb71bjris303tk1c 
       foreign key (note_id) 
       references application.notes;

    alter table if exists user_auth_providers 
       add constraint FK36nn9pmlugyb6c34h3vakuai 
       foreign key (user_id) 
       references users;

    alter table if exists user_custom_attributes 
       add constraint FKm3alr2tbt01f81njanmr6b6l0 
       foreign key (user_id) 
       references users;

    alter table if exists user_preferences 
       add constraint FKepakpib0qnm82vmaiismkqf88 
       foreign key (user_id) 
       references users;

CREATE TABLE IF NOT EXISTS plugin_registry (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    version VARCHAR(50) NOT NULL,
    description TEXT,
    author VARCHAR(255),
    type VARCHAR(50) NOT NULL,
    runtime VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'INACTIVE',
    path VARCHAR(500),
    endpoint VARCHAR(500),
    config JSONB DEFAULT '{}',
    config_schema JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plugin_events (
    id BIGSERIAL PRIMARY KEY,
    plugin_id BIGINT NOT NULL REFERENCES plugin_registry(id) ON DELETE CASCADE,
    event_type VARCHAR(255) NOT NULL,
    event_action VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(plugin_id, event_type, event_action)
);

CREATE TABLE IF NOT EXISTS plugin_permissions (
    id BIGSERIAL PRIMARY KEY,
    plugin_id BIGINT NOT NULL REFERENCES plugin_registry(id) ON DELETE CASCADE,
    permission VARCHAR(255) NOT NULL,
    granted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(plugin_id, permission)
);

CREATE TABLE IF NOT EXISTS plugin_execution_logs (
    id BIGSERIAL PRIMARY KEY,
    plugin_id BIGINT NOT NULL REFERENCES plugin_registry(id) ON DELETE CASCADE,
    execution_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    message TEXT,
    execution_time_ms BIGINT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plugin_health_checks (
    id BIGSERIAL PRIMARY KEY,
    plugin_id BIGINT NOT NULL REFERENCES plugin_registry(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    message TEXT,
    response_time_ms BIGINT,
    checked_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plugin_config_history (
    id BIGSERIAL PRIMARY KEY,
    plugin_id BIGINT NOT NULL REFERENCES plugin_registry(id) ON DELETE CASCADE,
    config_before JSONB,
    config_after JSONB,
    changed_by VARCHAR(255),
    change_reason TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_plugin_registry_name ON plugin_registry(name);
CREATE INDEX IF NOT EXISTS idx_plugin_registry_status ON plugin_registry(status);
CREATE INDEX IF NOT EXISTS idx_plugin_registry_type ON plugin_registry(type);
CREATE INDEX IF NOT EXISTS idx_plugin_events_plugin_id ON plugin_events(plugin_id);
CREATE INDEX IF NOT EXISTS idx_plugin_events_type ON plugin_events(event_type);
CREATE INDEX IF NOT EXISTS idx_plugin_permissions_plugin_id ON plugin_permissions(plugin_id);
CREATE INDEX IF NOT EXISTS idx_plugin_execution_logs_plugin_id ON plugin_execution_logs(plugin_id);
CREATE INDEX IF NOT EXISTS idx_plugin_execution_logs_created_at ON plugin_execution_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_plugin_health_checks_plugin_id ON plugin_health_checks(plugin_id);
CREATE INDEX IF NOT EXISTS idx_plugin_health_checks_checked_at ON plugin_health_checks(checked_at);

CREATE OR REPLACE FUNCTION update_plugin_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS plugin_registry_updated_at ON plugin_registry;
CREATE TRIGGER plugin_registry_updated_at
    BEFORE UPDATE ON plugin_registry
    FOR EACH ROW
    EXECUTE FUNCTION update_plugin_updated_at();
