all:
  children:
    netcup:
      hosts:
        dev-netcup:
          ansible_host: 10.165.78.189
          ansible_user: ik
          ansible_python_interpreter: /usr/bin/python3
          personal_role: disposable-development-compute
          personal_manage_runtime_units: true
          personal_public_address: 185.162.249.37
          personal_zerotier_address: 10.165.78.189
          personal_zerotier_network_id: 88c5b1f339774e42
          personal_zerotier_interface: ztpp6mnpl3
          personal_enable_ssh_hardening: true
          personal_enable_firewall: true
