apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: my-application-placeholder
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    services: "5"
    configmaps: "10"
    secrets: "10"
