apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: modulo
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  LOGGING_LEVEL_ROOT: "INFO"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  AZURE_APPLICATION_INSIGHTS_WEB_ENABLE_W3C: "true"
  AZURE_APPLICATION_INSIGHTS_LOGGING_LEVEL: "INFO"
  MANAGEMENT_METRICS_EXPORT_AZURE_MONITOR_ENABLED: "true"
