apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: modulo
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  LOGGING_LEVEL_ROOT: "INFO"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  AZURE_APPLICATION_INSIGHTS_WEB_ENABLE_W3C: "true"
  AZURE_APPLICATION_INSIGHTS_LOGGING_LEVEL: "INFO"
  MANAGEMENT_METRICS_EXPORT_AZURE_MONITOR_ENABLED: "true"
  # Database configuration
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  
  # OpenTelemetry Configuration
  OTEL_SERVICE_NAME: "modulo-backend"
  OTEL_SERVICE_VERSION: "1.0.0"
  OTEL_ENVIRONMENT: "production"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=modulo-backend,service.version=1.0.0,deployment.environment=production"
  
  # OpenTelemetry Exporter Configuration
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_COMPRESSION: "gzip"
  
  # OpenTelemetry Sampling (10% in production)
  OTEL_TRACES_SAMPLER: "traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "0.1"
  
  # OpenTelemetry Instrumentation
  OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED: "true"
  OTEL_INSTRUMENTATION_JDBC_ENABLED: "true"
  OTEL_INSTRUMENTATION_HIBERNATE_ENABLED: "true"
  OTEL_INSTRUMENTATION_MICROMETER_ENABLED: "true"
  OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"
  
  # Propagation
  OTEL_PROPAGATORS: "tracecontext,baggage,b3multi"
  
  # Prometheus Metrics
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES_HISTOGRAM_HTTP_SERVER_REQUESTS: "true"
  MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES_HTTP_SERVER_REQUESTS: "0.5,0.9,0.95,0.99"
