apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: my-application-placeholder
type: Opaque
data:
  DATABASE_USERNAME: cGxhY2Vob2xkZXItdXNlcm5hbWU= # placeholder-username
  DATABASE_PASSWORD: cGxhY2Vob2xkZXItcGFzc3dvcmQ= # placeholder-password
  # Add other sensitive data here
  # EXAMPLE_API_KEY: cGxhY2Vob2xkZXItYXBpLWtleQ== # placeholder-api-key
