apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: modulo
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXM= # postgres
  DATABASE_PASSWORD: cG9zdGdyZXM= # postgres
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTozNTQzMi9tb2R1bG8= # jdbc:postgresql://postgres-service:5432/modulo
