apiVersion: v1
kind: Secret
metadata:
  name: app-insights-secret
  namespace: modulo
type: Opaque
stringData:
  connection-string: "REPLACE_WITH_YOUR_CONNECTION_STRING"
  instrumentation-key: "REPLACE_WITH_YOUR_INSTRUMENTATION_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: modulo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: REPLACE_WITH_BASE64_ENCODED_DOCKER_CONFIG
