apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: modulo
  labels:
    app: react-frontend
spec:
  replicas: 1 # Default replicas, can be adjusted
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: frontend-container
        image: ghcr.io/ikey168/modulo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: / # Assuming root path serves the app
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: / # Assuming root path serves the app
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
