apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: my-application-placeholder
  annotations:
    # Use appropriate annotations for your Ingress controller
    # e.g., for Nginx Ingress:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # if paths need rewriting
    # kubernetes.io/ingress.class: "nginx" # if you have multiple ingress controllers
spec:
  rules:
  - host: app.example-placeholder.com # Placeholder hostname
    http:
      paths:
      - path: /api(/|$)(.*) # Routes /api and /api/* to API service
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 8080
      - path: /(|/)(.*) # Routes / and /* to Frontend service
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  # tls: # Optional: Add TLS configuration if needed
  # - hosts:
  #   - app.example-placeholder.com
  #   secretName: app-tls-secret # Assumes a secret 'app-tls-secret' with TLS cert and key exists
