apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulo-api
  namespace: modulo
  labels:
    app: modulo-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modulo-api
  template:
    metadata:
      labels:
        app: modulo-api
        tier: backend
    spec:
      containers:
      - name: api
        image: modulo/api:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: modulo-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: modulo-secrets
              key: redis-url
        # Azure Blob Storage Configuration
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            configMapKeyRef:
              name: azure-storage-config
              key: account-name
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: connection-string
              optional: true
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: account-key
              optional: true
        - name: AZURE_STORAGE_USE_MANAGED_IDENTITY
          valueFrom:
            configMapKeyRef:
              name: azure-storage-config
              key: use-managed-identity
        - name: AZURE_STORAGE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: azure-storage-config
              key: container-name
        - name: AZURE_STORAGE_MAX_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              name: azure-storage-config
              key: max-file-size
        - name: AZURE_CDN_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: azure-storage-config
              key: cdn-endpoint
        - name: AZURE_STORAGE_ALLOWED_CONTENT_TYPES
          valueFrom:
            configMapKeyRef:
              name: azure-storage-config
              key: allowed-content-types
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: modulo-api-service
  namespace: modulo
  labels:
    app: modulo-api
spec:
  selector:
    app: modulo-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
