apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  interval: 5m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.9.11"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets-system
      interval: 12h
  values:
    installCRDs: true
    replicaCount: 1
    
    # Security settings
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop:
        - ALL
    
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
    
    # Resource limits
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    
    # Service monitoring
    serviceMonitor:
      enabled: true
      namespace: external-secrets-system
    
    # Webhook settings
    webhook:
      create: true
      port: 9443
      certCheckInterval: "5m"
      lookaheadInterval: "5m"
    
    # Cert controller settings
    certController:
      create: true
      requeueInterval: "5m"
      
    # Enable metrics
    metrics:
      service:
        enabled: true
        port: 8080
