# Azure Key Vault SecretStore Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: modulo
spec:
  provider:
    azurekv:
      # Azure Key Vault URL - replace with your actual Key Vault
      vaultUrl: "https://modulo-keyvault.vault.azure.net/"
      
      # Authentication method: Service Principal with Secret
      authSecretRef:
        clientId:
          name: azure-keyvault-creds
          key: client-id
        clientSecret:
          name: azure-keyvault-creds
          key: client-secret
      
      tenantId: "REPLACE_WITH_YOUR_TENANT_ID"
      
      # Optional: Environment (AzurePublicCloud is default)
      environmentType: AzurePublicCloud

---
# Backup SecretStore using Kubernetes secrets (for development/testing)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-store
  namespace: modulo
spec:
  provider:
    kubernetes:
      # Service account for accessing secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-sa
      # Remote namespace where secrets are stored
      remoteNamespace: external-secrets-system

---
# ClusterSecretStore for organization-wide secrets (optional)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-cluster-store
spec:
  provider:
    azurekv:
      vaultUrl: "https://modulo-keyvault.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-keyvault-creds
          key: client-id
          namespace: external-secrets-system
        clientSecret:
          name: azure-keyvault-creds
          key: client-secret
          namespace: external-secrets-system
      tenantId: "REPLACE_WITH_YOUR_TENANT_ID"
      environmentType: AzurePublicCloud
