import { useState } from 'react';
import type { CoreNote } from '@modulo/core';
import type { WorkspaceViewProps } from '../plugins/types';
import { usePlugins } from '../plugins/PluginProvider';
import { bodyOf, download, field, now, replaceNote, uid, useAction, useToolStore } from './shared';
import { ToolPage } from './ToolPage';
import { emptyCheckpoints, linkKey, noteChanged, validateCheckpoints, type Checkpoint } from './snapshots';

export default function TimeMachineView({ data }: WorkspaceViewProps) {
  const plugins = usePlugins(); const store = useToolStore('workspace-time-machine', emptyCheckpoints, validateCheckpoints); const action = useAction();
  const [title, setTitle] = useState(''); const [selected, setSelected] = useState('');
  const [preview, setPreview] = useState<{ saved: CoreNote; current?: CoreNote }>(); const [confirmed, setConfirmed] = useState(false);
  const checkpoint = store.value.checkpoints.find(item => item.id === selected);
  const restoredId = (id: number) => checkpoint?.restoredIds?.[id] ?? id;
  const snapshot = (label: string): Checkpoint => ({ id: uid(), title: label, createdAt: now(),
    notes: structuredClone(data.notes), links: structuredClone(data.links),
    plugins: [...plugins.installedIds].map(id => ({ id, enabled: plugins.isEnabled(id) })),
    settings: plugins.preferences?.list().filter(entry => !entry.deleted && entry.schemaId === 'modulo.workspace.hub-tab') ?? [],
  });
  const backup = () => store.save(previous => ({ checkpoints: [snapshot('Before selective restore'), ...previous.checkpoints] }));
  return <ToolPage title="Workspace Time Machine" notice={store.notice}>{action.alert}
    <p className="text-sm">Named checkpoints preserve notes, graph links, installed-plugin state and workspace hub settings. Restore individual items after inspecting them. Attachments and external services are not rolled back.</p>
    <fieldset disabled={!store.ready || action.busy || data.loading} className="flex flex-wrap gap-2"><label>Checkpoint name<input className={field} value={title} onChange={e => setTitle(e.target.value)} /></label>
      <button className={field} disabled={!title.trim()} onClick={() => void action.run(async () => { const next = snapshot(title.trim()); await store.save(previous => ({ checkpoints: [next, ...previous.checkpoints] })); setSelected(next.id); setTitle(''); })}>Save checkpoint</button></fieldset>
    <label className="block">Import saved checkpoint<input type="file" accept="application/json,.json" disabled={!store.ready || action.busy} onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) void action.run(async () => {
      if (file.size > 1000000) throw new Error('Checkpoint exceeds 1 MB.');
      const imported = validateCheckpoints({ checkpoints: [JSON.parse(await file.text())] }).checkpoints[0];
      if (store.value.checkpoints.some(item => item.id === imported.id)) throw new Error('This checkpoint is already saved.');
      if (!window.confirm('Import this checkpoint into the current account? Only import checkpoints exported from this same workspace; note IDs identify its records. Individual restores still require preview.')) return;
      await store.save(previous => ({ checkpoints: [...previous.checkpoints, imported] })); setSelected(imported.id); setPreview(undefined);
    }); }} /></label>
    <select className={field} aria-label="Checkpoint" value={selected} disabled={action.busy} onChange={e => { setSelected(e.target.value); setPreview(undefined); setConfirmed(false); }}><option value="">Choose checkpoint</option>{store.value.checkpoints.map(item => <option key={item.id} value={item.id}>{item.title} · {new Date(item.createdAt).toLocaleString()}</option>)}</select>
    {checkpoint && <section className="space-y-4"><div className="flex flex-wrap gap-2"><button className={field} onClick={() => download(`checkpoint-${checkpoint.id}.json`, checkpoint)}>Export checkpoint</button><button className={field} disabled={action.busy} onClick={() => { if (window.confirm('Remove this saved checkpoint? Current workspace data is unchanged.')) void action.run(async () => { await store.save(previous => ({ checkpoints: previous.checkpoints.filter(item => item.id !== checkpoint.id) })); setSelected(''); }); }}>Remove checkpoint</button></div>
      <h2 className="font-medium">Notes</h2><ul className="divide-y divide-border">{checkpoint.notes.map(saved => { const current = data.notes.find(n => n.id === restoredId(saved.id)); return <li key={saved.id} className="flex flex-wrap justify-between gap-2 py-2"><span>{saved.title} · {!current ? 'Missing or trashed' : noteChanged(saved, current) ? 'Changed' : 'Unchanged'}</span><button className="underline" onClick={() => { setPreview({ saved, current }); setConfirmed(false); }}>Compare and restore</button></li>; })}</ul>
      {data.notes.filter(note => !checkpoint.notes.some(saved => saved.id === note.id)).map(note => <p className="text-sm" key={note.id}>Added since checkpoint: {note.title}</p>)}
      <h2 className="font-medium">Missing relationships</h2>{checkpoint.links.filter(link => !data.links.some(current => linkKey(current) === linkKey({ ...link, sourceNoteId: restoredId(link.sourceNoteId), targetNoteId: restoredId(link.targetNoteId) }))).map(link => <p key={link.id} className="flex flex-wrap gap-2"><span>#{link.sourceNoteId} → #{link.targetNoteId} · {link.linkType}</span><button className="underline" disabled={action.busy || !data.notes.some(n => n.id === restoredId(link.sourceNoteId)) || !data.notes.some(n => n.id === restoredId(link.targetNoteId))} onClick={() => { if (window.confirm('Restore this relationship?')) void action.run(async () => { await backup(); if (await data.createLink(restoredId(link.sourceNoteId), restoredId(link.targetNoteId), link.linkType) === false) throw new Error('Relationship restore failed.'); }); }}>Restore relationship</button></p>)}
      <h2 className="font-medium">Added relationships</h2>{data.links.filter(link => !checkpoint.links.some(saved => linkKey({ ...saved, sourceNoteId: restoredId(saved.sourceNoteId), targetNoteId: restoredId(saved.targetNoteId) }) === linkKey({ ...link, sourceNoteId: restoredId(link.sourceNoteId), targetNoteId: restoredId(link.targetNoteId) }))).map(link => <p key={link.id} className="flex flex-wrap gap-2"><span>#{link.sourceNoteId} → #{link.targetNoteId} · {link.linkType}</span><button className="underline" disabled={action.busy} onClick={() => { if (window.confirm('Remove this relationship added after the checkpoint? A safety checkpoint will be saved.')) void action.run(async () => { await backup(); await data.removeLink(link.id); }); }}>Remove relationship</button></p>)}
      <h2 className="font-medium">Plugins</h2>{checkpoint.plugins.map(item => <p key={item.id} className="flex flex-wrap gap-2"><span>{plugins.manifest(item.id)?.name ?? item.id} · {item.enabled ? 'Enabled' : 'Disabled'}</span><button className="underline" disabled={action.busy || !plugins.manifest(item.id) || item.id === 'workspace-time-machine'} onClick={() => { if (window.confirm(`Restore ${item.id} to ${item.enabled ? 'enabled' : 'disabled'}? Installation may include dependencies.`)) void action.run(async () => { await backup(); if (!plugins.isInstalled(item.id)) await plugins.install(item.id); await plugins.setEnabled(item.id, item.enabled); }); }}>Restore plugin state</button></p>)}
      <h2 className="font-medium">Workspace settings</h2>{checkpoint.settings.map(item => <p key={item.key} className="flex flex-wrap gap-2"><span>{item.key}: {JSON.stringify(item.value)}</span><button className="underline" disabled={action.busy || !plugins.preferences} onClick={() => { if (window.confirm(`Restore workspace setting ${item.key}?`)) void action.run(async () => { await backup(); if (item.schemaId === 'modulo.workspace.hub-tab' && typeof item.value === 'string') await plugins.preferences?.set(item.key, item.value, item.schemaId, 1); }); }}>Restore setting</button></p>)}
    </section>}
    {preview && <section className="space-y-3 border border-border p-4" aria-label="Restore preview"><h2 className="font-medium">Restore {preview.saved.title}</h2><div className="grid gap-4 sm:grid-cols-2"><div><h3>Current</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap text-sm">{preview.current ? `${preview.current.title}\n${bodyOf(preview.current)}` : 'Missing — restored as a new note.'}</pre></div><div><h3>Checkpoint</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap text-sm">{preview.saved.title}{'\n'}{bodyOf(preview.saved)}</pre><p>Tags: {preview.saved.tags.map(t => t.name).join(', ') || 'None'}</p></div></div>
      <label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />Restore this content and tags. A safety checkpoint will be saved first.</label>
      <button className={field} disabled={!confirmed || action.busy || !store.ready || data.loading} onClick={() => void action.run(async () => { await backup(); if (preview.current) await replaceNote(preview.current, { title: preview.saved.title, content: bodyOf(preview.saved) }, preview.saved.tags); else { const note = await data.createNote(preview.saved.title, bodyOf(preview.saved)); if (!note) throw new Error('Could not recreate note.'); await store.save(previous => ({ checkpoints: previous.checkpoints.map(item => item.id === checkpoint?.id ? { ...item, restoredIds: { ...item.restoredIds, [preview.saved.id]: note.id } } : item) })); for (const tag of preview.saved.tags) if (await data.addTag(note.id, tag.name) === false) throw new Error('Note recreated but some tags failed.'); } await data.refresh(); setPreview(undefined); setConfirmed(false); })}>Confirm restore</button>
      <button className={`${field} ml-2`} onClick={() => setPreview(undefined)}>Cancel</button>
    </section>}
  </ToolPage>;
}
