// Packs: curated bundles of plugins plus starter blueprints. Installing a pack
// installs each of its plugins (through the plugin runtime) and adds each of
// its blueprints (through the client-side blueprint store), so one click sets
// up a whole workflow.

import { Archive, BookOpenCheck, BriefcaseBusiness, Car, CircuitBoard, Clapperboard, ClipboardList, Compass, Dices as Dice20, FilePenLine, Gamepad2, GraduationCap, Heart, HeartHandshake, Home, Landmark, Library, Music2, PackageSearch, Radar, Server, ShieldCheck, Shirt, Zap, type LucideIcon } from 'lucide-react';
import { IR_VERSION, type BlueprintIR } from '../../blueprint/blueprintIR';
import {
  AUDIT_CORE_BROWSER_PLUGIN_ID,
  AUDIT_CORE_FINDINGS_PLUGIN_ID,
  AUDIT_CORE_OVERVIEW_PLUGIN_ID,
  AUDIT_CORE_REMEDIATION_PLUGIN_ID,
  AUDIT_CORE_REPORT_PLUGIN_ID,
  AUDIT_CORE_SCOPE_PLUGIN_ID,
  AUDIT_CORE_TESTS_PLUGIN_ID,
  AUDIT_CORE_THREATS_PLUGIN_ID,
  GITHUB_SYNC_PLUGIN_ID,
  CAREER_DASHBOARD_PLUGIN_ID,
  CAREER_DEVELOPMENT_PLUGIN_ID,
  CAREER_OPPORTUNITIES_PLUGIN_ID,
  CAREER_PORTFOLIO_PLUGIN_ID,
  BUSINESS_CONTRACTS_PLUGIN_ID,
  BUSINESS_DASHBOARD_PLUGIN_ID,
  BUSINESS_DIRECTORY_PLUGIN_ID,
  BUSINESS_OBLIGATIONS_PLUGIN_ID,
  BUSINESS_OPERATIONS_PLUGIN_ID,
  BUSINESS_RECONCILIATION_PLUGIN_ID,
  CALENDAR_PLUGIN_ID,
  DATABASE_PLUGIN_ID,
  EDUCATION_ASSIGNMENTS_PLUGIN_ID,
  EDUCATION_CORE_PLUGIN_ID,
  EDUCATION_CURRICULUM_PLUGIN_ID,
  EDUCATION_DASHBOARD_PLUGIN_ID,
  EDUCATION_STUDY_PLUGIN_ID,
  EVIDENCE_CLAIMS_PLUGIN_ID,
  EVIDENCE_DASHBOARD_PLUGIN_ID,
  EVIDENCE_LIBRARY_PLUGIN_ID,
  EVIDENCE_REPRO_PLUGIN_ID,
  ELECTRONICS_DASHBOARD_PLUGIN_ID,
  ELECTRONICS_LAB_PLUGIN_ID,
  ELECTRONICS_PARTS_PLUGIN_ID,
  ELECTRONICS_PROJECTS_PLUGIN_ID,
  EUER_PLUGIN_ID,
  FINANCE_SUBSCRIPTIONS_PLUGIN_ID,
  GRAPH_PLUGIN_ID,
  GOBD_PLUGIN_ID,
  HEALTH_TRACKER_PLUGIN_ID,
  HOBBY_STUDIO_PLUGIN_ID,
  HOBBY_STACK_PLUGIN_ID,
  HOBBY_PRACTICE_PLUGIN_ID,
  HOBBY_FUN_PLUGIN_ID,
  HOBBY_DASHBOARD_PLUGIN_ID,
  HIGHEST_VALUE_FOUNDATION_PLUGIN_IDS,
  HOME_INVENTORY_PLUGIN_ID,
  HOME_MAINTENANCE_PLUGIN_ID,
  HOMELAB_ASSETS_PLUGIN_ID,
  HOMELAB_OPERATIONS_PLUGIN_ID,
  HOMELAB_DASHBOARD_PLUGIN_ID,
  INFORMATION_INTAKE_PLUGIN_ID,
  IPFS_ATTACH_PLUGIN_ID,
  JOURNAL_REFLECTION_PLUGIN_ID,
  LIFE_OS_DASHBOARD_PLUGIN_ID,
  LIFE_OS_EXPLORER_PLUGIN_ID,
  LIFE_OS_PORTABILITY_PLUGIN_ID,
  LIFE_OS_RELATIONS_PLUGIN_ID,
  LIFE_OS_REVIEW_PLUGIN_ID,
  MEAL_PLANNER_PLUGIN_ID,
  MEDIA_LIBRARY_PLUGIN_ID,
  MEDIA_TYPE_PLUGIN_IDS,
  MOBILITY_DASHBOARD_PLUGIN_ID,
  MOBILITY_DOCUMENTS_PLUGIN_ID,
  MOBILITY_OPERATIONS_PLUGIN_ID,
  MOBILITY_VEHICLES_PLUGIN_ID,
  MUSIC_DASHBOARD_PLUGIN_ID,
  MUSIC_LIBRARY_PLUGIN_ID,
  MUSIC_PRACTICE_PLUGIN_ID,
  MUSIC_PROJECTS_PLUGIN_ID,
  KNOWLEDGE_LEARNING_PLUGIN_IDS,
  NOTES_PLUGIN_ID,
  OUTLINE_PLUGIN_ID,
  PARA_CAPTURE_PLUGIN_ID,
  PARA_CORE_PLUGIN_ID,
  PARA_DASHBOARD_PLUGIN_ID,
  PARA_GOALS_PLUGIN_ID,
  PARA_MIGRATION_PLUGIN_ID,
  PDF_EXPORT_PLUGIN_ID,
  PLANNER_PLUGIN_ID,
  RECHNUNG_PLUGIN_ID,
  ROUTINES_PLUGIN_ID,
  SECURITY_DASHBOARD_PLUGIN_ID,
  SECURITY_INCIDENTS_PLUGIN_ID,
  SECURITY_INVENTORY_PLUGIN_ID,
  SECURITY_RESILIENCE_PLUGIN_ID,
  SEMANTIC_SEARCH_PLUGIN_ID,
  SELF_HOSTED_PLUGIN_IDS,
  STYLE_STUDIO_PLUGIN_ID,
  TAGS_PLUGIN_ID,
  TIMESTAMP_PROOFS_PLUGIN_ID,
  PARA_REVIEW_PLUGIN_ID,
  PARA_TASKS_PLUGIN_ID,
  PERSONAL_CRM_PLUGIN_ID,
  PLACES_LIBRARY_PLUGIN_ID,
  WORKOUT_PLANNER_PLUGIN_ID,
  TRAVEL_PLANNER_PLUGIN_ID,
  WISHLIST_PURCHASES_PLUGIN_ID,
  WARDROBE_CLOSET_PLUGIN_ID,
  WARDROBE_DASHBOARD_PLUGIN_ID,
  WEALTH_BALANCE_PLUGIN_ID,
  WEALTH_CASHFLOW_PLUGIN_ID,
  WEALTH_DASHBOARD_PLUGIN_ID,
  WEALTH_INVESTMENTS_PLUGIN_ID,
  TTRPG_CAMPAIGNS_PLUGIN_ID,
  TTRPG_WORLD_PLUGIN_ID,
  TTRPG_SESSIONS_PLUGIN_ID,
  TTRPG_DASHBOARD_PLUGIN_ID,
  TAX_AUTOMATION_PLUGIN_ID,
  ZEITERFASSUNG_PLUGIN_ID,
  WRITING_DASHBOARD_PLUGIN_ID,
  WRITING_EDITORIAL_PLUGIN_ID,
  WRITING_MANUSCRIPTS_PLUGIN_ID,
  WRITING_PUBLISHING_PLUGIN_ID,
} from '../plugins';
import { WORKSPACE_TOOLS } from '../workspaceTools/definitions';
import { MEDIA_TYPE_PLUGIN_DEFINITIONS, type MediaType } from '../mediaLibrary';
import { DECISION_JOURNAL_PLUGIN_ID, SKILL_TREE_PLUGIN_ID, FLASHCARDS_PLUGIN_ID } from '../foundationTools';

export interface PackBlueprint {
  name: string;
  description: string;
  ir: BlueprintIR;
}

export interface Pack {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: string;
  /** Plugins installed when this pack is installed. */
  pluginIds: string[];
  /** Blueprints added when this pack is installed. */
  blueprints: PackBlueprint[];
}

// ── Blueprint builders ───────────────────────────────────────────────────────

const TS = '2024-01-01T00:00:00.000Z';
const node = (id: string, type: string, x: number, y: number) => ({ id, type, nodeVersion: 1, position: { x, y } });
const exec = (id: string, fromNode: string, toNode: string) =>
  ({ id, kind: 'exec' as const, fromNode, fromPin: 'then', toNode, toPin: 'in' });
const data = (id: string, fromNode: string, fromPin: string, toNode: string, toPin: string) =>
  ({ id, kind: 'data' as const, fromNode, fromPin, toNode, toPin });

function bp(name: string, description: string, nodes: BlueprintIR['nodes'], edges: BlueprintIR['edges']): PackBlueprint {
  return { name, description, ir: { irVersion: IR_VERSION, nodes, edges, metadata: { name, description, createdAt: TS, updatedAt: TS } } };
}

const mediaTypeIds = (...types: MediaType[]): string[] => types.map((type) => {
  const plugin = MEDIA_TYPE_PLUGIN_DEFINITIONS.find((definition) => definition.type === type);
  if (!plugin) throw new Error(`Missing media plugin for ${type}`);
  return plugin.pluginId;
});

// ── Catalog ──────────────────────────────────────────────────────────────────

export const PACKS: Pack[] = [
  {
    id: 'pack-workspace-tools', name: 'Workspace Tools',
    description: 'Capture, run procedures, review decisions and changes, compose living documents, restore checkpoints, and move projects between Modulo and local files.',
    icon: ClipboardList, category: 'productivity',
    pluginIds: [NOTES_PLUGIN_ID, ...WORKSPACE_TOOLS.map(tool => tool.id), DECISION_JOURNAL_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-deliberate-learning', name: 'Deliberate Learning',
    description: 'Review decisions against their outcomes, map skill prerequisites, and turn notes into spaced-repetition cards.',
    icon: GraduationCap, category: 'education',
    pluginIds: [NOTES_PLUGIN_ID, DECISION_JOURNAL_PLUGIN_ID, SKILL_TREE_PLUGIN_ID, FLASHCARDS_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-self-hosted-essentials',
    name: 'Self-hosted Essentials',
    description: 'Desktop-native replacements for feeds, web archiving, change detection, document OCR, PDF work, managed files, CalDAV, and ntfy.',
    icon: Server,
    category: 'productivity',
    pluginIds: [...SELF_HOSTED_PLUGIN_IDS],
    blueprints: [],
  },
  {
    id: 'pack-connected-foundations',
    name: 'Connected Foundations',
    description: 'Shared metadata and artwork resolution, media diary and reviews, lists and rankings, universal attachment references, and actionable reminders.',
    icon: PackageSearch,
    category: 'productivity',
    pluginIds: [...HIGHEST_VALUE_FOUNDATION_PLUGIN_IDS],
    blueprints: [],
  },
  {
    id: 'pack-digital-security-identity', name: 'Digital Security & Identity', description: 'Account, device, wallet, and identity posture; rotation reminders; backup verification; recovery readiness; and incident procedures. Metadata only—secrets are rejected.', icon: ShieldCheck, category: 'security',
    pluginIds: [SECURITY_INVENTORY_PLUGIN_ID, SECURITY_RESILIENCE_PLUGIN_ID, SECURITY_INCIDENTS_PLUGIN_ID, SECURITY_DASHBOARD_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-personal-finance-wealth', name: 'Personal Finance & Wealth', description: 'Provider-neutral accounts, assets, liabilities, cash flow, savings, investments, goals, and net-worth snapshots.', icon: Landmark, category: 'wealth',
    pluginIds: [WEALTH_BALANCE_PLUGIN_ID, WEALTH_CASHFLOW_PLUGIN_ID, WEALTH_INVESTMENTS_PLUGIN_ID, WEALTH_DASHBOARD_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-research-evidence-lab', name: 'Research Evidence Lab', description: 'Sources, quotations, claims, supporting and opposing evidence, bibliographies, procedures, environments, and reproducibility records.', icon: BookOpenCheck, category: 'evidence',
    pluginIds: [EVIDENCE_LIBRARY_PLUGIN_ID, EVIDENCE_CLAIMS_PLUGIN_ID, EVIDENCE_REPRO_PLUGIN_ID, EVIDENCE_DASHBOARD_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-career-studio', name: 'Career Studio', description: 'Roles, CV variants, accomplishments, applications, interviews, offers, portfolio evidence, skills, certifications, and development.', icon: BriefcaseBusiness, category: 'career',
    pluginIds: [CAREER_PORTFOLIO_PLUGIN_ID, CAREER_OPPORTUNITIES_PLUGIN_ID, CAREER_DEVELOPMENT_PLUGIN_ID, CAREER_DASHBOARD_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-writing-publishing-studio', name: 'Writing & Publishing Studio', description: 'Manuscripts, drafts, editorial stages, feedback, submissions, rights, releases, publication tracking, and writing momentum.', icon: FilePenLine, category: 'writing',
    pluginIds: [NOTES_PLUGIN_ID, PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, WRITING_MANUSCRIPTS_PLUGIN_ID, WRITING_EDITORIAL_PLUGIN_ID, WRITING_PUBLISHING_PLUGIN_ID, WRITING_DASHBOARD_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-travel-mobility', name: 'Travel & Mobility', description: 'Trips and itineraries extended with vehicles, mileage, maintenance, inspections, licenses, permits, insurance, tolls, and transport passes.', icon: Car, category: 'mobility',
    pluginIds: [TRAVEL_PLANNER_PLUGIN_ID, PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, MOBILITY_VEHICLES_PLUGIN_ID, MOBILITY_OPERATIONS_PLUGIN_ID, MOBILITY_DOCUMENTS_PLUGIN_ID, MOBILITY_DASHBOARD_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-audit-core-viewer',
    name: 'Audit Core Viewer',
    description: 'A read-only frontend for audit-core output JSONs: phase status, scope, architecture, threats, invariants, findings, tests, exploits, severity, reports, and remediation.',
    icon: ShieldCheck,
    category: 'audit',
    pluginIds: [
      AUDIT_CORE_BROWSER_PLUGIN_ID,
      AUDIT_CORE_OVERVIEW_PLUGIN_ID,
      AUDIT_CORE_SCOPE_PLUGIN_ID,
      AUDIT_CORE_THREATS_PLUGIN_ID,
      AUDIT_CORE_FINDINGS_PLUGIN_ID,
      AUDIT_CORE_TESTS_PLUGIN_ID,
      AUDIT_CORE_REPORT_PLUGIN_ID,
      AUDIT_CORE_REMEDIATION_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-business-administration',
    name: 'Business Administration',
    description: 'Clients and engagements, proposals and contracts, expense evidence and reconciliation, filings, vendors, correspondence, invoicing, time, EÜR/DATEV, GoBD retention, tax automations, and a Business Command Center.',
    icon: BriefcaseBusiness,
    category: 'business',
    pluginIds: [
      BUSINESS_DIRECTORY_PLUGIN_ID,
      BUSINESS_CONTRACTS_PLUGIN_ID,
      RECHNUNG_PLUGIN_ID,
      ZEITERFASSUNG_PLUGIN_ID,
      EUER_PLUGIN_ID,
      GOBD_PLUGIN_ID,
      TAX_AUTOMATION_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      BUSINESS_RECONCILIATION_PLUGIN_ID,
      BUSINESS_OBLIGATIONS_PLUGIN_ID,
      BUSINESS_OPERATIONS_PLUGIN_ID,
      BUSINESS_DASHBOARD_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-life-os-integration-portability',
    name: 'Life OS Integration & Portability',
    description: 'A read-mostly command layer over specialist stores: universal search, activity and artifacts, cross-plugin relations, integrated reviews, data health, and provider-neutral export or restore.',
    icon: HeartHandshake,
    category: 'life-os',
    pluginIds: [LIFE_OS_EXPLORER_PLUGIN_ID, LIFE_OS_RELATIONS_PLUGIN_ID, LIFE_OS_REVIEW_PLUGIN_ID, LIFE_OS_PORTABILITY_PLUGIN_ID, LIFE_OS_DASHBOARD_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-media-library',
    name: 'Media Library',
    description: 'One shared library with focused plugins for books, ebooks, audiobooks, short stories, novellas, essays, articles, comics, manga, magazines, poetry, movies, TV series, YouTube videos, animation, albums, songs, podcasts, video games, courses, and live performances.',
    icon: Library,
    category: 'media',
    pluginIds: [MEDIA_LIBRARY_PLUGIN_ID, ...MEDIA_TYPE_PLUGIN_IDS],
    blueprints: [],
  },
  {
    id: 'pack-health-training',
    name: 'Health & Training',
    description: 'Appointments, measurements, workouts, meals, habits, recovery, and time-blocked planning in one personal health workflow.',
    icon: Heart,
    category: 'life',
    pluginIds: [PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, ROUTINES_PLUGIN_ID, HEALTH_TRACKER_PLUGIN_ID, WORKOUT_PLANNER_PLUGIN_ID, MEAL_PLANNER_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-home-operations',
    name: 'Home Operations',
    description: 'Maintenance, chores, possessions, warranties, household subscriptions, planned purchases, and recurring home work.',
    icon: Home,
    category: 'life',
    pluginIds: [PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, HOME_MAINTENANCE_PLUGIN_ID, HOME_INVENTORY_PLUGIN_ID, FINANCE_SUBSCRIPTIONS_PLUGIN_ID, WISHLIST_PURCHASES_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-reading-learning',
    name: 'Reading & Learning',
    description: 'Reading shelves, courses, curricula, study sessions, assignments, notes, and PARA-linked learning projects.',
    icon: Library,
    category: 'education',
    pluginIds: [
      MEDIA_LIBRARY_PLUGIN_ID,
      ...mediaTypeIds('Book', 'Ebook', 'Audiobook', 'Short story', 'Novella', 'Essay', 'Article', 'Comic & graphic novel', 'Manga', 'Magazine & zine', 'Poetry', 'Course'),
      EDUCATION_CORE_PLUGIN_ID,
      EDUCATION_CURRICULUM_PLUGIN_ID,
      EDUCATION_STUDY_PLUGIN_ID,
      EDUCATION_ASSIGNMENTS_PLUGIN_ID,
      EDUCATION_DASHBOARD_PLUGIN_ID,
      NOTES_PLUGIN_ID,
      PARA_CORE_PLUGIN_ID,
      PARA_TASKS_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      ...KNOWLEDGE_LEARNING_PLUGIN_IDS,
    ],
    blueprints: [],
  },
  {
    id: 'pack-film-screen',
    name: 'Film & Screen',
    description: 'Focused shelves for movies, television, animation, and YouTube with ratings, watch status, progress, artwork, and release planning.',
    icon: Clapperboard,
    category: 'media',
    pluginIds: [MEDIA_LIBRARY_PLUGIN_ID, ...mediaTypeIds('Movie', 'TV series', 'YouTube video', 'Animation'), CALENDAR_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-relationships-social-life',
    name: 'Relationships & Social Life',
    description: 'People, follow-ups, shared places, trips, reflections, gifts, and plans for keeping relationships active.',
    icon: HeartHandshake,
    category: 'life',
    pluginIds: [PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, PERSONAL_CRM_PLUGIN_ID, PLACES_LIBRARY_PLUGIN_ID, TRAVEL_PLANNER_PLUGIN_ID, JOURNAL_REFLECTION_PLUGIN_ID, WISHLIST_PURCHASES_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-creative-studio',
    name: 'Creative Studio',
    description: 'Research, references, manuscripts, editorial work, publishing, notes, projects, and a practical creative schedule.',
    icon: FilePenLine,
    category: 'writing',
    pluginIds: [
      NOTES_PLUGIN_ID,
      PARA_CORE_PLUGIN_ID,
      PARA_TASKS_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      MEDIA_LIBRARY_PLUGIN_ID,
      INFORMATION_INTAKE_PLUGIN_ID,
      'daily-briefing', 'topic-watchlists', 'newsletter-inbox',
      WRITING_MANUSCRIPTS_PLUGIN_ID,
      WRITING_EDITORIAL_PLUGIN_ID,
      WRITING_PUBLISHING_PLUGIN_ID,
      WRITING_DASHBOARD_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-digital-archive',
    name: 'Digital Archive',
    description: 'Durable notes and documents with tags, search, PDF export, Git synchronization, IPFS attachments, and timestamp proofs.',
    icon: Archive,
    category: 'productivity',
    pluginIds: [NOTES_PLUGIN_ID, TAGS_PLUGIN_ID, SEMANTIC_SEARCH_PLUGIN_ID, PDF_EXPORT_PLUGIN_ID, GITHUB_SYNC_PLUGIN_ID, IPFS_ATTACH_PLUGIN_ID, TIMESTAMP_PROOFS_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-collectors-cabinet',
    name: "Collector's Cabinet",
    description: 'Catalog media, possessions, wardrobe pieces, and wanted items with tags, ratings, artwork, and provenance records.',
    icon: PackageSearch,
    category: 'life',
    pluginIds: [MEDIA_LIBRARY_PLUGIN_ID, ...MEDIA_TYPE_PLUGIN_IDS, HOME_INVENTORY_PLUGIN_ID, WARDROBE_CLOSET_PLUGIN_ID, WISHLIST_PURCHASES_PLUGIN_ID, TAGS_PLUGIN_ID, TIMESTAMP_PROOFS_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-freelancer-toolkit',
    name: 'Freelancer Toolkit',
    description: 'Clients, contracts, delivery, opportunities, time, invoices, expenses, filings, tax records, and project execution.',
    icon: BriefcaseBusiness,
    category: 'business',
    pluginIds: [
      PARA_CORE_PLUGIN_ID,
      PARA_TASKS_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      CAREER_PORTFOLIO_PLUGIN_ID,
      CAREER_OPPORTUNITIES_PLUGIN_ID,
      CAREER_DEVELOPMENT_PLUGIN_ID,
      CAREER_DASHBOARD_PLUGIN_ID,
      BUSINESS_DIRECTORY_PLUGIN_ID,
      BUSINESS_CONTRACTS_PLUGIN_ID,
      BUSINESS_RECONCILIATION_PLUGIN_ID,
      BUSINESS_OBLIGATIONS_PLUGIN_ID,
      BUSINESS_OPERATIONS_PLUGIN_ID,
      BUSINESS_DASHBOARD_PLUGIN_ID,
      RECHNUNG_PLUGIN_ID,
      ZEITERFASSUNG_PLUGIN_ID,
      EUER_PLUGIN_ID,
      GOBD_PLUGIN_ID,
      TAX_AUTOMATION_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-travel-journal',
    name: 'Travel Journal',
    description: 'Trips, places, people, reflections, travel media, supporting notes, attachments, and itinerary planning.',
    icon: Car,
    category: 'life',
    pluginIds: [PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, TRAVEL_PLANNER_PLUGIN_ID, PLACES_LIBRARY_PLUGIN_ID, PERSONAL_CRM_PLUGIN_ID, JOURNAL_REFLECTION_PLUGIN_ID, MEDIA_LIBRARY_PLUGIN_ID, NOTES_PLUGIN_ID, IPFS_ATTACH_PLUGIN_ID],
    blueprints: [],
  },
  {
    id: 'pack-homelab-infrastructure', name: 'Homelab & Infrastructure', description: 'Infrastructure topology, services, deployments, changes, incidents, maintenance, backups, restore tests, and experiments.', icon: Server, category: 'homelab',
    pluginIds: [HOBBY_STACK_PLUGIN_ID, PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, HOMELAB_ASSETS_PLUGIN_ID, HOMELAB_OPERATIONS_PLUGIN_ID, HOMELAB_DASHBOARD_PLUGIN_ID, INFORMATION_INTAKE_PLUGIN_ID, HOME_INVENTORY_PLUGIN_ID, WISHLIST_PURCHASES_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-wardrobe-style', name: 'Wardrobe & Style', description: 'Garments, outfits, capsules, silhouettes, archetypes, wears, experiments, repairs, alterations, and seasonal wardrobe health.', icon: Shirt, category: 'style',
    pluginIds: [HOBBY_STACK_PLUGIN_ID, PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, WARDROBE_CLOSET_PLUGIN_ID, STYLE_STUDIO_PLUGIN_ID, WARDROBE_DASHBOARD_PLUGIN_ID, HOME_INVENTORY_PLUGIN_ID, WISHLIST_PURCHASES_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-ttrpg-campaign-studio', name: 'TTRPG Campaign Studio', description: 'Campaigns, groups, world entities, characters, session prep, recaps, decisions, continuity, safety, and recurring community.', icon: Dice20, category: 'ttrpg',
    pluginIds: [HOBBY_STACK_PLUGIN_ID, PLANNER_PLUGIN_ID, CALENDAR_PLUGIN_ID, TTRPG_CAMPAIGNS_PLUGIN_ID, TTRPG_WORLD_PLUGIN_ID, TTRPG_SESSIONS_PLUGIN_ID, TTRPG_DASHBOARD_PLUGIN_ID, PERSONAL_CRM_PLUGIN_ID, NOTES_PLUGIN_ID], blueprints: [],
  },
  {
    id: 'pack-music-maker',
    name: 'Music Maker',
    description: 'Production projects, instrument practice, repertoire, theory, samples, presets, modular patches, studio gear, references, setlists, releases, and a music dashboard.',
    icon: Music2,
    category: 'music',
    pluginIds: [
      HOBBY_STACK_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      MUSIC_PROJECTS_PLUGIN_ID,
      MUSIC_PRACTICE_PLUGIN_ID,
      MUSIC_LIBRARY_PLUGIN_ID,
      MUSIC_DASHBOARD_PLUGIN_ID,
      MEDIA_LIBRARY_PLUGIN_ID,
      EDUCATION_CORE_PLUGIN_ID,
      HOME_INVENTORY_PLUGIN_ID,
      PERSONAL_CRM_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-electronics-workbench',
    name: 'Electronics Workbench',
    description: 'Electronics projects, components, stock, BOM procurement, prototypes, PCBs, assembly, tests, firmware, enclosures, repairs, and bench health.',
    icon: CircuitBoard,
    category: 'electronics',
    pluginIds: [
      HOBBY_STACK_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      ELECTRONICS_PROJECTS_PLUGIN_ID,
      ELECTRONICS_PARTS_PLUGIN_ID,
      ELECTRONICS_LAB_PLUGIN_ID,
      ELECTRONICS_DASHBOARD_PLUGIN_ID,
      INFORMATION_INTAKE_PLUGIN_ID,
      EDUCATION_CORE_PLUGIN_ID,
      HOME_INVENTORY_PLUGIN_ID,
      WISHLIST_PURCHASES_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-full-stack-hobbies',
    name: 'Full-Stack Hobbies',
    description: 'Active and queued hobby lanes, six-session experiments, day-block practice, artifacts, energy-aware fun, and social-depth signals.',
    icon: Gamepad2,
    category: 'hobbies',
    pluginIds: [
      PARA_CORE_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      HOBBY_STACK_PLUGIN_ID,
      HOBBY_PRACTICE_PLUGIN_ID,
      HOBBY_FUN_PLUGIN_ID,
      HOBBY_DASHBOARD_PLUGIN_ID,
      MEAL_PLANNER_PLUGIN_ID,
      WORKOUT_PLANNER_PLUGIN_ID,
      MEDIA_LIBRARY_PLUGIN_ID,
      PLACES_LIBRARY_PLUGIN_ID,
      PERSONAL_CRM_PLUGIN_ID,
      WISHLIST_PURCHASES_PLUGIN_ID,
      HOME_INVENTORY_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-research-lab',
    name: 'Research Lab — Information Intake Modes',
    description: 'Signed-in Information Intake with Noesis workflows for Awareness, Exploration, Deep Research, Decision Support, Problem-Solving, Creation, Externalization, Internalization, Iteration, and Maintenance.',
    icon: Radar,
    category: 'research',
    pluginIds: [
      PARA_CORE_PLUGIN_ID,
      NOTES_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      INFORMATION_INTAKE_PLUGIN_ID,
      'daily-briefing', 'topic-watchlists', 'newsletter-inbox',
    ],
    blueprints: [],
  },
  {
    id: 'pack-education-system',
    name: 'Education System',
    description: 'Programs and courses, hierarchical curricula, day-block study planning, assignments and assessments, and a progress dashboard.',
    icon: GraduationCap,
    category: 'education',
    pluginIds: [
      EDUCATION_CORE_PLUGIN_ID,
      EDUCATION_CURRICULUM_PLUGIN_ID,
      EDUCATION_STUDY_PLUGIN_ID,
      EDUCATION_ASSIGNMENTS_PLUGIN_ID,
      EDUCATION_DASHBOARD_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-personal-life',
    name: 'Personal Life',
    description: 'Routines, food, fitness, health, home, inventory, money, relationships, travel, hobbies, purchases, places, reflection, and media.',
    icon: Heart,
    category: 'life',
    pluginIds: [
      PLANNER_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      ROUTINES_PLUGIN_ID,
      MEAL_PLANNER_PLUGIN_ID,
      WORKOUT_PLANNER_PLUGIN_ID,
      HEALTH_TRACKER_PLUGIN_ID,
      HOME_MAINTENANCE_PLUGIN_ID,
      HOME_INVENTORY_PLUGIN_ID,
      FINANCE_SUBSCRIPTIONS_PLUGIN_ID,
      PERSONAL_CRM_PLUGIN_ID,
      TRAVEL_PLANNER_PLUGIN_ID,
      HOBBY_STUDIO_PLUGIN_ID,
      WISHLIST_PURCHASES_PLUGIN_ID,
      PLACES_LIBRARY_PLUGIN_ID,
      JOURNAL_REFLECTION_PLUGIN_ID,
      MEDIA_LIBRARY_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-modified-para',
    name: 'Modified PARA',
    description: 'Canonical PARA plus capture, day planning, routines and habits, meals, workouts, media, goals and arcs, reviews, and a Life Command Center.',
    icon: Compass,
    category: 'para',
    pluginIds: [
      PARA_CORE_PLUGIN_ID,
      PARA_CAPTURE_PLUGIN_ID,
      PARA_TASKS_PLUGIN_ID,
      PARA_GOALS_PLUGIN_ID,
      PARA_REVIEW_PLUGIN_ID,
      PARA_DASHBOARD_PLUGIN_ID,
      PARA_MIGRATION_PLUGIN_ID,
      PLANNER_PLUGIN_ID,
      ROUTINES_PLUGIN_ID,
      CALENDAR_PLUGIN_ID,
      MEAL_PLANNER_PLUGIN_ID,
      WORKOUT_PLANNER_PLUGIN_ID,
      HEALTH_TRACKER_PLUGIN_ID,
      HOME_MAINTENANCE_PLUGIN_ID,
      HOME_INVENTORY_PLUGIN_ID,
      FINANCE_SUBSCRIPTIONS_PLUGIN_ID,
      PERSONAL_CRM_PLUGIN_ID,
      TRAVEL_PLANNER_PLUGIN_ID,
      HOBBY_STUDIO_PLUGIN_ID,
      WISHLIST_PURCHASES_PLUGIN_ID,
      PLACES_LIBRARY_PLUGIN_ID,
      JOURNAL_REFLECTION_PLUGIN_ID,
      MEDIA_LIBRARY_PLUGIN_ID,
      NOTES_PLUGIN_ID,
    ],
    blueprints: [],
  },
  {
    id: 'pack-knowledge-base',
    name: 'Knowledge Base',
    description: 'Notes, the knowledge graph, and document outlines, with a blueprint that summarizes every note you save.',
    icon: Library,
    category: 'productivity',
    pluginIds: [NOTES_PLUGIN_ID, GRAPH_PLUGIN_ID, OUTLINE_PLUGIN_ID],
    blueprints: [
      bp(
        'Summarize on save',
        'When a note is saved, generate an AI summary of it.',
        [node('n1', 'trigger.note.saved', 40, 40), node('n2', 'action.ai.summarize', 360, 40)],
        [exec('e1', 'n1', 'n2'), data('e2', 'n1', 'note', 'n2', 'note')],
      ),
    ],
  },
  {
    id: 'pack-project-tracker',
    name: 'Project Tracker',
    description: 'Notes plus embedded databases for tables and boards, with a blueprint that tags new notes automatically.',
    icon: ClipboardList,
    category: 'productivity',
    pluginIds: [NOTES_PLUGIN_ID, DATABASE_PLUGIN_ID],
    blueprints: [
      bp(
        'Tag new notes',
        'When a note is saved, add a tag to it.',
        [node('n1', 'trigger.note.saved', 40, 40), node('n2', 'action.tag.add', 360, 40)],
        [exec('e1', 'n1', 'n2'), data('e2', 'n1', 'note', 'n2', 'note')],
      ),
    ],
  },
  {
    id: 'pack-automation-starter',
    name: 'Automation Starter',
    description: 'Markdown notes plus two starter automations: a scheduled task and on-save on-chain anchoring.',
    icon: Zap,
    category: 'automation',
    pluginIds: [NOTES_PLUGIN_ID],
    blueprints: [
      bp(
        'Scheduled task',
        'Run a sandboxed script on a schedule.',
        [node('n1', 'trigger.schedule', 40, 40), node('n2', 'action.code.execute', 360, 40)],
        [exec('e1', 'n1', 'n2')],
      ),
      bp(
        'Anchor on save',
        'When a note is saved, anchor its content hash on-chain.',
        [node('n1', 'trigger.note.saved', 40, 40), node('n2', 'action.note.anchor', 360, 40)],
        [exec('e1', 'n1', 'n2'), data('e2', 'n1', 'note', 'n2', 'note')],
      ),
    ],
  },
];
