import type { AreaChecklistHealth, ParaArea } from './para';
import { AREA_REQUIREMENT_DETAILS } from './areaRequirementDetails';

// Criteria for every active imported area. These remain editable in each Area.
const AREA_CRITERIA: Record<string, [string, string, string, string]> = {
  "Adventure, Travel & Exploration": ["Identify the practical obstacle stopping trips or exploration.", "List desired trips and the time, money, or logistics they require.", "Plan and complete manageable outings or trips.", "Travel and exploration happen at a sustainable pace within available resources."],
  "Cultural Sampling & Events": ["Find one accessible event to restart cultural outings.", "Keep a shortlist of venues and events worth attending.", "Attend selected events and note what resonates.", "Cultural events are chosen intentionally and attended without last-minute scramble."],
  "Local Exploration & Micro-Adventures": ["Choose a nearby place that is easy to visit soon.", "Collect nearby routes and places by travel time.", "Take regular local outings and vary the places visited.", "Local exploration is a repeatable part of life without needing major trip planning."],
  "Outdoor & Nature Activities": ["Choose an achievable outdoor activity and check needed gear.", "List suitable hikes, parks, and seasonal activities.", "Spend time outdoors regularly and build the habit safely.", "Outdoor time fits the season and gear and happens consistently."],
  "Travel Gear & Logistics": ["Identify missing documents or essentials for the next trip.", "Keep travel documents, luggage, and checklists in one place.", "Use and refine a packing and booking routine.", "Travel essentials are ready and logistics can be handled without avoidable stress."],
  "Trips & Itineraries": ["Choose the next trip and resolve its first blocking decision.", "Capture bookings, dates, routes, and packing needs.", "Maintain a realistic itinerary and complete bookings in time.", "Upcoming trips have clear logistics; past trip notes remain useful."],
  "Art & Aesthetic Life": ["Choose one creative or cultural practice to restart.", "Separate active making from media and art wishlists.", "Make, attend, or reflect on art regularly.", "Creative practice and cultural enjoyment have a sustainable place in life."],
  "Art Communities & Scenes": ["Reconnect with one relevant creative person or venue.", "List communities and events that actually feel welcoming.", "Attend gatherings and build a few recurring connections.", "Creative relationships and scenes are sustained through regular participation."],
  "Craft & Making": ["Choose a small making project and gather basic materials.", "Keep tools and project ideas organized by current interest.", "Finish small pieces and practice a chosen craft.", "Making happens regularly, with usable tools and completed work."],
  "Digital Aesthetic": ["Remove a distracting or broken part of the digital setup.", "Capture preferred themes, fonts, and setup changes.", "Use a coherent setup and refine it when needed.", "Digital appearance supports focus and is easy to maintain."],
  "Music Making": ["Choose an instrument or production session to resume.", "List current skills, equipment, and unfinished tracks.", "Practice or produce on a repeatable schedule.", "Music making produces regular practice or finished pieces."],
  "Performance & Live Arts": ["Choose one attainable live performance to attend or try.", "Track venues, dates, and participation opportunities.", "Attend or take part in live arts regularly.", "Live performance remains an active, enjoyable part of life."],
  "Taste Development": ["Record what currently feels meaningful in art and design.", "Collect examples with a short note on why they resonate.", "Compare examples and refine personal preferences.", "Preferences are clear enough to guide choices and keep evolving."],
  "Visual Practice": ["Choose a small drawing, photo, or visual exercise.", "Keep materials and practice ideas easy to access.", "Make visual work regularly and review what improves.", "Visual practice is sustained and shows a body of work."],
  "Writing & Prose": ["Choose a short writing exercise and make time for it.", "Capture drafts and ideas in one accessible place.", "Write regularly and revise selected pieces.", "Writing practice is steady and produces work worth keeping."],
  "Community & Contribution": ["Choose one contribution that fits current capacity.", "List commitments and causes that have a real connection.", "Participate or contribute on a repeatable cadence.", "Community commitments are meaningful, sustainable, and followed through."],
  "Digital Systems": ["Identify the digital failure most likely to disrupt daily life.", "Inventory accounts, devices, data, and recurring maintenance.", "Maintain backups, updates, and access routines.", "Important digital systems are secure, recoverable, and easy to use."],
  "Accounts, Identity & Access": ["Secure any account with lost or weak access.", "Inventory critical accounts and recovery methods.", "Maintain strong sign-in and recovery settings.", "Important accounts have reliable access and tested recovery routes."],
  "Automation & Integrations": ["Stop or repair an automation causing active trouble.", "Inventory integrations and identify owners or dependencies.", "Keep useful automations running and document their triggers.", "Automations save effort reliably and failures are noticed promptly."],
  "Browsing & Information Hygiene": ["Remove the largest current source of distracting browsing.", "Identify feeds, sites, and notification patterns that waste attention.", "Follow intentional browsing and information intake routines.", "Information intake supports decisions without taking over attention."],
  "Cloud Services & Sync": ["Resolve files that are missing or out of sync.", "Identify a source of truth for key files and folders.", "Use organized storage and verify sync across devices.", "Important files sync reliably and can be found quickly."],
  "Communication Systems": ["Fix a missed or overwhelming communication channel.", "Map channels, notification rules, and response expectations.", "Use clear communication windows and notification settings.", "Important messages are seen on time without constant interruption."],
  "Data Management & Backups": ["Protect data that currently has no usable backup.", "Identify important data, backup locations, and restore steps.", "Run backups and test a restore on a schedule.", "Important data is backed up and recoverable when needed."],
  "Devices & Operating Environments": ["Stabilize an unreliable or outdated essential device.", "List device configurations, updates, and replacement needs.", "Keep devices updated and document repeatable setup steps.", "Devices are dependable, current, and easy to restore or replace."],
  "Digital Compliance & Records": ["Secure any missing or at-risk important digital document.", "Organize digital records by type and retention need.", "Digitize and file new records consistently.", "Important records are complete, retrievable, and retained appropriately."],
  "Digital Finance Ops": ["Resolve a failed payment or inaccessible financial account.", "Inventory bank apps, payment methods, and statements.", "Review payment activity and reconcile statements regularly.", "Financial apps and payment flows work reliably with clear records."],
  "Home Network & Connectivity": ["Restore unstable or insecure home connectivity.", "Document network equipment, passwords, and failure points.", "Maintain router updates and test connectivity fallback.", "Home connectivity is stable, secure, and recoverable."],
  "Media, Entertainment & Subscriptions": ["Cancel or fix a costly unused media subscription.", "Inventory services and actual use.", "Review services and choose media intentionally.", "Media spending and consumption match current priorities."],
  "Security & Privacy": ["Close an exposed account or critical security gap.", "List passwords, 2FA, devices, and privacy settings needing attention.", "Improve security settings and check them periodically.", "Accounts and devices use strong protection with a workable recovery plan."],
  "Work/Dev Environment": ["Restore a broken work or development setup.", "Document tools, dependencies, and setup friction.", "Keep a reproducible development setup and update it deliberately.", "Work tools are reliable and can be rebuilt from documentation."],
  "Environment, Lifestyle & Identity in the World": ["Fix the home or daily routine causing the most friction.", "Map spaces, routines, and practical lifestyle needs.", "Improve one environment or routine at a time.", "Daily surroundings and rhythms support how life is actually lived."],
  "Daily Rhythms & Lifestyle Design": ["Establish a workable default for the next day.", "Identify recurring time demands and weak points in the week.", "Use a realistic weekly structure and adjust it from experience.", "Daily rhythms support responsibilities, rest, and flexibility."],
  "Digital Environment & Devices": ["Resolve the most disruptive device or app issue.", "List the OS, apps, themes, and workflows worth maintaining.", "Maintain a useful device setup and simplify friction.", "Digital tools support daily work without recurring setup problems."],
  "Food & Home Operations": ["Restore essential meals or household upkeep this week.", "List food, cleaning, and supply routines that need ownership.", "Run a simple meal and household maintenance cadence.", "Food, cleaning, and supplies are handled reliably."],
  "Home & Living": ["Fix an unsafe or unusable part of the home.", "List room functions, storage problems, and needed changes.", "Improve layout, storage, and atmosphere in small steps.", "Home zones are functional, comfortable, and easy to maintain."],
  "Local Life & Neighbourhood": ["Identify essential nearby services and routes.", "Keep a shortlist of places, errands, and local routines.", "Use neighbourhood services and explore useful routes.", "Local life is easy to navigate and includes places worth returning to."],
  "Objects, Tools & Gear": ["Repair or replace a tool that blocks daily tasks.", "Inventory useful gear and remove duplicate or broken items.", "Keep essential tools accessible and in working order.", "Gear supports daily routines without clutter or repeated replacement."],
  "Style & Personal Presentation": ["Address missing clothing or grooming basics.", "Identify outfits and grooming routines that fit current life.", "Maintain a small set of wearable looks and regular care.", "Presentation feels authentic and is easy to sustain."],
  "Wardrobe & Personal Style": ["Identify clothing gaps for current work and weather.", "Inventory clothes, fit issues, and useful outfit combinations.", "Wear and refine a practical wardrobe instead of impulse buying.", "The wardrobe fits, works for recurring situations, and is maintained."],
  "Learning & Education": ["Choose the most relevant learning commitment now.", "Separate active courses from reference material and future interests.", "Follow a course or study plan and apply what is learned.", "Learning commitments progress at a sustainable pace and produce usable skills."],
  "Creative Output – Code & Tech": ["Choose a small build that can be completed.", "List active code ideas, dependencies, and unfinished projects.", "Ship small tools or contributions and learn from feedback.", "Code projects produce useful, maintained outcomes."],
  "Creative Output – Music & Audio": ["Choose one track, recording, or audio exercise to resume.", "Organize unfinished sessions and production ideas.", "Work on audio regularly and finish selected pieces.", "Music or audio work reaches finished, shareable form when intended."],
  "Creative Output – Writing": ["Select one draft or publishing idea to develop.", "Keep publication ideas and drafts in a clear pipeline.", "Write, revise, and release selected pieces.", "Writing output reaches its intended readers at a sustainable pace."],
  "Experiments & Labs": ["Choose one small hypothesis that can be tested.", "Keep experiment ideas separate from active tests.", "Run bounded tests and record results.", "Experiments produce decisions or learning without accumulating indefinitely."],
  "Formal Education & Courses": ["Resolve a missed course deadline or enrollment issue.", "List active courses, syllabi, and assessment dates.", "Complete coursework on schedule and apply lessons.", "Formal study obligations are met and progress is documented."],
  "Knowledge Management & Notes": ["Recover important notes that are hard to find.", "Define where notes go and how they are retrieved.", "Capture and refine useful notes regularly.", "Knowledge can be found, connected, and used when needed."],
  "Self-Study & Skill Stacks": ["Choose the next skill and a first study session.", "Outline a small curriculum and track learning resources.", "Practice the skill and apply it in real work.", "Self-study produces demonstrable capability rather than collected materials."],
  "Meaning, Philosophy & Spirituality": ["Make room for reflection on a pressing question.", "Identify beliefs, practices, and questions worth revisiting.", "Reflect or practice regularly and update views with experience.", "Values and practices help guide decisions without requiring certainty."],
  "Life Philosophy & Ethics": ["Write down the value conflict currently affecting a decision.", "Identify principles that matter and where they conflict.", "Use those principles in actual choices and revise them thoughtfully.", "Ethical principles are clear enough to guide recurring decisions."],
  "Mortality & Long-Term Perspective": ["Acknowledge an avoided long-term concern without forcing a full plan.", "Capture questions about aging, time, and long horizons.", "Reflect on long-term priorities and adjust present choices.", "Long-term perspective informs priorities without crowding daily life."],
  "Practices, Rituals & Contemplation": ["Resume one brief contemplative practice.", "List practices that help and realistic times to do them.", "Repeat a chosen ritual or contemplation practice.", "The practice is sustainable and helps with attention or meaning."],
  "Reflection & Deep Journaling": ["Make a first entry about the current unresolved issue.", "Keep prompts and entries easy to find.", "Reflect regularly and revisit earlier insights.", "Journaling produces useful self-understanding and informs action."],
  "Worldview & Belief Systems": ["Name the belief or question currently creating friction.", "Capture core beliefs and open questions in plain language.", "Test beliefs against reading, experience, and conversation.", "A working worldview is coherent enough to guide choices and stay open to revision."],
  "Money, Admin & Infrastructure": ["Resolve the most urgent bill, document, or deadline.", "Inventory recurring financial and administrative obligations.", "Use a repeatable budget and admin review routine.", "Bills, records, and deadlines are current and easy to manage."],
  "Budgeting & Spending": ["Identify urgent overspending or unclear cash flow.", "List income, fixed costs, and current spending categories.", "Track spending against a realistic monthly plan.", "Spending fits the budget and is reviewed each month."],
  "Documents & Records": ["Find or replace a missing essential document.", "Collect IDs, contracts, certificates, and scans in known locations.", "File new records consistently and check completeness.", "Important documents are current, secure, and retrievable."],
  "Errands & General Life Admin": ["Handle the overdue errand with the largest consequence.", "Capture appointments, renewals, and maintenance tasks.", "Review and complete routine life admin each week.", "Recurring errands are handled before they become urgent."],
  "Income & Earning Power": ["Identify the income gap or immediate earning constraint.", "Map current income sources and realistic earning options.", "Take regular steps that improve earning capacity.", "Income sources and growth plans are understood and maintained."],
  "Saving, Investing & Wealth": ["Protect essential cash flow and savings first.", "Inventory accounts, balances, and goals.", "Save regularly according to a defined plan.", "Savings and investments align with current goals and are reviewed."],
  "Subscriptions, Contracts & Bills": ["Pay or resolve overdue essentials first.", "List recurring charges, contracts, and renewal dates.", "Review bills and cancel unused services.", "Bills are paid on time and contracts are understood."],
  "Taxes, Legal & Compliance": ["Identify any overdue filing or legal deadline.", "Collect required documents and upcoming obligations.", "Prepare records and file by the relevant dates.", "Filings and legal obligations are current with accessible records."],
  "People & Relationships": ["Reconnect where an important relationship needs attention.", "Map recurring commitments and desired contact with close people.", "Make time for conversations and follow through on plans.", "Important relationships receive steady attention and mutual care."],
  "Broader Social Circle & Acquaintances": ["Reconnect with one valued loose tie.", "Keep track of people and contexts where meeting again is natural.", "Attend social settings and follow up when appropriate.", "A wider social circle stays alive without forced outreach."],
  "Close Friends & Inner Circle": ["Reach out to a close friend who has gone quiet.", "Identify friendships needing more time or repair.", "Make recurring space for meaningful one-to-one contact.", "Close friendships feel mutual, dependable, and cared for."],
  "Creative & Work Collaborators": ["Clarify a stalled collaboration or expectation.", "List active collaborators, roles, and open commitments.", "Check in and deliver agreed contributions.", "Collaborations have clear roles, trust, and follow-through."],
  "Current Family Support & Roles": ["Address an unmet family duty or urgent request.", "Clarify current family needs, capacity, and boundaries.", "Provide agreed support and communicate changes early.", "Family support is reliable and sustainable for everyone involved."],
  "Family": ["Reconnect with a family member or resolve a strained practical matter.", "Map family bonds and current care responsibilities.", "Stay in touch and handle agreed responsibilities.", "Family bonds and obligations receive appropriate, sustainable care."],
  "Family Traditions & Rituals": ["Choose one family tradition worth restoring.", "List dates, people, and preparation each tradition needs.", "Prepare and participate in shared rituals.", "Family traditions happen with manageable effort and shared enjoyment."],
  "Rituals, Events & Traditions": ["Catch an upcoming birthday or shared event in time.", "Keep key dates and recurring gatherings in one calendar.", "Plan and participate in recurring social rituals.", "Important events are remembered and shared traditions are sustained."],
  "Romantic Life & Dating": ["Clarify what is needed in the current romantic situation.", "Identify intentions, boundaries, and communication gaps.", "Make time for dating or relationship check-ins that fit current goals.", "Romantic connections have honest communication and mutual respect."],
  "Social Skills & Communication": ["Notice a recurring conversation or conflict pattern.", "Identify situations and skills that need practice.", "Practice listening, feedback, and repair in real conversations.", "Communication is clear, respectful, and responsive to conflict."],
  "Reputation, Public Presence & Brand": ["Resolve an inaccurate or neglected public profile.", "Decide what work and identity should be visible publicly.", "Update profiles and share work deliberately.", "Public presence reflects current work without becoming a constant chore."],
  "Identity Narrative & Positioning": ["Draft a truthful description of current work.", "Identify the audiences and roles for a public introduction.", "Refine an about statement using real work and feedback.", "Public positioning is accurate, clear, and easy to reuse."],
  "Outreach & Visibility Routines": ["Follow up on a missed outreach commitment.", "List relevant contacts and sustainable outreach goals.", "Contact people or share work on a workable cadence.", "Visibility efforts are consistent, respectful, and purposeful."],
  "Professional Presence": ["Update one outdated profile or unfinished public piece.", "Gather current profiles, talks, and content ideas in one place.", "Publish or present selected work at a sustainable pace.", "Public work accurately shows current skills and is maintained."],
  "Testimonials, Social Proof & Press": ["Find existing references that may be lost or outdated.", "Collect recommendations, quotes, and mentions with permission.", "Request references when appropriate and keep evidence organized.", "Relevant proof of work is current and easy to share."],
  "Risk, Security & Resilience": ["Address the most immediate safety or financial exposure.", "List plausible risks and existing protections.", "Maintain backups, buffers, insurance, and emergency steps.", "Important risks have proportionate safeguards and workable recovery plans."],
  "Digital Security & Privacy": ["Secure a compromised or weak critical account.", "Review passwords, 2FA, and exposed devices.", "Improve account protection and review privacy settings.", "Critical accounts use strong protection and recovery is possible."],
  "Emergency Plans & Protocols": ["Make an immediate response plan for the most likely emergency.", "Keep contacts, documents, and basic supplies accessible.", "Review emergency steps and rehearse practical responses.", "Emergency information and essentials are ready when needed."],
  "Financial Buffers & Contingencies": ["Stop an immediate cash shortfall from worsening.", "Calculate essential expenses and current runway.", "Build or replenish an emergency buffer regularly.", "A realistic financial buffer is available and reviewed."],
  "Health & Insurance Safety Net": ["Resolve a missing or lapsed essential policy.", "Inventory coverage, exclusions, contacts, and renewal dates.", "Review insurance fit when circumstances change.", "Coverage and claim information are current and accessible."],
  "Health & Inner Life": ["Address the health or wellbeing issue with the greatest immediate impact.", "Identify core needs around sleep, movement, food, and mental health.", "Maintain practical routines and seek appropriate support.", "Core health needs are cared for and reviewed as life changes."],
  "Mental Resilience & Stress Tolerance": ["Identify a current stressor and a safe first response.", "List warning signs, supports, and coping strategies.", "Practice coping skills and protect recovery time.", "Stress is handled with workable supports and adequate recovery."],
  "Identity, Values & Archetypes": ["Name a value conflict affecting current behavior.", "Write down values and which identities feel useful.", "Use chosen principles to make concrete decisions.", "Self-description reflects lived choices and remains open to change."],
  "Mental Wellbeing": ["Identify a difficult pattern and a source of support.", "Track mood, triggers, and coping tools without overcomplicating it.", "Use helpful coping practices and follow through on support plans.", "Emotional needs are noticed early and support remains accessible."],
  "Nutrition & Eating": ["Restore regular access to adequate meals.", "Identify workable meals, shopping needs, and eating patterns.", "Eat regularly and use a simple food routine.", "Eating supports energy and health without constant planning stress."],
  "Physical Health": ["Address a neglected symptom, appointment, or physical limitation.", "Record current health needs and useful checkups.", "Follow a practical care and activity plan.", "Health checks and ongoing physical needs are handled consistently."],
  "Play, Fun & Personal Enjoyment": ["Make room for one low-pressure enjoyable activity.", "List activities that feel fun without productivity goals.", "Protect time for play and notice what restores energy.", "Enjoyment has a regular place in life without needing justification."],
  "Sleep & Recovery": ["Protect the next opportunity for adequate rest.", "Identify sleep disruptions and current recovery needs.", "Use a workable sleep schedule and wind-down routine.", "Rest supports daytime functioning most weeks."],
  "Time & Attention": ["Resolve the most disruptive scheduling or attention problem.", "Capture commitments and see where time is going.", "Use a workable weekly plan and protected focus periods.", "Time is allocated intentionally with space for rest and surprises."],
  "Attention Hygiene & Distraction Control": ["Remove the strongest active distraction from a focus block.", "Identify devices, feeds, and contexts that fragment attention.", "Use boundaries for notifications and distracting apps.", "Attention can be directed to chosen work without constant interruption."],
  "Calendar & Scheduling Architecture": ["Put an at-risk commitment on the calendar now.", "Collect recurring events and conflicting commitments.", "Review the calendar and schedule work with realistic buffers.", "The calendar is reliable and supports timely commitments."],
  "Deep Work System": ["Create one uninterrupted block for priority work.", "Identify when focus is strongest and what interrupts it.", "Protect regular deep-work blocks and prepare tasks beforehand.", "Important work gets sustained focus time each week."],
  "Execution & Momentum (Anti-Procrastination)": ["Start the stalled task with a small next step.", "Identify avoidance triggers and tasks lacking a clear start.", "Break work into next actions and begin them consistently.", "Important commitments move forward without repeated last-minute crises."],
  "Task Intake & Prioritization": ["Capture urgent loose tasks before they are forgotten.", "Use one trusted place for incoming tasks.", "Review tasks and choose priorities regularly.", "Next actions are current, findable, and aligned with commitments."],
  "Time Budgeting & Planning": ["Make room for the next non-negotiable commitment.", "Compare planned time with actual available time.", "Plan a realistic week and adjust after review.", "Time plans match capacity and leave room for recovery."],
  "Work, Career & Craft": ["Stabilize the most urgent work obligation.", "Clarify current role, skills, and career commitments.", "Deliver current work and develop useful craft skills.", "Work responsibilities are met and career direction is reviewed."],
  "Career Strategy & Long-Term Arc": ["Identify a career decision that can no longer wait.", "List plausible roles, constraints, and desired direction.", "Test career options through real work, conversations, or applications.", "Career direction is informed by evidence and updated when needed."],
  "Skills & Craft": ["Choose one core skill gap affecting current work.", "Define the practice needed to improve that skill.", "Practice deliberately and apply the skill in projects.", "Core craft skills meet current responsibilities and keep improving."],
  "Current Work": ["Clarify the most urgent current deliverable.", "List role expectations, deadlines, and open commitments.", "Deliver agreed work and check progress with stakeholders.", "Current responsibilities are met with clear priorities and feedback."],
  "Habits, Routines & Self-Regulation": ["Restore one routine that supports daily functioning.", "Identify routines that fail and the conditions around them.", "Use practical habit cues and adjust them based on experience.", "Routines support daily life without brittle rules."],
  "Job Search & Opportunities": ["Handle an imminent application or interview requirement.", "Track target roles, applications, and follow-ups.", "Apply deliberately and prepare for relevant interviews.", "The opportunity pipeline matches current career goals and capacity."],
  "Portfolio, Products & Case Studies": ["Choose one project that can be shown clearly.", "Inventory finished work, demos, and missing explanations.", "Document and publish selected work with outcomes.", "A current portfolio demonstrates real skills and results."],
  "Professional Network & Mentors": ["Reconnect with a valuable contact or mentor.", "List relationships and conversations worth sustaining.", "Follow up, offer value, and ask for feedback when useful.", "Professional relationships are reciprocal and maintained naturally."],
  "Workflows, Tools & Productivity": ["Fix a work tool or process that repeatedly blocks progress.", "Document recurring workflows and unnecessary steps.", "Use and refine templates, tools, or automation.", "Workflows reliably support delivery without excessive maintenance."],
  "Automation & Integration": ["Repair or disable an automation that is causing errors.", "List scripts, integrations, triggers, and owners.", "Maintain useful automation and check outputs.", "Integrations save work reliably and failures are easy to detect."],
  "Movement": ["Start with a manageable movement session.", "Identify suitable activities, barriers, and recovery needs.", "Move regularly in ways that fit energy and capacity.", "Movement is consistent, enjoyable enough to sustain, and supports health."],
};

const ORIGINAL_NAME_BY_ID: Record<string, string> = {
  "area-notion-92dccdd0a4e646e0bced732fbb28300d": "Adventure, Travel & Exploration",
  "area-notion-12ce0222aa014f7f803dc049ad6e7faf": "Cultural Sampling & Events",
  "area-notion-0ca446f16f06421890fc89e7a7374573": "Local Exploration & Micro-Adventures",
  "area-notion-1f4f4bdd5e7841318dd0c1b90671cee4": "Outdoor & Nature Activities",
  "area-notion-f03250c3b83c4e80b50d7e46380c610c": "Travel Gear & Logistics",
  "area-notion-cf8f894608a545928cbd33a87e98ffb4": "Trips & Itineraries",
  "area-notion-1b786fa7296a4709acb07c022222255d": "Art & Aesthetic Life",
  "area-notion-258c68d8f05240a5b41ecff17a10f560": "Art Communities & Scenes",
  "area-notion-dfedf8f0a9e743d7987f88a2a7acf444": "Craft & Making",
  "area-notion-8bfec7066629430ca2bdfdf7c8d0a584": "Digital Aesthetic",
  "area-notion-2f9bb2445a4f46f498780e37591355b5": "Music Making",
  "area-notion-56cf6e28c228445c8ad13b73fc11db19": "Performance & Live Arts",
  "area-notion-eadd4c3d0f7b46a1a7d7aa17d45a48c8": "Taste Development",
  "area-notion-9e1271cba9e04ad5b87657bb2876c7d4": "Visual Practice",
  "area-notion-0655ffedaa5446608bc61904fede85f5": "Writing & Prose",
  "area-notion-90559572cccd4de98f58f45dd4e8d8b8": "Community & Contribution",
  "area-notion-a59eaa94d9174976a6a7a22e21cdc72d": "Digital Systems",
  "area-notion-9b634b7163db418da8ea70e2eead6df1": "Accounts, Identity & Access",
  "area-notion-afa5d3d396f74dd79fdaa90139be7bf0": "Automation & Integrations",
  "area-notion-833e7a375f4c405886912a0a9a7ce39d": "Browsing & Information Hygiene",
  "area-notion-d5c28087484a4a3bbc7b356330dd5c87": "Cloud Services & Sync",
  "area-notion-5bc96ff2b005442397d6f80b4cc17b3d": "Communication Systems",
  "area-notion-564ecbdcbc7f47fc88d72a13ad481379": "Data Management & Backups",
  "area-notion-52df957adc93476f9373c3487458f488": "Devices & Operating Environments",
  "area-notion-98cef76858694d73a1b91028e1318043": "Digital Compliance & Records",
  "area-notion-aaea5e49a5d84ec3940b7dd9f3bc23a9": "Digital Finance Ops",
  "area-notion-498d1e22777e465c8b015ee1bf3c1a18": "Home Network & Connectivity",
  "area-notion-aab3eac6b19d449ab453b8e0553b9ba4": "Media, Entertainment & Subscriptions",
  "area-notion-9954aa8073324941a1b52f2e0cd62497": "Security & Privacy",
  "area-notion-b6c3882c484c444cb66b688824fbfc6a": "Work/Dev Environment",
  "area-notion-fe1162292ac641a2b62a4448f227d8fc": "Environment, Lifestyle & Identity in the World",
  "area-notion-2daeb127e60d43af97548660d9b851ac": "Daily Rhythms & Lifestyle Design",
  "area-notion-b2413b4f1e5148ccaad990f599a7d4ff": "Digital Environment & Devices",
  "area-notion-ceddce92f0ae4c4eb6b1d8dfe458dd1a": "Food & Home Operations",
  "area-notion-9e2411a72186440a8838cc6b716bbf54": "Home & Living",
  "area-notion-a458bc2d5c534b5dafd17ccfde5af90d": "Local Life & Neighbourhood",
  "area-notion-c5b31b74bb284056bc2198c18535681a": "Objects, Tools & Gear",
  "area-notion-2c54e837793780a2919df1f609c097ce": "Style & Personal Presentation",
  "area-notion-e08621e1dcfd4e35986fa551d5b32d0d": "Wardrobe & Personal Style",
  "area-notion-bc941df7b9d948dc8cccdd20652c2741": "Learning & Education",
  "area-notion-74fb0769a64f4a7a8e9adc2e0c89eddd": "Creative Output – Code & Tech",
  "area-notion-b26dae14318b4383a51ea0af533d4007": "Creative Output – Music & Audio",
  "area-notion-0ce3324d208e4390ba97b2740e41622f": "Creative Output – Writing",
  "area-notion-f031e9059740495e9358c6b89a4b6945": "Experiments & Labs",
  "area-notion-0565b82e9e6e4a1984132fc2e9f8e045": "Formal Education & Courses",
  "area-notion-f5b8193cd88b471f81d469709320b642": "Knowledge Management & Notes",
  "area-notion-167eaee12b48476b9870ca72d2d8cd07": "Self-Study & Skill Stacks",
  "area-notion-776b791761544239b9601c0e1c578ad1": "Meaning, Philosophy & Spirituality",
  "area-notion-55b309b0daa24382b5c259463e151ec0": "Life Philosophy & Ethics",
  "area-notion-b51c376048464fc6b422444d96e1965e": "Mortality & Long-Term Perspective",
  "area-notion-ec26ace808b34d48b2697507ae602676": "Practices, Rituals & Contemplation",
  "area-notion-d7af10d5a16a476e8452f1ea74176366": "Reflection & Deep Journaling",
  "area-notion-e36413dcc4de479eb65ed9efee6e0abf": "Worldview & Belief Systems",
  "area-notion-75a4b53b71d242c1916775f442a2d42a": "Money, Admin & Infrastructure",
  "area-notion-8b380e7e13324433b461ac0422e8c50b": "Budgeting & Spending",
  "area-notion-57ee9cc038184db18f27d4ef75e4f268": "Documents & Records",
  "area-notion-6758a1032ceb44ab9a3149b3b9f1a663": "Errands & General Life Admin",
  "area-notion-416778b1a06747a6ae3f8c97b30c3bfa": "Income & Earning Power",
  "area-notion-c80f8f1612874aa880863cdf2ca9f2b1": "Saving, Investing & Wealth",
  "area-notion-8fbe2fdabae240f7afca514a9f804a30": "Subscriptions, Contracts & Bills",
  "area-notion-4761789408d841d5bfa922235fcbce63": "Taxes, Legal & Compliance",
  "area-notion-8ab093175fcc4ad0b26663a6413c0a62": "People & Relationships",
  "area-notion-d95df0d988524abc8424eda0fae722be": "Broader Social Circle & Acquaintances",
  "area-notion-97450f3cab604c53b028ddc43dbfbdaf": "Close Friends & Inner Circle",
  "area-notion-902ca53b669147ed8cdc49aeaabd124b": "Creative & Work Collaborators",
  "area-notion-e73da29be2e3436cb1634d59f319b336": "Current Family Support & Roles",
  "area-notion-da2869170a944b15b2cbfcaf5971ddfe": "Family",
  "area-notion-fc981d512eec441fbfdb4fde685e6f0a": "Family Traditions & Rituals",
  "area-notion-7d36e7c712a64b1c8922aba86e24a902": "Rituals, Events & Traditions",
  "area-notion-6638ccbbd160406cbb5d22dfe0855b65": "Romantic Life & Dating",
  "area-notion-3c4bc873664444f1a1aaf59e1a728035": "Social Skills & Communication",
  "area-notion-c873d091529e44a5a0027508b198492c": "Reputation, Public Presence & Brand",
  "area-notion-a87dff007b5e45a9b7e51be97bc197e9": "Identity Narrative & Positioning",
  "area-notion-dfc2df16b49049b097fa6ea66af2b47e": "Outreach & Visibility Routines",
  "area-notion-0467b11caf114e4d9d29eddccfb6f28a": "Professional Presence",
  "area-notion-d4dcde8d98db45b4a5c415aaf7880aff": "Testimonials, Social Proof & Press",
  "area-notion-0c81f0de01214034a3a5a48065840968": "Risk, Security & Resilience",
  "area-notion-9e7a0afc4511422bae2af25c9818816a": "Digital Security & Privacy",
  "area-notion-d1235cf25be643639bff26c2df7cb442": "Emergency Plans & Protocols",
  "area-notion-9f77bff326d04be180b31a13bbda7f76": "Financial Buffers & Contingencies",
  "area-notion-cf54511c1172483aa0c683140ae4e0e2": "Health & Insurance Safety Net",
  "area-notion-12bceaa1e77746b48435051ac377d7ab": "Mental Resilience & Stress Tolerance",
  "area-notion-15b3d94850d34e53963dd04244a94dd7": "Health & Inner Life",
  "area-notion-5e09828987034215abc9e334e645970f": "Identity, Values & Archetypes",
  "area-notion-3c0b87982c0048289dfc6223d683b466": "Mental Wellbeing",
  "area-notion-f872e5e27b1840ce9bbe1950eee076d5": "Nutrition & Eating",
  "area-notion-ec90e537e8094068abe11267c7460374": "Physical Health",
  "area-notion-b98058d6053f49e3a68df1c395fac8ef": "Play, Fun & Personal Enjoyment",
  "area-notion-8ce46939d3d9490d90bf501daac4b3e8": "Sleep & Recovery",
  "area-notion-eac919a072f64b7c89c95f6d5ef0d0ef": "Time & Attention",
  "area-notion-b753ba97de2a4704864a7f2ff7b7d0af": "Attention Hygiene & Distraction Control",
  "area-notion-5fab8a7a21774510a562637037bf37b7": "Calendar & Scheduling Architecture",
  "area-notion-8ae04031303c48d3ac601260357278b8": "Deep Work System",
  "area-notion-20679bb4301441b9be0623577ab4701c": "Execution & Momentum (Anti-Procrastination)",
  "area-notion-b2a7b90088724a09ab5ce7b2651eb811": "Task Intake & Prioritization",
  "area-notion-115f6cec2d834c2ea96e3ae8dbdf4a20": "Time Budgeting & Planning",
  "area-notion-8e4143ea7afb4e748ea0fc29b0f7ddcc": "Work, Career & Craft",
  "area-notion-967f3329e6a14cbe904b3724cf0f8ecd": "Career Strategy & Long-Term Arc",
  "area-notion-463f0bdbb8c445b4b7435890421b40e5": "Skills & Craft",
  "area-notion-b64df7475cdf444a91f171e0b3b98d3a": "Current Work",
  "area-notion-72cc662571b645c09c6b93e77ade1583": "Habits, Routines & Self-Regulation",
  "area-notion-9e10eff8e8174247be7766e66e5fa5e8": "Job Search & Opportunities",
  "area-notion-29e8a63a6644472496dc5dce945db6f9": "Portfolio, Products & Case Studies",
  "area-notion-4e87600ef2bb47f3aec66b75f3237e04": "Professional Network & Mentors",
  "area-notion-6db58e10869f4507a02efb9c9229c2c2": "Workflows, Tools & Productivity",
  "area-notion-1b5a61c7c8e546f0853e6b9367a3c82b": "Automation & Integration",
  "area-984ad3aac84e": "Movement",
};

const HEALTH_INDEX: Record<AreaChecklistHealth, number> = { Rebuilding: 0, Messy: 1, Growing: 2, 'Under Control': 3 };

export function specificAreaName(area: ParaArea): string {
  return ORIGINAL_NAME_BY_ID[area.id] ?? area.name;
}

export function specificRequirement(area: ParaArea, health: AreaChecklistHealth): string {
  const criterion = AREA_CRITERIA[specificAreaName(area)]?.[HEALTH_INDEX[health]];
  if (criterion) return criterion;
  const subject = area.vision.trim().split(/[.\n]/)[0].trim() || area.name;
  switch (health) {
    case 'Rebuilding': return `Identify the main obstacle to ${subject.toLowerCase()} and schedule a recovery step.`;
    case 'Messy': return `Capture the unresolved commitments around ${subject.toLowerCase()}.`;
    case 'Growing': return `Follow a repeatable practice for ${subject.toLowerCase()} and record progress.`;
    case 'Under Control': return `Maintain ${subject.toLowerCase()} consistently and review it regularly.`;
  }
}

export function specificRequirements(area: ParaArea, health: AreaChecklistHealth): string[] {
  const standards = AREA_REQUIREMENT_DETAILS[specificAreaName(area)] ?? [
    `A clear definition of success for ${area.name} is recorded.`,
    `Recurring commitments in ${area.name} have a place in the calendar.`,
    `Resources needed for ${area.name} are available.`,
    `Open issues in ${area.name} have a next action.`,
  ];
  return [specificRequirement(area, health), ...standards.map((standard) => {
    const condition = standard[0].toLowerCase() + standard.slice(1);
    switch (health) {
      case 'Rebuilding': return `A recovery step is defined so ${condition}`;
      case 'Messy': return `Remaining gaps have next actions so ${condition}`;
      case 'Growing': return `Recent reviews show that ${condition}`;
      case 'Under Control': return standard;
    }
  })];
}
