// Separate standards for the practical dimensions of each imported area.
export const AREA_REQUIREMENT_DETAILS: Record<string, readonly string[]> = {
  "Adventure, Travel & Exploration": [
    "A shortlist separates near-term outings from someday trips.",
    "Trip costs fit the available leisure budget.",
    "Time for travel fits work and other commitments.",
    "Booking and packing information is easy to retrieve.",
  ],
  "Cultural Sampling & Events": [
    "The event list includes dates, locations, and ticket costs.",
    "Selected events reflect current cultural interests.",
    "Tickets and transport are arranged before attendance.",
    "Notes capture which venues and scenes are worth revisiting.",
  ],
  "Local Exploration & Micro-Adventures": [
    "Nearby destinations include realistic journey times.",
    "Short outings can fit into a free afternoon.",
    "Routes and opening hours are checked before leaving.",
    "Favourite local routes are easy to reuse.",
  ],
  "Outdoor & Nature Activities": [
    "Routes match current ability and available daylight.",
    "Clothing and equipment suit expected weather.",
    "Transport and return plans are workable.",
    "Outdoor outings leave enough time for rest afterwards.",
  ],
  "Travel Gear & Logistics": [
    "Required travel documents are valid for planned trips.",
    "Packing lists distinguish essentials from optional gear.",
    "Luggage and essential equipment are usable.",
    "Booking confirmations and emergency contacts are accessible during travel.",
  ],
  "Trips & Itineraries": [
    "Confirmed reservations and travel dates agree.",
    "Transport connections leave realistic transfer time.",
    "Daily plans include meals, rest, and spare time.",
    "Cancellation terms and booking references are accessible.",
  ],
  "Art & Aesthetic Life": [
    "Time is available for a chosen creative practice.",
    "Materials and tools are ready when needed.",
    "Cultural outings fit the leisure budget.",
    "Finished work and meaningful discoveries are kept somewhere retrievable.",
  ],
  "Art Communities & Scenes": [
    "Relevant gatherings have known dates and locations.",
    "There are people in the scene worth reconnecting with.",
    "Invitations and collaboration commitments receive responses.",
    "Participation fits available social energy and time.",
  ],
  "Craft & Making": [
    "A current project has a manageable scope.",
    "Essential materials and tools are available.",
    "The workspace can be set up and cleared without major effort.",
    "Completed pieces and useful process notes are kept.",
  ],
  "Digital Aesthetic": [
    "Text remains readable across daily applications.",
    "Themes and shortcuts stay consistent across frequently used tools.",
    "Essential accessibility settings survive updates.",
    "Preferred configurations can be restored after a reset.",
  ],
  "Music Making": [
    "Instruments or production tools are ready to use.",
    "Practice sessions have a clear musical focus.",
    "Recordings and project files are saved reliably.",
    "There is time to finish or review a piece of music.",
  ],
  "Performance & Live Arts": [
    "A shortlist includes relevant venues and performances.",
    "Attendance or rehearsal commitments are on the calendar.",
    "Tickets, preparation, and transport fit the available budget.",
    "Feedback or reflections inform the next performance choice.",
  ],
  "Taste Development": [
    "Saved examples include an explanation of what resonates.",
    "Examples represent more than one familiar creator or medium.",
    "Personal preferences can be distinguished from passing trends.",
    "Past favourites are revisited to notice changes in taste.",
  ],
  "Visual Practice": [
    "Materials or camera equipment are ready for the next session.",
    "Practice exercises target a chosen visual skill.",
    "Dated work makes improvement visible.",
    "Selected work receives reflection or constructive feedback.",
  ],
  "Writing & Prose": [
    "A current draft or prompt is easy to find.",
    "Writing time fits the weekly schedule.",
    "Drafts are backed up and versions remain identifiable.",
    "Finished drafts receive a separate revision pass.",
  ],
  "Community & Contribution": [
    "Current commitments have clear expectations and boundaries.",
    "Promised contributions are delivered or renegotiated early.",
    "Participation fits available time, money, and energy.",
    "Feedback shows whether the contribution is useful to others.",
  ],
  "Digital Systems": [
    "Critical accounts have usable recovery methods.",
    "Important files have a working backup.",
    "Essential devices receive maintenance and updates.",
    "Recurring failures and manual workarounds are tracked.",
  ],
  "Accounts, Identity & Access": [
    "Critical accounts are listed in a secure inventory.",
    "Recovery email addresses and phone numbers are current.",
    "Recovery codes are stored securely outside the device they protect.",
    "Unused accounts and unnecessary access are reviewed.",
  ],
  "Automation & Integrations": [
    "Each active automation has a clear purpose and trigger.",
    "Required credentials and dependencies are maintained.",
    "Failed runs are visible through logs or alerts.",
    "A manual fallback exists for important automated work.",
  ],
  "Browsing & Information Hygiene": [
    "Notifications are limited to channels that need attention.",
    "Saved pages have a retrieval or reading workflow.",
    "Feeds and subscriptions are reviewed for actual value.",
    "Focus periods have boundaries around distracting websites.",
  ],
  "Cloud Services & Sync": [
    "Each important collection has a designated source of truth.",
    "Sync errors are noticed and resolved.",
    "Sharing permissions match intended recipients.",
    "Important cloud files have a recovery route beyond ordinary sync.",
  ],
  "Communication Systems": [
    "Important channels have clear response expectations.",
    "Urgent messages have a reliable route.",
    "Notifications support work and rest boundaries.",
    "Unanswered commitments can be found during a review.",
  ],
  "Data Management & Backups": [
    "Critical data is included in the backup scope.",
    "Backup jobs finish successfully and failures are noticed.",
    "A sample restore has been verified.",
    "Recovery copies are protected from loss of the primary device.",
  ],
  "Devices & Operating Environments": [
    "Essential devices receive supported software updates.",
    "Storage and battery issues are identified before they block use.",
    "Important configuration choices are documented.",
    "A replacement or reset can restore essential applications and files.",
  ],
  "Digital Compliance & Records": [
    "Records have names and folders that support retrieval.",
    "New scans are readable and complete.",
    "Access is restricted for sensitive documents.",
    "Retention and deletion decisions are recorded where needed.",
  ],
  "Digital Finance Ops": [
    "Financial account access and recovery details are current.",
    "Payment failures and unfamiliar transactions receive attention.",
    "Statements can be retrieved for reconciliation.",
    "Payment methods and linked apps are reviewed when no longer used.",
  ],
  "Home Network & Connectivity": [
    "Wi-Fi coverage supports the places where it is needed.",
    "Router access and network credentials are protected.",
    "Network equipment receives maintenance and updates.",
    "A workable alternative exists for important connectivity outages.",
  ],
  "Media, Entertainment & Subscriptions": [
    "Active services and renewal costs are listed.",
    "Unused trials are cancelled before unwanted renewal.",
    "Media choices fit available leisure time.",
    "Saved media can be found without accumulating an unmanageable backlog.",
  ],
  "Security & Privacy": [
    "Critical accounts use distinct passwords and available strong authentication.",
    "Devices lock automatically and receive security updates.",
    "Sensitive files and recovery material have restricted access.",
    "App permissions and public sharing settings are reviewed.",
  ],
  "Work/Dev Environment": [
    "A documented setup can recreate essential development tools.",
    "Dependencies and configuration are tracked with projects.",
    "Secrets are kept out of source files and shared logs.",
    "A basic build or development task works after setup changes.",
  ],
  "Environment, Lifestyle & Identity in the World": [
    "Home spaces support their intended daily activities.",
    "Essential household supplies are replenished in time.",
    "Daily routines include realistic transition and rest time.",
    "Clothing and surroundings fit current practical needs.",
  ],
  "Daily Rhythms & Lifestyle Design": [
    "A typical weekday has a workable sequence of commitments.",
    "Meals and rest fit into the daily plan.",
    "Transition time prevents routines from depending on perfect timing.",
    "A simpler routine is available for low-energy or disrupted days.",
  ],
  "Digital Environment & Devices": [
    "Daily applications and files are easy to access.",
    "Device settings support comfortable and accessible use.",
    "Unnecessary apps and recurring setup friction are addressed.",
    "Preferred settings can be recovered after changes.",
  ],
  "Food & Home Operations": [
    "Groceries support a small set of practical meals.",
    "Food storage and basic kitchen cleanup are handled.",
    "Cleaning tasks have a workable rotation.",
    "Household supplies are replaced before they run out.",
  ],
  "Home & Living": [
    "Frequently used surfaces and routes remain usable.",
    "Belongings have accessible storage locations.",
    "Lighting, seating, and room layout fit daily activities.",
    "Repairs and household maintenance have next actions.",
  ],
  "Local Life & Neighbourhood": [
    "Essential shops and services have known locations and opening hours.",
    "Routine errands have practical routes.",
    "Useful local contacts and service information are retrievable.",
    "There are nearby places for rest, social time, or recreation.",
  ],
  "Objects, Tools & Gear": [
    "Frequently used tools have known storage locations.",
    "Essential gear is clean and functional.",
    "Borrowed or shared items can be accounted for.",
    "Purchases address a real gap instead of duplicating unused gear.",
  ],
  "Style & Personal Presentation": [
    "A few reliable outfits suit recurring daily situations.",
    "Grooming supplies and routines are manageable.",
    "Clothing is clean, comfortable, and in usable condition.",
    "Presentation choices reflect personal preferences and practical needs.",
  ],
  "Wardrobe & Personal Style": [
    "Current clothing fits comfortably and suits the season.",
    "Outfit combinations cover recurring occasions.",
    "Laundry and repairs keep useful clothes available.",
    "Shopping priorities reflect specific wardrobe gaps.",
  ],
  "Learning & Education": [
    "Active learning commitments fit available study time.",
    "Coursework and practice deadlines are visible.",
    "Notes and exercises can be retrieved when applying a skill.",
    "Completed learning produces an example, assessment, or demonstrated ability.",
  ],
  "Creative Output – Code & Tech": [
    "An active build has a small, clear intended use.",
    "Code and project instructions are saved in version control.",
    "A working example demonstrates the current result.",
    "Known defects and maintenance needs have a next action.",
  ],
  "Creative Output – Music & Audio": [
    "Sessions and audio assets are organised and backed up.",
    "A piece has a clear next production or practice step.",
    "Work is reviewed through listening rather than only editing.",
    "Finished exports can be found and shared when intended.",
  ],
  "Creative Output – Writing": [
    "Each active piece has an intended audience and purpose.",
    "Drafts and source notes are organised.",
    "Editing includes structure and clarity as well as wording.",
    "Publication commitments fit a sustainable writing pace.",
  ],
  "Experiments & Labs": [
    "Each active experiment has a question that can be answered.",
    "Time and resource limits are set before starting.",
    "Observations and results are recorded.",
    "A finished experiment leads to a decision or a documented lesson.",
  ],
  "Formal Education & Courses": [
    "Enrollment, access, and required materials are in order.",
    "Assignment and assessment deadlines are recorded.",
    "Study sessions cover current coursework and practice.",
    "Grades, feedback, or certificates are saved for reference.",
  ],
  "Knowledge Management & Notes": [
    "New notes have a reliable capture location.",
    "Useful notes have titles and links that aid retrieval.",
    "Source references stay attached to claims or excerpts.",
    "Outdated or duplicate notes are reviewed when they cause confusion.",
  ],
  "Self-Study & Skill Stacks": [
    "A current skill goal includes a way to demonstrate ability.",
    "Resources support the chosen goal instead of an endless curriculum.",
    "Practice includes application without following every step of a tutorial.",
    "Progress reviews inform what to study next.",
  ],
  "Meaning, Philosophy & Spirituality": [
    "Important values and open questions are recorded in plain language.",
    "A reflective practice fits current life.",
    "Real decisions provide opportunities to test personal principles.",
    "Uncertainty can be acknowledged without forcing a fixed answer.",
  ],
  "Life Philosophy & Ethics": [
    "Core principles are stated clearly enough to use.",
    "A recent difficult decision can be explained in terms of those principles.",
    "Conflicting values are acknowledged rather than hidden.",
    "Principles are revised when experience exposes a problem.",
  ],
  "Mortality & Long-Term Perspective": [
    "Long-term priorities can be connected to present choices.",
    "Avoided questions can be recorded without requiring immediate resolution.",
    "Time is reserved for people and experiences that matter.",
    "Reflection on the future leaves room for ordinary daily life.",
  ],
  "Practices, Rituals & Contemplation": [
    "A chosen practice has a simple, repeatable form.",
    "A workable time and place support the practice.",
    "Shorter alternatives allow continuity on difficult days.",
    "Reflection shows whether the practice is helpful.",
  ],
  "Reflection & Deep Journaling": [
    "Entries and prompts are kept in a consistent place.",
    "Reflection includes concrete experiences rather than only abstract ideas.",
    "Useful insights lead to decisions or experiments.",
    "Earlier entries are revisited to notice recurring patterns.",
  ],
  "Worldview & Belief Systems": [
    "Core beliefs are distinguished from open questions.",
    "Sources and experiences behind important beliefs can be identified.",
    "Contrary evidence receives a fair hearing.",
    "Beliefs can change without requiring an entirely new identity.",
  ],
  "Money, Admin & Infrastructure": [
    "Upcoming bills and administrative deadlines are visible.",
    "Essential records can be found when needed.",
    "Spending and available cash are understood.",
    "A recurring review catches renewals and unresolved admin.",
  ],
  "Budgeting & Spending": [
    "Income and fixed costs are recorded for the current budget period.",
    "Recent spending is assigned to usable categories.",
    "Variable spending limits reflect actual available money.",
    "Budget differences lead to an adjustment rather than being ignored.",
  ],
  "Documents & Records": [
    "Essential IDs and certificates are current or have renewal plans.",
    "Originals and digital copies have known locations.",
    "Sensitive documents are stored with appropriate access restrictions.",
    "New documents are filed before they become hard to find.",
  ],
  "Errands & General Life Admin": [
    "Appointments and renewals are captured in one trusted place.",
    "Tasks with deadlines are distinguished from optional errands.",
    "Required documents or supplies are prepared before appointments.",
    "Completed errands and outstanding follow-ups are reviewed.",
  ],
  "Income & Earning Power": [
    "Current income sources and payment timing are understood.",
    "Work owed and payments received can be reconciled.",
    "Skills or opportunities relevant to earning goals have next steps.",
    "Changes in income are reflected in the spending plan.",
  ],
  "Saving, Investing & Wealth": [
    "Savings goals have an intended use and time horizon.",
    "Accounts and balances are recorded in a retrievable overview.",
    "Contributions fit current cash flow and commitments.",
    "The plan is reviewed when goals or circumstances change.",
  ],
  "Subscriptions, Contracts & Bills": [
    "Recurring charges and due dates are listed.",
    "Renewal and cancellation terms are accessible.",
    "Payment methods and billing details are current.",
    "Unused or unsuitable contracts have a cancellation or review action.",
  ],
  "Taxes, Legal & Compliance": [
    "Relevant filing dates and obligations are recorded.",
    "Supporting documents are organised by reporting period.",
    "Submitted forms and confirmations are saved.",
    "Questions or missing information have a route to resolution.",
  ],
  "People & Relationships": [
    "Important relationships receive time that fits both people.",
    "Promised help and shared plans are followed through.",
    "Boundaries and changes in availability are communicated.",
    "Tension or missed contact can be addressed through conversation.",
  ],
  "Broader Social Circle & Acquaintances": [
    "Names and shared contexts are remembered or noted appropriately.",
    "Invitations and messages receive considerate responses.",
    "Follow-ups happen after enjoyable meetings.",
    "Social commitments fit available time and energy.",
  ],
  "Close Friends & Inner Circle": [
    "Contact happens often enough for both people to feel connected.",
    "There is room for meaningful conversation as well as activities.",
    "Important events and difficulties in friends' lives receive attention.",
    "Disagreements and imbalances can be discussed respectfully.",
  ],
  "Creative & Work Collaborators": [
    "Roles and expected contributions are clear.",
    "Shared deadlines and next steps are visible.",
    "Files and decisions needed for collaboration are accessible.",
    "Changes in scope or availability are communicated early.",
  ],
  "Current Family Support & Roles": [
    "Agreed family responsibilities are explicit.",
    "Requests are considered against current capacity.",
    "Care or support arrangements have practical follow-up steps.",
    "Boundaries can be communicated without promising more than is sustainable.",
  ],
  "Family": [
    "Contact reflects the relationships that matter now.",
    "Important family news and dates are acknowledged.",
    "Agreed practical responsibilities are followed through.",
    "Personal boundaries and differences receive respectful communication.",
  ],
  "Family Traditions & Rituals": [
    "Chosen traditions have dates or occasions attached.",
    "Preparation is shared or assigned realistically.",
    "Costs and expectations fit participants' circumstances.",
    "Traditions can be adapted when they stop working for the family.",
  ],
  "Rituals, Events & Traditions": [
    "Important birthdays and recurring events are recorded.",
    "Invitations and preparation happen with reasonable notice.",
    "Hosting or participation costs fit the budget.",
    "Shared rituals remain enjoyable rather than compulsory.",
  ],
  "Romantic Life & Dating": [
    "Intentions and expectations can be discussed honestly.",
    "Boundaries and consent are respected.",
    "Plans and communication fit each person's availability.",
    "Connection leaves room for autonomy and other important relationships.",
  ],
  "Social Skills & Communication": [
    "Conversations leave space to listen and ask clarifying questions.",
    "Needs and boundaries can be expressed directly.",
    "Feedback can be received without immediate defensiveness.",
    "Misunderstandings receive an attempt at repair.",
  ],
  "Reputation, Public Presence & Brand": [
    "Public profiles accurately describe current work.",
    "Claims about skills or results have supporting examples.",
    "Published material is appropriate for its intended audience.",
    "Public contact routes and important links still work.",
  ],
  "Identity Narrative & Positioning": [
    "An introduction explains current work in understandable terms.",
    "Descriptions fit the audience without misrepresenting experience.",
    "Examples support the skills or interests being presented.",
    "Old descriptions are updated when direction changes.",
  ],
  "Outreach & Visibility Routines": [
    "Outreach has a clear reason relevant to the recipient.",
    "Contacts and promised follow-ups are recorded.",
    "Messages respect boundaries and avoid repeated unwanted follow-ups.",
    "Results inform which channels deserve continued effort.",
  ],
  "Professional Presence": [
    "Core profiles contain current roles and contact information.",
    "Selected work samples or articles remain accessible.",
    "Talks and publication commitments have preparation time.",
    "Public claims are accurate and supported by the work shown.",
  ],
  "Testimonials, Social Proof & Press": [
    "Recommendations and mentions are saved with their source.",
    "Permission and intended use are clear for private quotes.",
    "References are relevant to the work being presented.",
    "Outdated or unsupported claims are removed from public materials.",
  ],
  "Risk, Security & Resilience": [
    "The most consequential plausible risks have been considered.",
    "Key documents and emergency contacts are accessible.",
    "Backup and recovery arrangements can actually be used.",
    "Safeguards are reviewed after major changes in circumstances.",
  ],
  "Digital Security & Privacy": [
    "Critical accounts have distinct credentials and strong authentication where available.",
    "Recovery methods are current and stored securely.",
    "Devices and important applications receive updates.",
    "Access permissions and public exposure are reviewed periodically.",
  ],
  "Emergency Plans & Protocols": [
    "Emergency contacts and essential information are easy to reach.",
    "Basic household response steps are understood.",
    "Needed supplies and equipment are accessible and usable.",
    "Plans account for who needs help and how to contact them.",
  ],
  "Financial Buffers & Contingencies": [
    "Essential recurring expenses are understood.",
    "Available contingency funds can be accessed when needed.",
    "Use of the buffer has clear boundaries.",
    "A depleted buffer has a realistic replenishment plan.",
  ],
  "Health & Insurance Safety Net": [
    "Current coverage and renewal dates are recorded.",
    "Policy documents and contact details are retrievable.",
    "Important exclusions or limits have been checked.",
    "Claims or unresolved coverage questions have follow-up actions.",
  ],
  "Health & Inner Life": [
    "Regular meals, movement, and rest fit the weekly routine.",
    "Physical or emotional concerns have an appropriate follow-up path.",
    "Support and recovery remain available during demanding periods.",
    "Health routines can be adjusted without becoming all-or-nothing rules.",
  ],
  "Mental Resilience & Stress Tolerance": [
    "Personal signs of overload are recognisable.",
    "Helpful coping practices are available before stress peaks.",
    "Support contacts and boundaries are clear.",
    "Demanding periods are followed by sufficient recovery time.",
  ],
  "Identity, Values & Archetypes": [
    "Personal values are stated in practical language.",
    "Recent choices can be related to those values.",
    "Useful identity ideas support action rather than rigid labels.",
    "Contradictions between beliefs and behaviour receive reflection.",
  ],
  "Mental Wellbeing": [
    "Changes in mood and functioning can be noticed.",
    "Helpful coping tools are accessible when needed.",
    "Support plans and appointments are followed through when applicable.",
    "Daily demands leave room for rest and emotional processing.",
  ],
  "Nutrition & Eating": [
    "Meals are regular enough to support daily functioning.",
    "Available food includes a practical variety suited to personal needs.",
    "Shopping and preparation fit time and resources.",
    "Eating routines remain flexible around changes in schedule.",
  ],
  "Physical Health": [
    "Current symptoms and physical limitations receive appropriate attention.",
    "Agreed care plans and follow-up appointments are tracked.",
    "Relevant health information is available when needed.",
    "Daily activity and recovery fit current physical capacity.",
  ],
  "Play, Fun & Personal Enjoyment": [
    "There are accessible activities chosen purely for enjoyment.",
    "Leisure time is protected from being consumed by every new task.",
    "Play does not depend on expensive preparation or perfect conditions.",
    "Activities can change when they stop feeling enjoyable.",
  ],
  "Sleep & Recovery": [
    "Bed and wake times fit current commitments and rest needs.",
    "The sleeping space supports comfort and reduced disturbance.",
    "An evening wind-down makes it easier to stop demanding activity.",
    "Demanding days include realistic opportunities for recovery.",
  ],
  "Time & Attention": [
    "Current commitments fit the actual time available.",
    "Important work has protected attention time.",
    "Rest and transitions are included in planning.",
    "Unexpected tasks lead to explicit reprioritisation.",
  ],
  "Attention Hygiene & Distraction Control": [
    "Notifications are configured around actual response needs.",
    "Distracting sites or devices have practical boundaries during focus time.",
    "Needed materials are ready before starting a focus block.",
    "Interruptions can be captured without abandoning the current task.",
  ],
  "Calendar & Scheduling Architecture": [
    "Confirmed commitments are recorded in a trusted calendar.",
    "Travel and preparation time are accounted for.",
    "Calendar conflicts are resolved before the day arrives.",
    "Changes and cancellations are reflected promptly.",
  ],
  "Deep Work System": [
    "Focus blocks have a specific intended outcome.",
    "Materials and access are ready before the block.",
    "Interruptions have a clear handling rule.",
    "Completed focus time is reviewed against the work that mattered.",
  ],
  "Execution & Momentum (Anti-Procrastination)": [
    "Stalled tasks have a small and concrete starting action.",
    "Task size fits available attention and energy.",
    "Avoidance triggers have a practical response.",
    "Unfinished commitments are resumed or renegotiated explicitly.",
  ],
  "Task Intake & Prioritization": [
    "Incoming tasks have a reliable capture place.",
    "Urgent deadlines are visible among ordinary tasks.",
    "Current priorities have clear next actions.",
    "Completed, stale, and duplicate tasks are cleared during review.",
  ],
  "Time Budgeting & Planning": [
    "Plans use realistic estimates rather than ideal days.",
    "High-priority commitments receive time before optional work.",
    "Buffers account for transitions and unexpected work.",
    "Actual time use informs the next planning cycle.",
  ],
  "Work, Career & Craft": [
    "Current work expectations and deadlines are clear.",
    "Useful craft practice fits alongside delivery commitments.",
    "Career options are informed by real work and feedback.",
    "Workload remains compatible with recovery and other obligations.",
  ],
  "Career Strategy & Long-Term Arc": [
    "Desired roles are connected to concrete skills and constraints.",
    "Career assumptions are tested through conversations or experience.",
    "Near-term steps support the current direction.",
    "The plan is revisited when new evidence or priorities emerge.",
  ],
  "Skills & Craft": [
    "A specific skill gap has been chosen for deliberate practice.",
    "Practice includes feedback or a way to assess the result.",
    "The skill is applied to work beyond isolated exercises.",
    "Examples demonstrate how capability has improved.",
  ],
  "Current Work": [
    "Deliverables and priorities are agreed with relevant people.",
    "Deadlines and dependencies are visible.",
    "Risks and blockers are communicated before they become surprises.",
    "Completed work receives review and necessary follow-up.",
  ],
  "Habits, Routines & Self-Regulation": [
    "Important habits have practical cues and an easy starting step.",
    "Routines fit current energy and constraints.",
    "A reduced version supports difficult or disrupted days.",
    "Reviews focus on adjusting conditions rather than blaming missed days.",
  ],
  "Job Search & Opportunities": [
    "Target roles match current direction and constraints.",
    "Application materials are accurate and current.",
    "Applications, responses, and follow-ups are tracked.",
    "Interview preparation uses the actual role and organisation.",
  ],
  "Portfolio, Products & Case Studies": [
    "Selected examples are accessible and work as described.",
    "Each example explains the problem, contribution, and result.",
    "Claims distinguish personal work from team contributions.",
    "Old links, demos, and descriptions receive maintenance.",
  ],
  "Professional Network & Mentors": [
    "Valued contacts and shared context can be recalled.",
    "Promised introductions and follow-ups are completed.",
    "Mentoring conversations have useful questions or context.",
    "Relationships include reciprocal help and respect for time.",
  ],
  "Workflows, Tools & Productivity": [
    "Recurring workflows have clear steps or usable templates.",
    "Frequently encountered friction has a tracked improvement action.",
    "Tools have a clear purpose in the work being delivered.",
    "Process changes are kept only when they improve actual use.",
  ],
  "Automation & Integration": [
    "Important scripts have documented triggers and dependencies.",
    "Secrets and permissions are limited to what integrations need.",
    "Failures are visible and have a practical response.",
    "A manual fallback is available for critical workflows.",
  ],
  "Movement": [
    "Chosen activities fit current ability and practical constraints.",
    "Movement sessions have realistic space in the week.",
    "Needed equipment or access is available when planned.",
    "Activity is adjusted when discomfort, fatigue, or recovery needs change.",
  ],
};
