// Audit report generator (#359) — pure builders. A report compiles an
// engagement's notes and findings into markdown (stored as a note, so it can
// be anchored via the existing on-chain flow) and into standalone HTML for the
// print/PDF export path.

import type { CoreNote } from '@modulo/core';
import { extractFindings, SEVERITIES, severityRank, type NoteFinding } from './findings';
import { ENGAGEMENT_TAG_PREFIX } from './pipeline';

export interface ReportInput {
  /** Bare engagement name (without the `engagement/` prefix). */
  engagement: string;
  /** All vault notes; the builder selects the engagement's slice itself. */
  notes: CoreNote[];
  /** Report date, injected for testability. */
  date: Date;
}

export interface BuiltReport {
  title: string;
  markdown: string;
  findings: NoteFinding[];
  countsLine: string;
}

/** Every distinct engagement tag in the vault, bare names, sorted. */
export function engagementsIn(notes: CoreNote[]): string[] {
  const set = new Set<string>();
  for (const n of notes) {
    for (const t of n.tags) {
      if (t.name.startsWith(ENGAGEMENT_TAG_PREFIX)) set.add(t.name.slice(ENGAGEMENT_TAG_PREFIX.length));
    }
  }
  return [...set].sort();
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export function buildReport({ engagement, notes, date }: ReportInput): BuiltReport {
  const tag = `${ENGAGEMENT_TAG_PREFIX}${engagement}`;
  const scopeNotes = notes.filter((n) => n.tags.some((t) => t.name === tag));
  const findings = extractFindings(scopeNotes)
    .filter((f) => f.engagements.includes(tag))
    .sort((a, b) => severityRank(a.finding.severity) - severityRank(b.finding.severity));

  const counts = SEVERITIES.map((s) => [s, findings.filter((f) => f.finding.severity === s).length] as const).filter(
    ([, n]) => n > 0,
  );
  const countsLine = counts.length === 0 ? 'No findings.' : counts.map(([s, n]) => `${n} ${s}`).join(', ');

  const lines: string[] = [];
  const title = `Audit report — ${engagement} (${isoDate(date)})`;
  lines.push(`# ${title}`, '');
  lines.push('## Summary', '');
  lines.push(`Findings: ${countsLine}`, '');
  lines.push(
    `Status: ${findings.length === 0 ? '—' : `${findings.filter((f) => f.finding.status === 'verified').length}/${findings.length} verified fixed`}`,
    '',
  );

  lines.push('## Findings', '');
  if (findings.length === 0) {
    lines.push('_No findings were recorded for this engagement._', '');
  }
  for (const severity of SEVERITIES) {
    const group = findings.filter((f) => f.finding.severity === severity);
    if (group.length === 0) continue;
    lines.push(`### ${severity.charAt(0).toUpperCase()}${severity.slice(1)}`, '');
    for (const f of group) {
      const heading = f.finding.id ? `${f.finding.id} — ${f.finding.title}` : f.finding.title;
      lines.push(`#### ${heading}`, '');
      const meta = [
        `severity: ${f.finding.severity}`,
        `status: ${f.finding.status}`,
        f.finding.contract && `contract: ${f.finding.contract}`,
        f.finding.location && `location: ${f.finding.location}`,
        f.finding.vulnClass && `class: ${f.finding.vulnClass}`,
      ]
        .filter(Boolean)
        .join(' · ');
      lines.push(`_${meta}_`, '');
      if (f.finding.body) lines.push(f.finding.body, '');
      if (f.finding.response) lines.push(`**Client response:** ${f.finding.response}`, '');
    }
  }

  lines.push('## Scope', '');
  if (scopeNotes.length === 0) {
    lines.push(`_No notes are tagged \`${tag}\`._`, '');
  } else {
    for (const n of scopeNotes) lines.push(`- ${n.title}`);
    lines.push('');
  }

  return { title, markdown: lines.join('\n'), findings, countsLine };
}

// ── Print/PDF export ─────────────────────────────────────────────────────────
// The report markdown is generated by us, so a small renderer over its known
// shapes (headings, lists, emphasis, bold) is enough for a clean print page.

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function inline(s: string): string {
  return escapeHtml(s)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/_([^_]+)_/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>');
}

export function reportHtml(markdown: string): string {
  const out: string[] = [];
  let inList = false;
  const closeList = () => {
    if (inList) {
      out.push('</ul>');
      inList = false;
    }
  };
  for (const raw of markdown.split('\n')) {
    const line = raw.trimEnd();
    const h = /^(#{1,4})\s+(.*)$/.exec(line);
    if (h) {
      closeList();
      const level = h[1].length;
      out.push(`<h${level}>${inline(h[2])}</h${level}>`);
      continue;
    }
    if (/^\s*-\s+/.test(line)) {
      if (!inList) {
        out.push('<ul>');
        inList = true;
      }
      out.push(`<li>${inline(line.replace(/^\s*-\s+/, ''))}</li>`);
      continue;
    }
    closeList();
    if (line.trim() === '') continue;
    out.push(`<p>${inline(line)}</p>`);
  }
  closeList();
  return out.join('\n');
}

/** Full standalone document for the print window. */
export function reportDocument(markdown: string, title: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  body { font: 13px/1.55 -apple-system, 'Segoe UI', Roboto, sans-serif; color: #111; max-width: 46rem; margin: 2rem auto; padding: 0 1rem; }
  h1 { font-size: 1.5rem; border-bottom: 2px solid #111; padding-bottom: .4rem; }
  h2 { font-size: 1.15rem; margin-top: 1.6rem; border-bottom: 1px solid #ccc; padding-bottom: .2rem; }
  h3 { font-size: 1rem; margin-top: 1.2rem; text-transform: uppercase; letter-spacing: .04em; }
  h4 { font-size: .95rem; margin: 1rem 0 .3rem; }
  code { font-family: ui-monospace, monospace; background: #f3f3f3; padding: 0 .25em; border-radius: 3px; }
  em { color: #555; }
  @media print { body { margin: 0 auto; } }
</style></head><body>${reportHtml(markdown)}</body></html>`;
}
