import { useState } from 'react';
import { Check, Plus, Trash2 } from 'lucide-react';
import { Button, Input, Textarea } from '@/ui';
import { DAY_BLOCKS } from './dayBlocks';
import { HOBBY_ENERGIES, HOBBY_SESSION_STATUSES, newHobbyId, type HobbyArtifact, type HobbySession } from './hobbies';
import { isoDay } from './para';
import { useHobbyStore } from './useHobbyStore';
import { PopoverEditor } from './EntryPopover';
import { Choice, Field } from './viewkit';

const blankSession = (): HobbySession => ({ id: newHobbyId('session'), date: isoDay(), durationMinutes: 60, status: 'Planned', people: [], notes: '' });
const blankArtifact = (): HobbyArtifact => ({ id: newHobbyId('artifact'), hobbyId: '', title: '', type: '', date: isoDay(), notes: '' });

export function HobbyPracticeView() {
  const [data, setData] = useHobbyStore();
  const [session, setSession] = useState(blankSession);
  const [artifact, setArtifact] = useState(blankArtifact);
  const addSession = () => { if (!session.hobbyId) return; setData((current) => ({ ...current, sessions: [...current.sessions, session] })); setSession(blankSession()); };
  const addArtifact = () => { if (!artifact.hobbyId || !artifact.title.trim()) return; setData((current) => ({ ...current, artifacts: [...current.artifacts, { ...artifact, title: artifact.title.trim() }] })); setArtifact(blankArtifact()); };
  const hobbyName = (id?: string) => data.hobbies.find((item) => item.id === id)?.title ?? 'Unknown hobby';
  return <div className="flex min-w-0 flex-1 flex-col overflow-y-auto"><header className="border-b border-border px-4 py-2.5"><h2 className="text-sm font-semibold">Practice & artifacts</h2></header><div className="grid gap-4 p-4 xl:grid-cols-2">
    <section><PopoverEditor title="Plan or log session"><Choice label="Hobby" value={session.hobbyId ?? ''} options={data.hobbies.map((item) => ({ value: item.id, label: item.title }))} placeholder="Select hobby" onChange={(hobbyId) => setSession({ ...session, hobbyId })} /><Field label="Date"><Input type="date" value={session.date} onChange={(event) => setSession({ ...session, date: event.target.value })} /></Field><Choice label="Day block" value={session.blockId ?? ''} options={DAY_BLOCKS.map((item) => ({ value: item.id, label: item.label }))} placeholder="Unblocked" onChange={(blockId) => setSession({ ...session, blockId: blockId as HobbySession['blockId'] })} /><Field label="Minutes"><Input type="number" min={5} step={5} value={session.durationMinutes} onChange={(event) => setSession({ ...session, durationMinutes: Number(event.target.value) })} /></Field><Choice label="Status" value={session.status} options={HOBBY_SESSION_STATUSES} onChange={(status) => setSession({ ...session, status: status as HobbySession['status'] })} /><Field label="People"><Input value={session.people.join(', ')} onChange={(event) => setSession({ ...session, people: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} placeholder="Names, comma separated" /></Field><Choice label="Energy before" value={session.energyBefore ?? ''} options={HOBBY_ENERGIES} placeholder="Not logged" onChange={(energyBefore) => setSession({ ...session, energyBefore: energyBefore as HobbySession['energyBefore'] })} /><Choice label="Energy after" value={session.energyAfter ?? ''} options={HOBBY_ENERGIES} placeholder="Not logged" onChange={(energyAfter) => setSession({ ...session, energyAfter: energyAfter as HobbySession['energyAfter'] })} /><Field label="Notes"><Textarea className="sm:col-span-2" rows={2} value={session.notes} onChange={(event) => setSession({ ...session, notes: event.target.value })} /></Field><Button className="sm:col-span-2" onClick={addSession} disabled={!session.hobbyId}><Plus className="size-4" />Add session</Button></PopoverEditor></section>
    <section><PopoverEditor title="Capture artifact"><Choice label="Hobby" value={artifact.hobbyId} options={data.hobbies.map((item) => ({ value: item.id, label: item.title }))} placeholder="Select hobby" onChange={(hobbyId) => setArtifact({ ...artifact, hobbyId })} /><Field label="Date"><Input type="date" value={artifact.date} onChange={(event) => setArtifact({ ...artifact, date: event.target.value })} /></Field><Field label="Title"><Input value={artifact.title} onChange={(event) => setArtifact({ ...artifact, title: event.target.value })} /></Field><Field label="Type"><Input value={artifact.type} onChange={(event) => setArtifact({ ...artifact, type: event.target.value })} placeholder="Track, module, meal, note, photo…" /></Field><Field label="Link"><Input value={artifact.url ?? ''} onChange={(event) => setArtifact({ ...artifact, url: event.target.value || undefined })} /></Field><Field label="Notes"><Input value={artifact.notes} onChange={(event) => setArtifact({ ...artifact, notes: event.target.value })} /></Field><Button className="sm:col-span-2" onClick={addArtifact} disabled={!artifact.hobbyId || !artifact.title.trim()}><Plus className="size-4" />Add artifact</Button></PopoverEditor></section>
    <section className="rounded-sm border border-border xl:col-span-2"><header className="border-b border-border px-3 py-2 text-sm font-medium">Session log</header><div className="divide-y divide-border">{data.sessions.filter((item) => item.hobbyId).length === 0 ? <p className="p-4 text-xs text-muted-foreground">No hobby sessions logged.</p> : [...data.sessions].filter((item) => item.hobbyId).sort((a, b) => b.date.localeCompare(a.date)).map((item) => <div key={item.id} className="flex items-center gap-2 px-3 py-2 text-xs"><Button size="icon" variant="ghost" className="size-7" aria-label="Toggle completed" onClick={() => setData((current) => ({ ...current, sessions: current.sessions.map((candidate) => candidate.id === item.id ? { ...candidate, status: candidate.status === 'Done' ? 'Planned' : 'Done' } : candidate) }))}><Check className={item.status === 'Done' ? 'size-4 text-success' : 'size-4 text-muted-foreground/30'} /></Button><span className="font-medium">{hobbyName(item.hobbyId)}</span><span className="rounded-sm border border-border px-2 py-0.5 text-muted-foreground">{item.status}</span><span className="ml-auto text-muted-foreground">{item.date} · {item.durationMinutes}m{item.blockId ? ` · ${DAY_BLOCKS.find((block) => block.id === item.blockId)?.label}` : ''}</span><Button size="icon" variant="ghost" className="size-7" aria-label="Delete session" onClick={() => setData((current) => ({ ...current, sessions: current.sessions.filter((candidate) => candidate.id !== item.id) }))}><Trash2 className="size-3.5" /></Button></div>)}</div></section>
    <section className="rounded-sm border border-border xl:col-span-2"><header className="border-b border-border px-3 py-2 text-sm font-medium">Artifacts shipped</header><div className="divide-y divide-border">{data.artifacts.length === 0 ? <p className="p-3 text-xs text-muted-foreground">No artifacts yet.</p> : [...data.artifacts].sort((a, b) => b.date.localeCompare(a.date)).map((item) => <div key={item.id} className="flex items-start gap-3 px-3 py-2.5"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="truncate text-xs text-muted-foreground">{hobbyName(item.hobbyId)} · {item.type || 'Artifact'} · {item.date}</p>{item.notes && <p className="mt-1 text-xs text-muted-foreground">{item.notes}</p>}</div><Button size="icon" variant="ghost" className="size-7" aria-label="Delete artifact" onClick={() => setData((current) => ({ ...current, artifacts: current.artifacts.filter((candidate) => candidate.id !== item.id) }))}><Trash2 className="size-3.5" /></Button></div>)}</div></section>
  </div></div>;
}
