import {
  BookCopy,
  BookOpen,
  BookText,
  Clapperboard,
  Disc3,
  FilePenLine,
  Gamepad2,
  GraduationCap,
  Headphones,
  Music2,
  Newspaper,
  NotebookPen,
  PanelsTopLeft,
  Podcast,
  ScrollText,
  Theater,
  Tv,
  Youtube,
  Feather,
  Camera,
  Palette,
  PenTool,
  Building2,
  Armchair,
  Paintbrush,
  Video,
  Film,
  MonitorPlay,
  Aperture,
  Globe,
  Projector,
  Radio,
  RadioTower,
  Disc,
  AudioLines,
  MessageSquareQuote,
  Presentation,
  MessagesSquare,
  History,
  BookAudio,
  Drama,
  Music4,
  Landmark,
  Footprints,
  Speaker,
  PersonStanding,
  Tent,
  Sparkles,
  Dices,
  Swords,
  Spade,
  Puzzle,
  ScanEye,
  MicVocal,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";
import type { MediaType } from "./mediaLibrary";

export const MEDIA_TYPE_ICONS: Record<MediaType, LucideIcon> = {
  Book: BookOpen,
  Ebook: BookText,
  Audiobook: Headphones,
  "Short story": FilePenLine,
  Novella: NotebookPen,
  Essay: ScrollText,
  Article: Newspaper,
  "Comic & graphic novel": PanelsTopLeft,
  Manga: BookCopy,
  "Magazine & zine": Newspaper,
  Poetry: Feather,
  Movie: Clapperboard,
  "TV series": Tv,
  "YouTube video": Youtube,
  Animation: WandSparkles,
  Album: Disc3,
  Song: Music2,
  Podcast,
  "Video game": Gamepad2,
  "Board game": Dices,
  TTRPG: Swords,
  "Card game": Spade,
  Puzzle: Puzzle,
  ARG: ScanEye,
  Course: GraduationCap,
  "Live performance": Theater,
  "Stand-up": MicVocal,
  Photograph: Camera,
  Artwork: Palette,
  "Graphic design": PenTool,
  Architecture: Building2,
  "Product design": Armchair,
  Illustration: Paintbrush,
  Documentary: Video,
  "Short film": Film,
  "Music video": MonitorPlay,
  "Experimental film": Aperture,
  "Web series": Globe,
  "Commercial & title sequence": Projector,
  "Radio drama": Radio,
  "Radio documentary": RadioTower,
  "DJ mix": Disc,
  "Live recording": AudioLines,
  Interview: MessageSquareQuote,
  "Speech & lecture": Presentation,
  Debate: MessagesSquare,
  "Oral history": History,
  Reading: BookAudio,
  Theatre: Drama,
  Musical: Music4,
  Opera: Landmark,
  Dance: Footprints,
  Concert: Speaker,
  "Performance art": PersonStanding,
  "Circus & physical theatre": Tent,
  "Magic & illusion": Sparkles,
};

export const SQUARE_MEDIA_TYPES = new Set<MediaType>([
  "Audiobook",
  "Album",
  "Song",
  "Podcast",
]);
export const LANDSCAPE_MEDIA_TYPES = new Set<MediaType>(["YouTube video"]);

export const MEDIA_ARTWORK_TONES: Record<MediaType, string> = {
  Book: "bg-warning/10 text-warning",
  Ebook: "bg-warning/10 text-warning",
  Audiobook: "bg-destructive/10 text-destructive",
  "Short story": "bg-warning/10 text-warning",
  Novella: "bg-warning/10 text-warning",
  Essay: "bg-warning/10 text-warning",
  Article: "bg-warning/10 text-warning",
  "Comic & graphic novel": "bg-warning/10 text-warning",
  Manga: "bg-destructive/10 text-destructive",
  "Magazine & zine": "bg-info/10 text-info",
  Poetry: "bg-warning/10 text-warning",
  Movie: "bg-info/10 text-info",
  "TV series": "bg-info/10 text-info",
  "YouTube video": "bg-destructive/10 text-destructive",
  Animation: "bg-info/10 text-info",
  Album: "bg-destructive/10 text-destructive",
  Song: "bg-destructive/10 text-destructive",
  Podcast: "bg-destructive/10 text-destructive",
  "Video game": "bg-success/10 text-success",
  "Board game": "bg-success/10 text-success",
  TTRPG: "bg-success/10 text-success",
  "Card game": "bg-success/10 text-success",
  Puzzle: "bg-success/10 text-success",
  ARG: "bg-success/10 text-success",
  Course: "bg-primary/10 text-primary",
  "Live performance": "bg-accent text-accent-foreground",
  "Stand-up": "bg-accent text-accent-foreground",
  Photograph: "bg-info/10 text-info",
  Artwork: "bg-info/10 text-info",
  "Graphic design": "bg-info/10 text-info",
  Architecture: "bg-info/10 text-info",
  "Product design": "bg-info/10 text-info",
  Illustration: "bg-info/10 text-info",
  Documentary: "bg-info/10 text-info",
  "Short film": "bg-info/10 text-info",
  "Music video": "bg-destructive/10 text-destructive",
  "Experimental film": "bg-info/10 text-info",
  "Web series": "bg-destructive/10 text-destructive",
  "Commercial & title sequence": "bg-info/10 text-info",
  "Radio drama": "bg-destructive/10 text-destructive",
  "Radio documentary": "bg-destructive/10 text-destructive",
  "DJ mix": "bg-destructive/10 text-destructive",
  "Live recording": "bg-destructive/10 text-destructive",
  Interview: "bg-primary/10 text-primary",
  "Speech & lecture": "bg-primary/10 text-primary",
  Debate: "bg-primary/10 text-primary",
  "Oral history": "bg-primary/10 text-primary",
  Reading: "bg-primary/10 text-primary",
  Theatre: "bg-accent text-accent-foreground",
  Musical: "bg-accent text-accent-foreground",
  Opera: "bg-accent text-accent-foreground",
  Dance: "bg-accent text-accent-foreground",
  Concert: "bg-accent text-accent-foreground",
  "Performance art": "bg-accent text-accent-foreground",
  "Circus & physical theatre": "bg-accent text-accent-foreground",
  "Magic & illusion": "bg-accent text-accent-foreground",
};
