import { DAY_BLOCKS, type DayBlockId } from './dayBlocks';
export const TTRPG_STORE_KEY = 'modulo-ttrpg-v1';
export const CAMPAIGN_STATUSES = ['Idea', 'Recruiting', 'Active', 'Paused', 'Completed', 'Archived'] as const; export const TTRPG_ENTITY_TYPES = ['Player Character', 'NPC', 'Location', 'Faction', 'Quest', 'Item', 'Lore', 'Encounter', 'Handout'] as const; export const GAME_SESSION_STATUSES = ['Planned', 'Played', 'Cancelled'] as const;
export interface Campaign { id: string; title: string; system: string; status: typeof CAMPAIGN_STATUSES[number]; cadence: string; nextSession?: string; location: string; gm: string; players: string[]; tone: string; safetyTools: string; notes: string; }
export interface TtrpgEntity { id: string; campaignId: string; type: typeof TTRPG_ENTITY_TYPES[number]; name: string; status: string; summary: string; links: string[]; }
export interface GameSession { id: string; campaignId: string; title: string; date: string; minutes: number; blockId?: DayBlockId; status: typeof GAME_SESSION_STATUSES[number]; attendees: string[]; prep: string; summary: string; decisions: string; nextHook: string; }
export interface TtrpgData { version: 1; campaigns: Campaign[]; entities: TtrpgEntity[]; sessions: GameSession[]; }
export const emptyTtrpgData = (): TtrpgData => ({ version: 1, campaigns: [], entities: [], sessions: [] }); export const newTtrpgId = (p: 'campaign' | 'entity' | 'session') => `ttrpg-${p}-${Math.random().toString(36).slice(2, 10)}`;
const object = (v: unknown): Record<string, unknown> => typeof v === 'object' && v !== null ? v as Record<string, unknown> : {}; const array = (v: unknown): unknown[] => Array.isArray(v) ? v : []; const text = (v: unknown): string => typeof v === 'string' ? v : ''; const optionalText = (v: unknown): string | undefined => text(v) || undefined; const strings = (v: unknown): string[] => array(v).filter((x): x is string => typeof x === 'string'); const num = (v: unknown): number => Number.isFinite(Number(v)) ? Number(v) : 0; const choice = <T extends string>(v: unknown, values: readonly T[], fallback: T): T => values.includes(v as T) ? v as T : fallback; const block = (v: unknown): DayBlockId | undefined => DAY_BLOCKS.some((x) => x.id === v) ? v as DayBlockId : undefined;
export function parseTtrpgData(value: unknown): TtrpgData { const raw = object(value); return { version: 1, campaigns: array(raw.campaigns).map(object).filter((v) => text(v.id) && text(v.title)).map((v) => ({ id: text(v.id), title: text(v.title), system: text(v.system), status: choice(v.status, CAMPAIGN_STATUSES, 'Idea'), cadence: text(v.cadence), nextSession: optionalText(v.nextSession), location: text(v.location), gm: text(v.gm), players: strings(v.players), tone: text(v.tone), safetyTools: text(v.safetyTools), notes: text(v.notes) })), entities: array(raw.entities).map(object).filter((v) => text(v.id) && text(v.campaignId) && text(v.name)).map((v) => ({ id: text(v.id), campaignId: text(v.campaignId), type: choice(v.type, TTRPG_ENTITY_TYPES, 'Lore'), name: text(v.name), status: text(v.status), summary: text(v.summary), links: strings(v.links) })), sessions: array(raw.sessions).map(object).filter((v) => text(v.id) && text(v.campaignId) && text(v.title)).map((v) => ({ id: text(v.id), campaignId: text(v.campaignId), title: text(v.title), date: text(v.date), minutes: Math.max(0, num(v.minutes)), blockId: block(v.blockId), status: choice(v.status, GAME_SESSION_STATUSES, 'Planned'), attendees: strings(v.attendees), prep: text(v.prep), summary: text(v.summary), decisions: text(v.decisions), nextHook: text(v.nextHook) })) }; }
 export const gameSessionsOn = (data: TtrpgData, date: string): GameSession[] => data.sessions.filter((session) => session.date === date);
