import { DAY_BLOCKS, type DayBlockId } from './dayBlocks';
export const WARDROBE_STORE_KEY = 'modulo-wardrobe-v1';
export const GARMENT_CATEGORIES = ['Top', 'Bottom', 'Outerwear', 'Dress', 'Suit', 'Shoes', 'Bag', 'Accessory', 'Underwear', 'Activewear', 'Other'] as const;
export const GARMENT_STATUSES = ['Active', 'Seasonal', 'Repair', 'Alteration', 'Sell', 'Donate', 'Archived'] as const;
export const STYLE_LOG_TYPES = ['Wear', 'Experiment', 'Repair', 'Alteration', 'Declutter', 'Capsule Review'] as const;
export interface Garment { id: string; name: string; category: typeof GARMENT_CATEGORIES[number]; status: typeof GARMENT_STATUSES[number]; brand: string; size: string; color: string; seasons: string[]; storage: string; inventoryId?: string; wishlistId?: string; notes: string; }
export interface Outfit { id: string; title: string; garmentIds: string[]; silhouette: string; archetype: string; occasion: string; season: string; rating?: number; notes: string; }
export interface StyleLog { id: string; outfitId?: string; type: typeof STYLE_LOG_TYPES[number]; title: string; date: string; blockId?: DayBlockId; done: boolean; rating?: number; notes: string; }
export interface WardrobeData { version: 1; garments: Garment[]; outfits: Outfit[]; logs: StyleLog[]; }
export const emptyWardrobeData = (): WardrobeData => ({ version: 1, garments: [], outfits: [], logs: [] }); export const newWardrobeId = (p: 'garment' | 'outfit' | 'log') => `wardrobe-${p}-${Math.random().toString(36).slice(2, 10)}`;
const object = (v: unknown): Record<string, unknown> => typeof v === 'object' && v !== null ? v as Record<string, unknown> : {}; const array = (v: unknown): unknown[] => Array.isArray(v) ? v : []; const text = (v: unknown): string => typeof v === 'string' ? v : ''; const optionalText = (v: unknown): string | undefined => text(v) || undefined; const strings = (v: unknown): string[] => array(v).filter((x): x is string => typeof x === 'string'); const num = (v: unknown): number | undefined => Number.isFinite(Number(v)) ? Number(v) : undefined; const choice = <T extends string>(v: unknown, values: readonly T[], fallback: T): T => values.includes(v as T) ? v as T : fallback; const block = (v: unknown): DayBlockId | undefined => DAY_BLOCKS.some((x) => x.id === v) ? v as DayBlockId : undefined;
export function parseWardrobeData(value: unknown): WardrobeData { const raw = object(value); return { version: 1, garments: array(raw.garments).map(object).filter((v) => text(v.id) && text(v.name)).map((v) => ({ id: text(v.id), name: text(v.name), category: choice(v.category, GARMENT_CATEGORIES, 'Other'), status: choice(v.status, GARMENT_STATUSES, 'Active'), brand: text(v.brand), size: text(v.size), color: text(v.color), seasons: strings(v.seasons), storage: text(v.storage), inventoryId: optionalText(v.inventoryId), wishlistId: optionalText(v.wishlistId), notes: text(v.notes) })), outfits: array(raw.outfits).map(object).filter((v) => text(v.id) && text(v.title)).map((v) => ({ id: text(v.id), title: text(v.title), garmentIds: strings(v.garmentIds), silhouette: text(v.silhouette), archetype: text(v.archetype), occasion: text(v.occasion), season: text(v.season), rating: num(v.rating), notes: text(v.notes) })), logs: array(raw.logs).map(object).filter((v) => text(v.id) && text(v.title) && text(v.date)).map((v) => ({ id: text(v.id), outfitId: optionalText(v.outfitId), type: choice(v.type, STYLE_LOG_TYPES, 'Wear'), title: text(v.title), date: text(v.date), blockId: block(v.blockId), done: Boolean(v.done), rating: num(v.rating), notes: text(v.notes) })) }; }
export const styleLogsOn = (data: WardrobeData, date: string): StyleLog[] => data.logs.filter((log) => log.date === date);
