apiVersion: v1
kind: Namespace
metadata:
  name: litmus
  labels:
    name: litmus
    app.kubernetes.io/name: litmus
    app.kubernetes.io/component: operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosengines.litmuschaos.io
spec:
  group: litmuschaos.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              appinfo:
                type: object
                properties:
                  appns:
                    type: string
                  applabel:
                    type: string
                  appkind:
                    type: string
              chaosServiceAccount:
                type: string
              experiments:
                type: array
                items:
                  type: object
              jobCleanUpPolicy:
                type: string
              annotationCheck:
                type: string
          status:
            type: object
  scope: Namespaced
  names:
    plural: chaosengines
    singular: chaosengine
    kind: ChaosEngine
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosexperiments.litmuschaos.io
spec:
  group: litmuschaos.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: chaosexperiments
    singular: chaosexperiment
    kind: ChaosExperiment
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosresults.litmuschaos.io
spec:
  group: litmuschaos.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: chaosresults
    singular: chaosresult
    kind: ChaosResult
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus
  namespace: litmus
  labels:
    name: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: litmus
  labels:
    name: litmus
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "events", "replicationcontrollers", "services", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines", "chaosexperiments", "chaosresults"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: litmus
  labels:
    name: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litmus
subjects:
- kind: ServiceAccount
  name: litmus
  namespace: litmus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-operator-ce
  namespace: litmus
  labels:
    name: chaos-operator-ce
    app.kubernetes.io/name: litmus
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-operator-ce
  template:
    metadata:
      labels:
        name: chaos-operator-ce
        app.kubernetes.io/name: litmus
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: litmus
      containers:
      - name: chaos-operator-ce
        image: litmuschaos/chaos-operator:3.8.0
        command:
        - chaos-operator
        args:
        - -leader-elect=true
        imagePullPolicy: Always
        env:
        - name: CHAOS_RUNNER_IMAGE
          value: "litmuschaos/chaos-runner:3.8.0"
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "chaos-operator-ce"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 125m
            memory: 300Mi
          requests:
            cpu: 125m
            memory: 300Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-operator-config
  namespace: litmus
data:
  # Chaos operator configuration
  ANALYTICS: "FALSE"
  CHAOS_RUNNER_IMAGE: "litmuschaos/chaos-runner:3.8.0"
  EXPERIMENT_IMAGE: "litmuschaos/go-runner:3.8.0"
