import {useEffect,useRef,useState} from 'react';
import {authenticatedRequest} from '../../services/authenticatedRequest';
import {readPropertyFrontmatter,writePropertyFrontmatter,validateProperty,type PropertyDefinition,type PropertyValue} from './propertyFrontmatter';
const field='rounded border border-border bg-background px-2 py-1 text-sm';
interface Snapshot {noteId:number;version:number;values:Record<string,PropertyValue>}
async function request<T>(path:string,body?:unknown,method='POST'):Promise<T>{const response=await authenticatedRequest(`/api/note-properties/${path}`,body===undefined?undefined:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(response.status===409?'This note changed elsewhere. Your input is retained. Load the current version before retrying.':`Property request failed (${response.status}). Your input is retained.`);return response.json();}
export function NotePropertyPanel({noteId,content,onSaved,notes,contentBusy=false}:{noteId:number;content:string;onSaved:(content:string)=>void;notes:{id:number;title:string}[];contentBusy?:boolean}){
 const [definitions,setDefinitions]=useState<PropertyDefinition[]>([]);const [snapshot,setSnapshot]=useState<Snapshot>();const [values,setValues]=useState<Record<string,PropertyValue>>({});const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [newKey,setNewKey]=useState('');const [newType,setNewType]=useState('text');const [options,setOptions]=useState('');const [dirty,setDirty]=useState(false);const active=useRef(true);
 useEffect(()=>{active.current=true;Promise.all([request<PropertyDefinition[]>('definitions'),request<Snapshot[]>('read',{noteIds:[noteId]})]).then(([defs,rows])=>{if(active.current){setDefinitions(defs);setSnapshot(rows[0]);setValues(rows[0].values);}}).catch(e=>{if(active.current)setError(e.message);});return()=>{active.current=false;};},[noteId]);
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){if(active.current)setError(e instanceof Error?e.message:'Property request failed.');}finally{if(active.current)setBusy(false);}}
 function update(key:string,value:PropertyValue|undefined){setValues(previous=>{const next={...previous};if(value===undefined)delete next[key];else next[key]=value;return next;});setDirty(true);setNotice('');}
 async function save(){if(!snapshot)return;await run(async()=>{for(const def of definitions)if(Object.prototype.hasOwnProperty.call(values,def.key))validateProperty(def,values[def.key]);const markdown=writePropertyFrontmatter(content,values,definitions);const result=await request<Snapshot[]>('document',{change:{noteId,version:snapshot.version,set:values,remove:Object.keys(snapshot.values).filter(key=>!Object.prototype.hasOwnProperty.call(values,key))},markdown,expectedMarkdown:content});setSnapshot(result[0]);setValues(result[0].values);setDirty(false);onSaved(markdown);setNotice('Properties and Markdown saved.');});}
 return <details className="shrink-0 border-b border-border px-4 py-2"><summary className="cursor-pointer text-sm">Properties{dirty?' · unsaved':''}</summary><div className="max-h-80 space-y-3 overflow-y-auto py-3">
 {error&&<p role="alert" className="text-sm">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}
 <fieldset disabled={busy||!snapshot||contentBusy} className="space-y-3"><legend className="sr-only">Typed note properties</legend>
 {definitions.map(def=>{const present=Object.prototype.hasOwnProperty.call(values,def.key);const value=values[def.key];return <div key={def.key} className="flex flex-wrap items-start gap-2"><label className="flex min-w-36 flex-col gap-1 text-sm">{def.title} value state<select className={field} value={!present?'missing':value===null?'null':'value'} onChange={event=>update(def.key,event.target.value==='missing'?undefined:event.target.value==='null'?null:def.type==='boolean'?false:def.type==='number'?0:def.type==='multiSelect'?[]:def.type==='noteReference'?notes[0]?.id??0:'')}><option value="missing">Missing</option><option value="null">Null</option><option value="value">Value</option></select></label>{present&&value!==null&&<PropertyInput definition={def} value={value} notes={notes} onChange={next=>update(def.key,next)}/>}</div>;})}
 <div className="flex flex-wrap gap-3"><button className={field} onClick={save}>Save properties and Markdown</button><button className={field} onClick={()=>{try{const markdown=writePropertyFrontmatter(content,values,definitions);const url=URL.createObjectURL(new Blob([markdown],{type:'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`note-${noteId}.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}}>Export Markdown with properties</button><button className={field} onClick={()=>{try{const parsed=readPropertyFrontmatter(content,definitions);setValues(parsed.values);setDirty(true);setError('');setNotice(parsed.unknown.length?`Unknown property fields preserved: ${parsed.unknown.join(', ')}.`:'Imported frontmatter into the property draft. Review and save.');}catch(e){setError((e as Error).message);}}}>Import from current Markdown</button><button className={field} onClick={()=>run(async()=>{const current=(await request<Snapshot[]>('read',{noteIds:[noteId]}))[0];setSnapshot(current);setNotice('Current version loaded. Your property input is retained; review before saving.');})}>Load current version, keep input</button></div>
 </fieldset>
 <details><summary className="cursor-pointer text-sm">Define a property</summary><fieldset disabled={busy||contentBusy} className="mt-2 flex flex-wrap items-end gap-2"><label className="flex flex-col gap-1 text-sm">Property key<input className={field} list="property-key-suggestions" value={newKey} onChange={e=>{setNewKey(e.target.value);const suggestions:Record<string,string>={status:"select",due:"date",owner:"noteReference",priority:"number",reviewed:"boolean"};if(suggestions[e.target.value])setNewType(suggestions[e.target.value]);}} placeholder="status"/></label><label className="flex flex-col gap-1 text-sm">Property type<select className={field} value={newType} onChange={e=>setNewType(e.target.value)}>{['text','number','boolean','date','datetime','select','multiSelect','link','noteReference'].map(type=><option key={type}>{type}</option>)}</select></label>{['select','multiSelect'].includes(newType)&&<label className="flex flex-col gap-1 text-sm">Choices, one per line<textarea className={field} value={options} onChange={e=>setOptions(e.target.value)}/></label>}<button className={field} onClick={()=>run(async()=>{if(!/^[a-z][a-z0-9_.-]{0,127}$/.test(newKey))throw new Error('Use a lowercase property key beginning with a letter.');const definition=await request<PropertyDefinition>('definitions',{key:newKey,title:newKey,type:newType,options:['select','multiSelect'].includes(newType)?options.split('\n').map(value=>value.trim()).filter(Boolean):[],revision:0},'PUT');setDefinitions(previous=>[...previous,definition]);setNewKey('');})}>Add property definition</button></fieldset><datalist id="property-key-suggestions">{["status","due","owner","priority","reviewed"].filter(key=>!definitions.some(def=>def.key===key)).map(key=><option key={key} value={key}/>)}</datalist></details>
 </div></details>;
}
function PropertyInput({definition:def,value,onChange,notes}:{definition:PropertyDefinition;value:PropertyValue;onChange:(value:PropertyValue)=>void;notes:{id:number;title:string}[]}){
 if(def.type==='multiSelect')return <fieldset><legend className="text-sm">{def.title}</legend>{def.options.map(option=><label key={option} className="mr-3 inline-flex gap-1 text-sm"><input type="checkbox" checked={Array.isArray(value)&&value.includes(option)} onChange={event=>onChange(event.target.checked?[...(Array.isArray(value)?value:[]),option]:(Array.isArray(value)?value:[]).filter(item=>item!==option))}/>{option}</label>)}</fieldset>;
 if(def.type==='boolean')return <label className="mt-5 flex gap-2 text-sm"><input type="checkbox" checked={value===true} onChange={event=>onChange(event.target.checked)}/>{def.title}</label>;
 if(def.type==='select'||def.type==='noteReference')return <label className="flex flex-col gap-1 text-sm">{def.title}<select className={field} value={String(value??'')} onChange={event=>onChange(def.type==='noteReference'?Number(event.target.value):event.target.value)}><option value="">Choose…</option>{def.type==='select'?def.options.map(option=><option key={option}>{option}</option>):notes.map(note=><option key={note.id} value={note.id}>{note.title} (#{note.id})</option>)}</select></label>;
 return <label className="flex flex-col gap-1 text-sm">{def.title}{def.type==='datetime'?' (UTC, ISO 8601)':''}<input className={field} type={def.type==='date'?'date':def.type==='number'?'number':def.type==='link'?'url':'text'} value={String(value??'')} step={def.type==='number'?'any':undefined} onChange={event=>onChange(def.type==='number'&&event.target.value!==''?Number(event.target.value):event.target.value)}/></label>;
}
