import {PropertyInput} from './NotePropertyPanel';
import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {authenticatedRequest} from '../../services/authenticatedRequest';
import {queryRequest,type QueryConfiguration,type QueryResults,type QueryRow,type SavedQuery} from './propertyQueryApi';
import {type PropertyDefinition,type PropertyValue,validateProperty,writePropertyFrontmatter} from './propertyFrontmatter';
const field='rounded border border-border bg-background px-2 py-1 text-sm';
const empty=():QueryConfiguration=>({filters:[],sort:{key:'noteId',direction:'asc'},groupBy:null,columns:[],formulas:[],view:'table'});
export function PropertyQueries(){const [params,setParams]=useSearchParams();const [queries,setQueries]=useState<SavedQuery[]>([]);const [definitions,setDefinitions]=useState<PropertyDefinition[]>([]);const [current,setCurrent]=useState<SavedQuery>();const [title,setTitle]=useState('New query');const [configuration,setConfiguration]=useState<QueryConfiguration>(empty);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const id=params.get('query');
 useEffect(()=>{let active=true;Promise.all([queryRequest<SavedQuery[]>(''),authenticatedRequest('/api/note-properties/definitions').then(async response=>{if(!response.ok)throw new Error('Property definitions unavailable.');return response.json();})]).then(([list,defs])=>{if(active){setQueries(list);setDefinitions(defs);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision]);
 useEffect(()=>{let active=true;if(!id){setCurrent(undefined);setTitle('New query');setConfiguration(empty());return;}queryRequest<SavedQuery>(`/${id}`).then(value=>{if(active){setCurrent(value);setTitle(value.title);setConfiguration(value.configuration);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,revision]);
 async function save(){setBusy(true);setError('');try{const saved=await queryRequest<SavedQuery>('',{id:current?.id,revision:current?.revision??0,title,configuration});setCurrent(saved);setParams({query:saved.id});setRevision(value=>value+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-6xl space-y-4 px-4 py-6"><h1 className="text-xl font-semibold">Property queries</h1>{error&&<p role="alert">{error}</p>}<div className="flex flex-wrap gap-2"><label className="text-sm">Saved query <select className={field} disabled={busy} value={id??''} onChange={event=>setParams(event.target.value?{query:event.target.value}:{})}><option value="">New query</option>{queries.map(query=><option key={query.id} value={query.id}>{query.title}</option>)}</select></label></div>
 <fieldset disabled={busy} className="space-y-3"><legend className="sr-only">Query configuration</legend><label className="flex flex-col gap-1 text-sm">Query title<input className={field} value={title} onChange={event=>setTitle(event.target.value)}/></label>
 <fieldset className="flex flex-wrap gap-3"><legend className="text-sm">Columns</legend>{definitions.map(def=><label key={def.key} className="flex gap-1 text-sm"><input type="checkbox" checked={configuration.columns.includes(def.key)} onChange={event=>setConfiguration({...configuration,columns:event.target.checked?[...configuration.columns,def.key]:configuration.columns.filter(key=>key!==def.key)})}/>{def.title}</label>)}</fieldset>
 <div className="flex flex-wrap gap-3"><label className="text-sm">Sort <select className={field} value={configuration.sort.key} onChange={event=>setConfiguration({...configuration,sort:{...configuration.sort,key:event.target.value}})}><option value="noteId">Note ID</option>{definitions.map(def=><option key={def.key} value={def.key}>{def.title}</option>)}</select></label><label className="text-sm">Direction <select className={field} value={configuration.sort.direction} onChange={event=>setConfiguration({...configuration,sort:{...configuration.sort,direction:event.target.value as 'asc'|'desc'}})}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><label className="text-sm">Group by <select className={field} value={configuration.groupBy??''} onChange={event=>setConfiguration({...configuration,groupBy:event.target.value||null})}><option value="">None</option>{definitions.map(def=><option key={def.key} value={def.key}>{def.title}</option>)}</select></label></div>
 <fieldset className="space-y-2"><legend className="text-sm">All filters must match</legend>{configuration.filters.map((filter,index)=><div key={index} className="flex flex-wrap gap-2"><label className="text-sm">Filter {index+1} property <select className={field} value={filter.key} onChange={event=>setConfiguration({...configuration,filters:configuration.filters.map((item,i)=>i===index?{...item,key:event.target.value}:item)})}>{definitions.map(def=><option key={def.key} value={def.key}>{def.title}</option>)}</select></label><label className="text-sm">Filter {index+1} operator <select className={field} value={filter.operator} onChange={event=>setConfiguration({...configuration,filters:configuration.filters.map((item,i)=>i===index?{...item,operator:event.target.value}:item)})}>{['eq','gt','gte','lt','lte','contains','exists','missing'].map(operator=><option key={operator}>{operator}</option>)}</select></label>{!['exists','missing'].includes(filter.operator)&&<FilterValue definition={definitions.find(def=>def.key===filter.key)} operator={filter.operator} value={filter.value} onChange={value=>setConfiguration({...configuration,filters:configuration.filters.map((item,i)=>i===index?{...item,value}:item)})}/>}<button className="text-sm underline" onClick={()=>setConfiguration({...configuration,filters:configuration.filters.filter((_,i)=>i!==index)})}>Remove filter {index+1}</button></div>)}<button className={field} disabled={!definitions.length||configuration.filters.length>=10} onClick={()=>setConfiguration({...configuration,filters:[...configuration.filters,{key:definitions[0].key,operator:'exists'}]})}>Add filter</button></fieldset>
 <fieldset className="space-y-2"><legend className="text-sm">Calculated columns</legend>{configuration.formulas.map((formula,index)=><div key={index} className="flex flex-wrap gap-2"><label className="text-sm">Formula {index+1} title <input className={field} value={formula.title} onChange={event=>setConfiguration({...configuration,formulas:configuration.formulas.map((item,i)=>i===index?{...item,title:event.target.value}:item)})}/></label><label className="text-sm">Formula {index+1} operation <select className={field} value={formula.operation} onChange={event=>setConfiguration({...configuration,formulas:configuration.formulas.map((item,i)=>i===index?{...item,operation:event.target.value as 'sum'|'concat'}:item)})}><option value="sum">Sum</option><option value="concat">Concatenate</option></select></label><label className="text-sm">Formula {index+1} property keys, comma separated <input className={field} value={formula.keys.join(',')} onChange={event=>setConfiguration({...configuration,formulas:configuration.formulas.map((item,i)=>i===index?{...item,keys:event.target.value.split(',').map(key=>key.trim())}:item)})}/></label><button className="text-sm underline" onClick={()=>setConfiguration({...configuration,formulas:configuration.formulas.filter((_,i)=>i!==index)})}>Remove formula {index+1}</button></div>)}<button className={field} disabled={configuration.formulas.length>=10} onClick={()=>setConfiguration({...configuration,formulas:[...configuration.formulas,{title:'Total',operation:'sum',keys:[]}]})}>Add formula</button></fieldset>
 <button className={field} onClick={save}>Save query</button></fieldset>{current&&<><p className="text-sm">Embed in a note with a <code>property-query</code> fenced block containing <code>{current.id}</code>, or link to <Link className="underline" to={`/app/property-queries?query=${current.id}`}>this query</Link>.</p><PropertyQueryResults key={`${current.id}:${revision}`} id={current.id}/></>}
 </main>;
}
export function PropertyQueryResults({id,initialView}:{id:string;initialView?:QueryConfiguration["view"]}){const [result,setResult]=useState<QueryResults>();const [page,setPage]=useState(0);const [view,setView]=useState<QueryConfiguration['view']>('table');const [definitions,setDefinitions]=useState<PropertyDefinition[]>([]);const [error,setError]=useState('');const [editing,setEditing]=useState<{row:QueryRow;key:string;source:string}>();const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;queryRequest<QueryResults>(`/${id}/results?page=${page}&limit=50`).then(value=>{if(active){setResult(value);if(page===0&&revision===0)setView(initialView??value.query.configuration.view);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,page,revision]);
 useEffect(()=>{let active=true;authenticatedRequest('/api/note-properties/definitions').then(response=>response.json()).then(value=>{if(active&&Array.isArray(value))setDefinitions(value);}).catch(()=>{});const refresh=()=>setRevision(value=>value+1);const timer=setInterval(refresh,15000);window.addEventListener('modulo:properties-changed',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('modulo:properties-changed',refresh);};},[]);
 async function apply(){if(!editing)return;setBusy(true);setError('');try{const value=JSON.parse(editing.source) as PropertyValue;const def=definitions.find(def=>def.key===editing.key);if(!def)throw new Error('Property unavailable.');validateProperty(def,value);const noteResponse=await authenticatedRequest(`/api/notes/${editing.row.noteId}`);if(!noteResponse.ok)throw new Error('Note unavailable.');const note=await noteResponse.json();if(note.version!==editing.row.version)throw new Error('The note changed. Your input is retained; reopen the editor after refreshing.');const original=note.markdownContent??note.content??'';const markdown=writePropertyFrontmatter(original,{...editing.row.values,[editing.key]:value},definitions);const response=await authenticatedRequest('/api/note-properties/document',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({change:{noteId:editing.row.noteId,version:editing.row.version,set:{[editing.key]:value},remove:[]},markdown,expectedMarkdown:original})});if(!response.ok)throw new Error(response.status===409?'The note changed. Your input is retained; close and reopen the editor to load its current version.':'Property update failed.');setEditing(undefined);window.dispatchEvent(new Event('modulo:properties-changed'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!result)return <p role="status">{error||'Loading query…'}</p>;const config=result.query.configuration;const name=(key:string)=>definitions.find(def=>def.key===key)?.title??key;const display=(value:unknown)=>value===undefined?'Missing':value===null?'Null':typeof value==='string'?value:JSON.stringify(value);
 const cells=(row:QueryRow)=><>{config.columns.map(key=><div key={key} className="text-sm"><span>{name(key)}: </span><button className="underline" onClick={()=>setEditing({row,key,source:JSON.stringify(row.values[key]??null)})} aria-label={`Edit ${name(key)} for ${row.title}`}>{display(row.values[key])}</button></div>)}{Object.entries(row.formulas).map(([title,value])=><p key={title} className="text-sm">{title}: {display(value)}</p>)}</>;
 const card=(row:QueryRow)=><article key={row.noteId} className="space-y-2 border-b border-border p-3"><Link className="font-medium underline" to={`/app/notes?note=${row.noteId}`}>{row.title} · #{row.noteId}</Link>{cells(row)}</article>;
 const groups=new Map<string,QueryRow[]>();for(const row of result.rows){const group=display(config.groupBy?row.values[config.groupBy]:undefined);groups.set(group,[...(groups.get(group)??[]),row]);}
 return <section className="space-y-3"><div className="flex flex-wrap items-center gap-2"><h2 className="mr-3 font-medium">{result.query.title}</h2>{(['table','list','card','board'] as const).map(type=><button className={field} key={type} disabled={type==='board'&&!config.groupBy} aria-pressed={view===type} onClick={()=>setView(type)}>{type}</button>)}</div>{error&&<p role="alert">{error}</p>}
 {editing&&definitions.some(def=>def.key===editing.key)&&<fieldset disabled={busy} className="space-y-2 border border-border p-3"><legend>Edit {name(editing.key)}</legend><PropertyInput definition={definitions.find(def=>def.key===editing.key)!} value={JSON.parse(editing.source)} notes={result.rows.map(row=>({id:row.noteId,title:row.title}))} onChange={value=>setEditing({...editing,source:JSON.stringify(value)})}/><button className={field} onClick={()=>setEditing({...editing,source:"null"})}>Set null</button><button className={field} onClick={apply}>Apply property edit</button><button className={`${field} ml-2`} onClick={()=>setEditing(undefined)}>Cancel edit</button></fieldset>}
 {view==='table'?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Note</th>{config.columns.map(key=><th key={key} className="p-2">{name(key)}</th>)}{config.formulas.map(formula=><th key={formula.title}>{formula.title}</th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.noteId} className="border-t border-border"><td className="p-2"><Link className="underline" to={`/app/notes?note=${row.noteId}`}>{row.title}</Link></td>{config.columns.map(key=><td className="p-2" key={key}><button className="underline" aria-label={`Edit ${name(key)} for ${row.title}`} onClick={()=>setEditing({row,key,source:JSON.stringify(row.values[key]??null)})}>{display(row.values[key])}</button></td>)}{Object.entries(row.formulas).map(([title,value])=><td key={title} className="p-2">{display(value)}</td>)}</tr>)}</tbody></table></div>:view==='board'?<div className="flex gap-4 overflow-x-auto">{[...groups].map(([group,rows])=><section key={group} className="min-w-64 flex-1 border border-border"><h3 className="border-b border-border p-3 text-sm font-medium">{group}</h3>{rows.map(card)}</section>)}</div>:<div className={view==='card'?'grid gap-3 sm:grid-cols-2 lg:grid-cols-3':''}>{result.rows.map(card)}</div>}
 <div className="flex items-center gap-3 text-sm"><button className={field} disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous page</button><span>Page {page+1} · {result.rows.length} notes</span><button className={field} disabled={!result.hasMore} onClick={()=>setPage(value=>value+1)}>Next page</button></div><p className="text-sm">Groups and calculations show the current page. Changes refresh automatically.</p></section>;
}

function FilterValue({definition,operator,value,onChange}:{definition?:PropertyDefinition;operator:string;value?:PropertyValue;onChange:(value:PropertyValue)=>void}) {
 if(!definition)return null;
 const effective=definition.type==='multiSelect'&&operator==='contains'?{...definition,type:'select'}:definition;
 return <div className="space-y-1"><label className="flex gap-1 text-sm"><input type="checkbox" checked={value===null} onChange={event=>onChange(event.target.checked?null:effective.type==='boolean'?false:effective.type==='number'?0:effective.type==='multiSelect'?[]:'')}/>Match null</label>{value!==null&&(effective.type==='noteReference'?<label className="text-sm">Owned note ID <input className={field} type="number" min="1" value={String(value??'')} onChange={event=>onChange(Number(event.target.value))}/></label>:<PropertyInput definition={{...effective,title:`${definition.title} filter value`}} value={value??(effective.type==='boolean'?false:effective.type==='multiSelect'?[]:'')} notes={[]} onChange={onChange}/>)}</div>;
}
