import {parseDocument,isMap,isScalar,isAlias,isNode,visit,stringify} from 'yaml';
export type PropertyValue=string|number|boolean|null|string[];
export interface PropertyDefinition {key:string;title:string;type:string;options:string[];revision:number}
const field='moduloProperties';
function split(source:string){const opening=/^---\r?\n/.exec(source);if(!opening)return {prefix:'',yaml:'',suffix:source,newline:'\n'};const rest=source.slice(opening[0].length);const closing=/^---[ \t]*(?:\r?\n|$)/m.exec(rest);if(!closing)throw new Error('Frontmatter closing delimiter is missing.');return {prefix:opening[0],yaml:rest.slice(0,closing.index),suffix:rest.slice(closing.index),newline:opening[0].includes('\r')?'\r\n':'\n'};}
function document(source:string){const parts=split(source);if(parts.yaml.length>65536)throw new Error('Frontmatter exceeds 64 KiB.');const doc=parseDocument(parts.yaml,{version:'1.2',uniqueKeys:true,prettyErrors:false});if(doc.errors.length||doc.warnings.length)throw new Error('Frontmatter has invalid YAML or unsupported tags.');if(doc.contents&&!isMap(doc.contents))throw new Error('Frontmatter must be a mapping.');visit(doc,{Node(_key,node){if(isAlias(node)||node.anchor)throw new Error('YAML aliases and anchors are not supported for property import.');}});return {parts,doc};}
export function readPropertyFrontmatter(source:string,definitions:PropertyDefinition[]){const {doc}=document(source);const map=doc.get(field,true);if(map===undefined)return {values:{} as Record<string,PropertyValue>,unknown:[] as string[]};if(!isMap(map))throw new Error('moduloProperties must be a mapping.');const known=new Map(definitions.map(def=>[def.key,def]));const values:Record<string,PropertyValue>=Object.create(null);const unknown:string[]=[];for(const pair of map.items){if(!isScalar(pair.key)||typeof pair.key.value!=='string')throw new Error('Property keys must be strings.');const key=pair.key.value;if(!known.has(key)){unknown.push(key);continue;}const value=(isNode(pair.value)?pair.value.toJSON():null);validateProperty(known.get(key)!,value);values[key]=value;}return {values,unknown};}
export function validateProperty(def:PropertyDefinition,value:unknown):asserts value is PropertyValue {if(value===null)return;let valid=false;switch(def.type){case 'text':valid=typeof value==='string'&&value.length<=4096;break;case 'number':valid=typeof value==='number'&&Number.isFinite(value);break;case 'boolean':valid=typeof value==='boolean';break;case 'date':valid=typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;break;case 'datetime':valid=typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/.test(value)&&!Number.isNaN(Date.parse(value));break;case 'select':valid=typeof value==='string'&&def.options.includes(value);break;case 'multiSelect':valid=Array.isArray(value)&&value.every(item=>typeof item==='string'&&def.options.includes(item))&&new Set(value).size===value.length;break;case 'noteReference':valid=typeof value==='number'&&Number.isSafeInteger(value)&&value>0;break;case 'link':try{const url=new URL(String(value));valid=typeof value==='string'&&value.length<=2048&&['https:','http:'].includes(url.protocol)&&!url.username&&!url.password;}catch{/* invalid */}break;}if(!valid)throw new Error(`${def.title}: invalid ${def.type} value.`);}
export function writePropertyFrontmatter(source:string,values:Record<string,PropertyValue>,definitions:PropertyDefinition[]){const {parts,doc}=document(source);const known=new Set(definitions.map(def=>def.key));for(const def of definitions)if(Object.prototype.hasOwnProperty.call(values,def.key))validateProperty(def,values[def.key]);const existing=doc.get(field,true);if(existing!==undefined&&!isMap(existing))throw new Error('moduloProperties must be a mapping.');const merged:Record<string,unknown>=Object.create(null);if(isMap(existing))for(const pair of existing.items){if(!isScalar(pair.key)||typeof pair.key.value!=='string')throw new Error('Property keys must be strings.');if(!known.has(pair.key.value))merged[pair.key.value]=(isNode(pair.value)?pair.value.toJSON():null);}
  for(const key of Object.keys(values).sort())merged[key]=values[key];
  const block=stringify({[field]:merged},{sortMapEntries:true,lineWidth:0}).replace(/\n/g,parts.newline);
  if(!parts.prefix)return `---\n${block}---\n${source}`;
  // Replace only this top-level pair; every unrelated source byte stays intact.
  const pair=isMap(doc.contents)?doc.contents.items.find(item=>isScalar(item.key)&&item.key.value===field):undefined;
  if(!pair)return parts.prefix+parts.yaml+block+parts.suffix;
  if(!isScalar(pair.key)||!pair.key.range||!pair.value?.range)throw new Error('Cannot safely replace this frontmatter structure.');
  const start=pair.key.range[0];const end=pair.value.range[2];
  if(parts.yaml.slice(0,start).split('\n').pop()!.trim())throw new Error('Use block-style frontmatter to edit properties.');
  return parts.prefix+parts.yaml.slice(0,start)+block+parts.yaml.slice(end)+parts.suffix;
}
