import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {authenticatedRequest} from '../../services/authenticatedRequest';
import {createPackPlan,applyPackPlan,type PackPlan} from './workspacePackService';
import {CAPABILITY_LABELS} from '../blueprint/capabilities';
import {PropertyQueryResults} from '../knowledge/PropertyQueryView';
import {EvidenceExport} from '../executions/EvidenceExport';
import type {PackManifest} from '../blueprint/pack/packManifest';
const field='rounded border border-border bg-background px-3 py-2 text-sm';
interface Engagement {id:string;title:string;intake_note?:number;checklist_note?:number;report_note?:number;review_run?:string;run_state?:string;records?:{note_id:number;title:string;kind:string}[];approvals?:{id:string;state:string;signature_state:string}[]}
interface Resource {spec:string;pack_key:string;resource_key:string;kind:string;title:string;knowledge_id?:string;detached:boolean}
export async function auditRequest<T>(path:string,body?:unknown):Promise<T>{const response=await authenticatedRequest(`/api/audit-pack${path}`,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){let code='';try{code=(await response.json()).code??'';}catch{/* status below */}throw new Error(`Audit request failed${code?`: ${code}`:` (${response.status})`}.`);}return response.json();}
export function AuditPack(){const [status,setStatus]=useState<{installed:boolean;signingConfigured:boolean}>();const [engagements,setEngagements]=useState<Engagement[]>([]);const [current,setCurrent]=useState<Engagement>();const [resources,setResources]=useState<Resource[]>([]);const [reviewer,setReviewer]=useState('');const [plan,setPlan]=useState<PackPlan>();const [consent,setConsent]=useState(false);const [title,setTitle]=useState('');const [scope,setScope]=useState('');const [finding,setFinding]=useState({title:'',severity:'high',description:'',recommendation:'',vulnerabilityClass:'access-control'});const [report,setReport]=useState<string>();const [share,setShare]=useState(false);const [reportTarget,setReportTarget]=useState<{id:number;version:number}>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [requestId,setRequestId]=useState(()=>crypto.randomUUID());const [findingId,setFindingId]=useState(()=>crypto.randomUUID());const [submitId,setSubmitId]=useState(()=>crypto.randomUUID());
 useEffect(()=>{let active=true;Promise.all([auditRequest<{installed:boolean;signingConfigured:boolean}>(''),auditRequest<Engagement[]>('/engagements'),authenticatedRequest('/api/workspace-packs/resources').then(response=>response.json())]).then(([state,items,resources])=>{if(active){setStatus(state);setEngagements(items);if(Array.isArray(resources))setResources(resources.filter((item:Resource)=>item.pack_key==='org.modulo.security-audit'&&!item.detached));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision]);
 useEffect(()=>{if(!current)return;let active=true;const timer=setInterval(()=>auditRequest<Engagement>(`/engagements/${current.id}`).then(value=>{if(active)setCurrent(value);}).catch(()=>{}),5000);return()=>{active=false;clearInterval(timer);};},[current?.id]);
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function select(id:string){await run(async()=>{setCurrent(await auditRequest<Engagement>(`/engagements/${id}`));setReport(undefined);setShare(false);setSubmitId(crypto.randomUUID());});}
 return <main className="mx-auto max-w-6xl space-y-5 px-4 py-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">Security Audit</h1><Link className="text-sm underline" to="/app/packs">Pack history and removal</Link></div>{error&&<p role="alert">{error}</p>}
 {!status?<p role="status">Loading audit workspace…</p>:!status.installed?<section className="max-w-2xl space-y-4"><p>Install engagement intake, checklists, findings, vulnerability knowledge, reports and approval workflows. Existing audit plugins and their dependencies are included.</p><label className="flex flex-col gap-1 text-sm">Reviewer account ID<input className={field} type="number" min="1" disabled={busy} value={reviewer} onChange={event=>{setReviewer(event.target.value);setPlan(undefined);setConsent(false);}}/></label><p className="text-sm">Choose a different account. Reports are shared with that reviewer only after you explicitly submit them.</p><button className={field} disabled={busy||!reviewer} onClick={()=>run(async()=>{const manifest=await auditRequest<PackManifest>('/manifest',{reviewer:Number(reviewer)});setPlan(await createPackPlan(manifest,false));})}>Review Audit Pack installation</button>
 {plan&&<section className="space-y-3"><h2 className="font-medium">Requested capabilities</h2><ul className="text-sm">{plan.plan.requiredCapabilities.map(capability=><li key={capability}>{CAPABILITY_LABELS[capability]?.label??capability}</li>)}</ul><p className="text-sm">Includes Markdown Notes, Pipeline, Findings Tracker, Audit Checklists, Vulnerability Knowledge and Audit Reports. No blockchain connection is required.</p><label className="flex gap-2 text-sm"><input type="checkbox" disabled={busy} checked={consent} onChange={event=>setConsent(event.target.checked)}/>I approve this installation and its requested capabilities.</label><button className={field} disabled={busy||!consent} onClick={()=>run(async()=>{await applyPackPlan(plan);setPlan(undefined);setRevision(value=>value+1);window.dispatchEvent(new Event('modulo:packs-changed'));})}>Install Security Audit Pack</button></section>}
 </section>:<>
 <nav className="flex flex-wrap gap-4 text-sm" aria-label="Audit tools">{[['pipeline','Pipeline'],['notes','Checklists'],['findings','Findings'],['vuln-kb','Vulnerability knowledge'],['approvals','Approvals'],['executions','Executions']].map(([view,label])=><Link key={view} className="underline" to={`/app/${view}`}>{label}</Link>)}</nav>
 <p className="text-sm">{status.signingConfigured?'Server decision signing is configured. Verify exported signatures against a trusted public-key fingerprint.':'Decision signing is not configured. Reviews can proceed, but their receipts will be marked unsigned.'} Reports and exports are not anchored.</p>
 <section className="space-y-3 border-y border-border py-4"><h2 className="font-medium">New engagement</h2><fieldset disabled={busy} className="max-w-2xl space-y-3"><label className="flex flex-col gap-1 text-sm">Engagement title<input className={field} value={title} onChange={event=>setTitle(event.target.value)}/></label><label className="flex flex-col gap-1 text-sm">Scope and assets<textarea className={`${field} min-h-24`} value={scope} onChange={event=>setScope(event.target.value)}/></label><button className={field} disabled={!title.trim()||!scope.trim()} onClick={()=>run(async()=>{const engagement=await auditRequest<Engagement>('/engagements',{requestId,title,scope});setCurrent(engagement);setRequestId(crypto.randomUUID());setTitle('');setScope('');setRevision(value=>value+1);window.dispatchEvent(new Event('modulo:properties-changed'));})}>Create engagement and checklist</button></fieldset></section>
 <section className="space-y-2"><h2 className="font-medium">Engagements</h2><ul className="space-y-2 text-sm">{engagements.map(item=><li key={item.id}><button className="underline" disabled={busy} onClick={()=>select(item.id)}>{item.title}</button></li>)}</ul></section>
 {current&&<section className="space-y-4 border-t border-border pt-4"><h2 className="font-medium">{current.title}</h2><ul className="space-y-1 text-sm">{current.records?.map(record=><li key={record.note_id}><Link className="underline" to={`/app/notes?note=${record.note_id}`}>{record.title}</Link> · {record.kind}</li>)}</ul>
 <details><summary className="cursor-pointer text-sm underline">Record a finding</summary><fieldset disabled={busy} className="my-3 max-w-2xl space-y-3">{(['title','description','recommendation','vulnerabilityClass'] as const).map(key=><label key={key} className="flex flex-col gap-1 text-sm">Finding {key}<input className={field} value={finding[key]} onChange={event=>setFinding({...finding,[key]:event.target.value})}/></label>)}<label className="flex flex-col gap-1 text-sm">Finding severity<select className={field} value={finding.severity} onChange={event=>setFinding({...finding,severity:event.target.value})}>{['critical','high','medium','low','informational'].map(value=><option key={value}>{value}</option>)}</select></label><button className={field} onClick={()=>run(async()=>{setCurrent(await auditRequest<Engagement>(`/engagements/${current.id}/findings`,{requestId:findingId,...finding}));setFindingId(crypto.randomUUID());window.dispatchEvent(new Event('modulo:properties-changed'));})}>Save finding and knowledge record</button></fieldset></details>
 <button className={field} disabled={busy} onClick={()=>run(async()=>{const updated=await auditRequest<Engagement>(`/engagements/${current.id}/report`,{});setCurrent(updated);const response=await authenticatedRequest(`/api/notes/${updated.report_note}`);if(!response.ok)throw new Error('Report unavailable.');const note=await response.json();setReport(note.markdownContent??note.content??'');setReportTarget({id:note.id,version:note.version});setShare(false);setSubmitId(crypto.randomUUID());window.dispatchEvent(new Event('modulo:properties-changed'));})}>Generate report snapshot</button>
 {report!==undefined&&<section className="space-y-3"><h3 className="font-medium">Report to submit</h3><pre className="max-h-96 overflow-auto whitespace-pre-wrap border border-border p-3 text-sm">{report}</pre><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={share} disabled={busy} onChange={event=>setShare(event.target.checked)}/>Share this exact report with the configured reviewer for approval.</label><button className={field} disabled={busy||!share} onClick={()=>run(async()=>{await auditRequest(`/engagements/${current.id}/submit`,{requestId:submitId,shareReport:true,expectedReport:reportTarget?.id,expectedVersion:reportTarget?.version});setCurrent(await auditRequest<Engagement>(`/engagements/${current.id}`));setShare(false);})}>Submit report for review</button></section>}
 {current.review_run&&<div className="space-y-3"><p>Workflow: {current.run_state??'Loading'}</p><Link className="text-sm underline" to={`/app/executions?run=${current.review_run}`}>Open report workflow</Link>{current.approvals?.map(approval=><div key={approval.id}><Link className="text-sm underline" to={`/app/approvals?request=${approval.id}`}>Review request</Link><p className="text-sm">{approval.state} · {approval.signature_state} · Not anchored</p><AuditReportArtifact requestId={approval.id}/></div>)}{['SUCCEEDED','FAILED','CANCELLED'].includes(current.run_state??'')&&<EvidenceExport runId={current.review_run}/>}</div>}
 </section>}
 <AuditDashboard resources={resources}/><section className="space-y-3 border-t border-border pt-4"><h2 className="font-medium">Pack queries</h2>{resources.filter(resource=>resource.kind==='savedQuery'&&resource.knowledge_id).map(resource=><LazyAuditQuery key={resource.resource_key} resource={resource}/>)}</section>
 </>}
 </main>;
}
export function AuditReportArtifact({requestId}:{requestId:string}){const [report,setReport]=useState<{title:string;markdown:string;signature?:{signatureState?:string}}> ();const [error,setError]=useState('');async function load(download=false){try{const receipt=await auditRequest<{title:string;markdown:string;signature?:{signatureState?:string}}>(`/approvals/${requestId}/report`);setReport(receipt);if(download){const url=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='audit-report-receipt.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){setError((e as Error).message);}}return <section className="my-3 space-y-2"><button className="text-sm underline" onClick={()=>load()}>Read shared report snapshot</button>{report&&<><h3 className="font-medium">{report.title}</h3><pre className="max-h-96 overflow-auto whitespace-pre-wrap border border-border p-3 text-sm">{report.markdown}</pre><button className="text-sm underline" onClick={()=>load(true)}>Export report and decision receipt</button><p className="text-sm">{report.signature?'A decision receipt is included. Verify its signature independently.':'No decision signature is available yet.'} Not anchored.</p></>}{error&&<p role="alert">{error}</p>}</section>;}

function LazyAuditQuery({resource}:{resource:Resource}){const [open,setOpen]=useState(false);return <details onToggle={event=>setOpen(event.currentTarget.open)}><summary className="cursor-pointer text-sm underline">{resource.title}</summary>{open&&<PropertyQueryResults id={resource.knowledge_id!}/>}</details>;}
function AuditDashboard({resources}:{resources:Resource[]}){const [selected,setSelected]=useState('');const dashboard=resources.find(resource=>resource.kind==='dashboard');if(!dashboard)return null;const spec=typeof dashboard.spec==='string'?JSON.parse(dashboard.spec):dashboard.spec;const views=resources.filter(resource=>resource.kind==='view'&&spec.viewRefs.includes(resource.resource_key));const view=views.find(view=>view.resource_key===selected)??views[0];if(!view)return null;const viewSpec=typeof view.spec==='string'?JSON.parse(view.spec):view.spec;const query=resources.find(resource=>resource.resource_key===viewSpec.queryRef);return <section className="space-y-3 border-t border-border pt-4"><h2 className="font-medium">{dashboard.title}</h2><div className="flex flex-wrap gap-3">{views.map(item=><button key={item.resource_key} className={field} aria-pressed={item.resource_key===view.resource_key} onClick={()=>setSelected(item.resource_key)}>{item.title}</button>)}</div>{query?.knowledge_id&&<PropertyQueryResults key={view.resource_key} id={query.knowledge_id} initialView={viewSpec.layout}/>}</section>;}
