import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {authenticatedRequest} from '../../services/authenticatedRequest';
import type {PackManifest} from '../blueprint/pack/packManifest';
import {resourceCapabilities,type PackResource} from '../blueprint/pack/packManifestV2';
import type {BlueprintListItem,SavedBlueprint} from '../blueprint/blueprintService';
import {CAPABILITY_LABELS} from '../blueprint/capabilities';
import knowledge from './examples/knowledge-base.v2.json';
import audit from './examples/security-audit.v2.json';
import {defaultValue,diagnosePack,referencedIds,resourceSchema,updateResource,withResources} from './packAuthoring';
import {ResourceFields} from './ResourceFields';
import {PackPreview} from './PackPreview';
const field='border border-border bg-background px-3 py-2 text-sm rounded';
const clone=(value:unknown)=>structuredClone(value) as PackManifest;
interface Preview {ok:boolean;reason?:string;canonicalSource:string;contentHash:string;capabilities:string[]}
interface Draft {id:string;title:string;revision:number;source?:string}
interface Publication {id:string;pack_key:string;version:string;state:string;content_hash:string;cid?:string;failure_code?:string}
async function studio<T>(path:string,body?:unknown):Promise<T>{const response=await authenticatedRequest(`/api/pack-studio${path}`,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){let code='';try{code=(await response.json()).code??'';}catch{/* classified below */}throw new Error(code==='DRAFT_CHANGED_OR_UNAVAILABLE'?'This draft changed elsewhere. Reload it before saving.':code==='IPFS_PUBLICATION_FAILED'?'IPFS publication could not be verified. The release is not marked published.':code==='PUBLICATION_VERSION_IMMUTABLE'?'This version already has different source. Choose a new version before publishing.':code==='PUBLICATION_SOURCE_CHANGED'?'The source changed. Preview it again before publishing.':`Pack Studio request failed${code?` (${code})`:''}.`);}return response.json();}
function exportSource(source:string,name:string){const url=URL.createObjectURL(new Blob([source],{type:'application/json;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PackStudio(){
  const [manifest,setManifest]=useState<PackManifest>(()=>clone(knowledge));const [selected,setSelected]=useState(0);const [draft,setDraft]=useState<Draft>();const [drafts,setDrafts]=useState<Draft[]>([]);const [publications,setPublications]=useState<Publication[]>([]);const [blueprints,setBlueprints]=useState<BlueprintListItem[]>([]);
  const [preview,setPreview]=useState<Preview>();const [publicConfirmed,setPublicConfirmed]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [kind,setKind]=useState<PackResource['kind']>('template');const [revision,setRevision]=useState(0);
  useEffect(()=>{let active=true;Promise.all([studio<Draft[]>('/drafts'),studio<Publication[]>('/publications')]).then(([saved,published])=>{if(active){setDrafts(saved);setPublications(published);}}).catch(e=>{if(active)setError(e.message);});authenticatedRequest('/api/blueprints').then(response=>response.ok?response.json():[]).then(value=>{if(active)setBlueprints(value);}).catch(()=>{});return()=>{active=false;};},[revision]);
  const resources=manifest.resources??[];const resource=resources[selected];const diagnostics=diagnosePack(manifest);
  function change(next:PackManifest){setManifest(next);setPreview(undefined);setPublicConfirmed(false);setNotice('');}
  function edit(next:PackResource){setManifest(previous=>withResources(previous,(previous.resources??[]).map(value=>value===resource?next:value)));setPreview(undefined);setPublicConfirmed(false);setNotice('');}
  function loadSource(source:string){const value=JSON.parse(source) as PackManifest;if(value.manifestVersion!==2||!Array.isArray(value.resources)||value.resources.some(item=>!item||typeof item.id!=='string'||typeof item.kind!=='string'||!item.spec||typeof item.spec!=='object'||!Array.isArray(item.requires)||!Array.isArray(item.capabilities)||item.requires.some(ref=>typeof ref!=='string')||item.capabilities.some(cap=>typeof cap!=='string')||Array.isArray(item.spec)))throw new Error('Import a v2 manifest with structured resources.');change(value);setSelected(0);}
  async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Pack Studio request failed.');}finally{setBusy(false);}}
  async function save(){await run(async()=>{const saved=await studio<Draft>('/drafts',{id:draft?.id,revision:draft?.revision??0,source:JSON.stringify(manifest)});setDraft(saved);setNotice('Private draft saved.');setRevision(value=>value+1);});}
  async function inspect(){await run(async()=>{if(diagnostics.length)throw new Error('Fix the listed contributions before previewing.');const value=await studio<Preview>('/preview',{source:JSON.stringify(manifest)});if(!value.ok)throw new Error(value.reason);setPreview(value);setPublicConfirmed(false);});}
  async function publish(){if(!preview||!publicConfirmed)return;await run(async()=>{const receipt=await studio<Publication>('/publish',{source:preview.canonicalSource,expectedHash:preview.contentHash,publicConfirmation:true});if(receipt.state!=='PUBLISHED')throw new Error('Publication is not verified yet.');setNotice('Publication verified on IPFS. The source is public and is not anchored.');setPublicConfirmed(false);setRevision(value=>value+1);});}
  return <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">Pack Studio</h1><Link className="text-sm underline" to="/app/packs">Installed packs</Link></div>
    {error&&<p role="alert" className="my-3">{error}</p>}{notice&&<p role="status" className="my-3">{notice}</p>}
    <div className="my-5 flex flex-wrap gap-3"><button className={field} disabled={busy} onClick={()=>{change(clone(knowledge));setDraft(undefined);setSelected(0);}}>New Knowledge Base draft</button><button className={field} disabled={busy} onClick={()=>{change(clone(audit));setDraft(undefined);setSelected(0);}}>New Audit draft</button><label className={`${field} cursor-pointer`}>Import manifest<input type="file" accept="application/json,.json" className="sr-only" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)run(async()=>{if(file.size>2097152)throw new Error('Manifest exceeds 2 MiB.');loadSource(await file.text());setDraft(undefined);});}}/></label><button className={field} disabled={busy} onClick={save}>Save private draft</button></div>
    <div className="my-4 grid gap-3 sm:grid-cols-3">{(['id','name','version'] as const).map(key=><label key={key} className="flex flex-col gap-1 text-sm">Pack {key}<input className={field} disabled={busy} value={manifest[key]} onChange={event=>change({...manifest,[key]:event.target.value})}/></label>)}</div>
    <label className="mb-5 flex flex-col gap-1 text-sm">Description<textarea className={field} disabled={busy} value={manifest.description??''} onChange={event=>change({...manifest,description:event.target.value})}/></label>
    <fieldset disabled={busy} className="grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]"><legend className="sr-only">Pack contributions</legend>
      <aside><h2 className="font-medium">Resources</h2><ul className="my-3 space-y-1">{resources.map((item,index)=><li key={index}><button className="w-full border-l-2 border-border px-3 py-2 text-left text-sm" aria-pressed={index===selected} onClick={()=>setSelected(index)}>{item.title||item.id}<span className="block text-xs text-muted-foreground">{item.kind}</span></button></li>)}</ul>
        <label className="flex flex-col gap-1 text-sm">Contribution type<select className={field} value={kind} onChange={event=>setKind(event.target.value as PackResource['kind'])}>{Object.keys(resourceCapabilities).map(value=><option key={value}>{value}</option>)}</select></label><button className={`${field} mt-2`} onClick={()=>{const id=`${kind.toLowerCase()}-${resources.length+1}`;const item:PackResource={id,kind,title:'New contribution',requires:[],capabilities:[resourceCapabilities[kind]],spec:defaultValue(resourceSchema(kind)) as Record<string,unknown>};change(withResources(manifest,[...resources,item]));setSelected(resources.length);}}>Add contribution</button>
      </aside>
      {resource&&<section key={selected} className="min-w-0 space-y-4"><h2 className="font-medium">Edit {resource.kind}</h2><div className="grid gap-3 sm:grid-cols-2"><label className="flex flex-col gap-1 text-sm">Resource ID<input className={field} value={resource.id} onChange={event=>edit({...resource,id:event.target.value})}/></label><label className="flex flex-col gap-1 text-sm">Resource title<input className={field} value={resource.title} onChange={event=>edit({...resource,title:event.target.value})}/></label></div>
        {resource.kind==='blueprint'?<BlueprintResource key={resource.id} resource={resource} blueprints={blueprints} onChange={edit} onError={setError} onRefresh={()=>setRevision(value=>value+1)}/>:<ResourceFields rule={resourceSchema(resource.kind)} value={resource.spec} path="spec" label="Contribution settings" resources={resources.filter((_,index)=>index!==selected)} onChange={spec=>edit(updateResource(resource,spec as Record<string,unknown>))}/>}
        <details><summary className="cursor-pointer text-sm underline">Prerequisites and capabilities</summary><fieldset className="my-3"><legend className="text-sm font-medium">Requires resources</legend>{resources.filter((_,index)=>index!==selected).map(item=><label key={item.id} className="my-1 flex gap-2 text-sm"><input type="checkbox" checked={resource.requires.includes(item.id)} disabled={referencedIds(resource.spec).includes(item.id)} onChange={event=>edit({...resource,requires:event.target.checked?[...resource.requires,item.id]:resource.requires.filter(id=>id!==item.id)})}/>{item.title} ({item.id})</label>)}</fieldset><fieldset><legend className="text-sm font-medium">Declared capabilities</legend>{Object.keys(CAPABILITY_LABELS).map(capability=><label key={capability} className="my-1 flex gap-2 text-sm"><input type="checkbox" checked={resource.capabilities.includes(capability)} disabled={capability===resourceCapabilities[resource.kind]} onChange={event=>edit({...resource,capabilities:event.target.checked?[...resource.capabilities,capability]:resource.capabilities.filter(cap=>cap!==capability)})}/>{CAPABILITY_LABELS[capability].label}</label>)}</fieldset></details>
        <button className="text-sm underline" onClick={()=>{change(withResources(manifest,resources.filter((_,index)=>index!==selected)));setSelected(Math.max(0,selected-1));}}>Remove contribution</button>
      </section>}
    </fieldset>
    <section className="my-6 border-t border-border pt-4"><h2 className="font-medium">Validation</h2>{diagnostics.length?<ul className="my-3 space-y-2 text-sm" aria-label="Manifest validation errors">{diagnostics.map((issue,index)=><li key={index}><strong>{issue.path}</strong>: {issue.message}</li>)}</ul>:<p className="my-3 text-sm">All contributions and references pass local validation.</p>}<button className={field} disabled={busy||diagnostics.length>0} onClick={inspect}>Preview package</button></section>
    {preview&&<section className="my-6 space-y-4"><PackPreview manifest={manifest}/><h2 className="font-medium">Package source and provenance</h2><p className="break-all text-sm">SHA-256: {preview.contentHash}</p><ul className="text-sm">{preview.capabilities.map(capability=><li key={capability}>{CAPABILITY_LABELS[capability]?.label??capability}</li>)}</ul><button className={field} disabled={busy} onClick={()=>exportSource(preview.canonicalSource,'pack-manifest.json')}>Export manifest source</button><p className="text-sm">Not anchored. Publisher identity is not verified by publishing to IPFS.</p><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={publicConfirmed} disabled={busy} onChange={event=>setPublicConfirmed(event.target.checked)}/>I confirm this manifest may be public on IPFS, including its Blueprint and plugin configuration.</label><button className={field} disabled={busy||!publicConfirmed} onClick={publish}>Publish reviewed source to IPFS</button></section>}
    <section className="my-6 border-t border-border pt-4"><h2 className="font-medium">Private drafts</h2><ul className="my-3 space-y-2 text-sm">{drafts.map(saved=><li key={saved.id}><button className="underline" disabled={busy} onClick={()=>run(async()=>{const loaded=await studio<Draft>(`/drafts/${saved.id}`);loadSource(loaded.source!);setDraft(loaded);})}>{saved.title} · revision {saved.revision}</button></li>)}</ul></section>
    <section className="my-6"><h2 className="font-medium">Publications</h2><ul className="my-3 space-y-3 text-sm">{publications.map(publication=><li key={publication.id}><p>{publication.pack_key} · {publication.version} · {publication.state}</p><p className="break-all">{publication.cid??publication.failure_code??'Awaiting IPFS verification'}</p><button className="underline" disabled={busy} onClick={()=>run(async()=>{const response=await authenticatedRequest(`/api/pack-studio/publications/${publication.id}/source`);if(!response.ok)throw new Error('Source unavailable.');exportSource(await response.text(),'published-pack.json');})}>Export exact source</button></li>)}</ul></section>
  </main>;
}
function BlueprintResource({resource,blueprints,onChange,onError,onRefresh}:{resource:PackResource;blueprints:BlueprintListItem[];onChange:(value:PackResource)=>void;onError:(error:string)=>void;onRefresh:()=>void}){
  const request=useRef(0);
  useEffect(()=>{request.current++;return()=>{request.current++;};},[resource]);
  const ir=resource.spec.ir as {nodes?:{id:string;type:string;config?:Record<string,unknown>}[];edges?:unknown[]};
  const nodes=Array.isArray(ir?.nodes)?ir.nodes.filter(node=>node&&typeof node==='object'):[];
  return <div className="space-y-3"><label className="flex flex-col gap-1 text-sm">Import saved Blueprint<select className={field} value="" onChange={event=>{const name=event.target.value;const attempt=++request.current;if(name)authenticatedRequest(`/api/blueprints/${encodeURIComponent(name)}`).then(async response=>{if(!response.ok)throw new Error('Blueprint unavailable.');const saved=await response.json() as SavedBlueprint;if(attempt===request.current)onChange(updateResource(resource,{ir:saved.ir}));}).catch(error=>{if(attempt===request.current)onError(error.message);});}}><option value="">Choose a Blueprint…</option>{blueprints.map(blueprint=><option key={blueprint.id} value={blueprint.name}>{blueprint.name}</option>)}</select></label><div className="flex gap-3"><Link className="text-sm underline" to="/app/blueprints" target="_blank" rel="noreferrer">Open Blueprint editor in new tab</Link><button className="text-sm underline" onClick={onRefresh}>Refresh Blueprints</button></div><p className="text-sm">Included graph: {nodes.length} nodes, {ir?.edges?.length??0} connections.</p>{nodes.filter(node=>node.type==='action.approval.request').map(node=><label key={node.id} className="flex flex-col gap-1 text-sm">Reviewer account ID for {node.id}<input className={field} value={String(node.config?.approverUserId??'')} onChange={event=>onChange(updateResource(resource,{ir:{...ir,nodes:ir.nodes!.map(item=>item.id===node.id?{...item,config:{...item.config,approverUserId:event.target.value}}:item)}}))}/></label>)}</div>;
}
