import {useState} from 'react';
import type {PackResource} from '../blueprint/pack/packManifestV2';
import {defaultValue,type FormSchema} from './packAuthoring';
const field='w-full border border-border bg-background px-2 py-2 text-sm rounded';
const labels:Record<string,string>={schemaRef:'Property schema',queryRef:'Saved query',templateRef:'Template',dashboardRef:'Dashboard',viewRefs:'Views',groupBy:'Group by property'};
const refKinds:Record<string,string>={schemaRef:'propertySchema',queryRef:'savedQuery',templateRef:'template',dashboardRef:'dashboard',viewRefs:'view'};
export function ResourceFields({rule,value,onChange,label,path,resources}:{rule:FormSchema;value:unknown;onChange:(value:unknown)=>void;label:string;path:string;resources:PackResource[]}){
  const key=path.split('.').pop()!;
  if(rule.enum)return <label className="flex flex-col gap-1 text-sm">{label}<select className={field} value={String(value??'')} onChange={event=>onChange(rule.enum!.find(option=>String(option)===event.target.value))}><option value="">Choose…</option>{rule.enum.map(option=><option key={String(option)} value={String(option)}>{String(option)}</option>)}</select></label>;
  if(refKinds[key]&&rule.type!=='array')return <label className="flex flex-col gap-1 text-sm">{labels[key]}<select className={field} value={String(value??'')} onChange={event=>onChange(event.target.value||undefined)}><option value="">Choose…</option>{resources.filter(resource=>resource.kind===refKinds[key]).map(resource=><option key={resource.id} value={resource.id}>{resource.title} ({resource.id})</option>)}</select></label>;
  if(rule.type==='object'){
    if(!rule.properties)return <JsonField label={label} value={value??{}} onChange={onChange}/>;
    const object=(value&&typeof value==='object'?value:{}) as Record<string,unknown>;
    return <fieldset className="space-y-3 border-l border-border pl-3"><legend className="mb-2 text-sm font-medium">{label}</legend>{Object.entries(rule.properties).map(([name,property])=><ResourceFields key={name} rule={property} value={object[name]} resources={resources} path={`${path}.${name}`} label={`${labels[name]??name}${rule.required?.includes(name)?' *':''}`} onChange={next=>{const copy={...object};if(next===undefined)delete copy[name];else copy[name]=next;onChange(copy);}}/>)}</fieldset>;
  }
  if(rule.type==='array'){
    const values=Array.isArray(value)?value:[];
    if(refKinds[key])return <fieldset><legend className="mb-2 text-sm">{labels[key]}</legend>{resources.filter(resource=>resource.kind===refKinds[key]).map(resource=><label key={resource.id} className="my-1 flex items-start gap-2 text-sm"><input type="checkbox" checked={values.includes(resource.id)} onChange={event=>onChange(event.target.checked?[...values,resource.id]:values.filter(item=>item!==resource.id))}/>{resource.title}</label>)}</fieldset>;
    return <fieldset className="space-y-3"><legend className="text-sm font-medium">{label}</legend>{values.map((item,index)=><div key={index} className="space-y-2 border-b border-border pb-3"><ResourceFields rule={rule.items??{type:'string'}} value={item} resources={resources} label={`${label} ${index+1}`} path={`${path}[${index}]`} onChange={next=>onChange(values.map((old,position)=>position===index?next:old))}/><button type="button" className="text-sm underline" onClick={()=>onChange(values.filter((_,position)=>position!==index))}>Remove {label} {index+1}</button></div>)}<button type="button" className="border border-border px-2 py-1 text-sm" disabled={values.length>=(rule.maxItems??100)} onClick={()=>onChange([...values,defaultValue(rule.items??{type:'string'})])}>Add {label}</button></fieldset>;
  }
  if(Array.isArray(rule.type))return <ScalarField label={label} value={value} onChange={onChange}/>;
  if(rule.type==='boolean')return <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={value===true} onChange={event=>onChange(event.target.checked)}/>{label}</label>;
  if(rule.type==='number'||rule.type==='integer')return <label className="flex flex-col gap-1 text-sm">{label}<input className={field} type="number" value={typeof value==='number'?value:''} onChange={event=>onChange(event.target.value===''?undefined:Number(event.target.value))}/></label>;
  return <label className="flex flex-col gap-1 text-sm">{label}{(rule.maxLength??0)>512?<textarea className={`${field} min-h-28`} maxLength={rule.maxLength} value={String(value??'')} onChange={event=>onChange(event.target.value)}/>:<input className={field} maxLength={rule.maxLength} value={String(value??'')} onChange={event=>onChange(event.target.value)}/>}</label>;
}
function JsonField({label,value,onChange}:{label:string;value:unknown;onChange:(value:unknown)=>void}){const [source,setSource]=useState(()=>JSON.stringify(value,null,2));const [error,setError]=useState('');return <label className="flex flex-col gap-1 text-sm">{label} (JSON configuration)<textarea className={`${field} min-h-24 font-mono`} value={source} onChange={event=>{setSource(event.target.value);try{const parsed=JSON.parse(event.target.value);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();onChange(parsed);setError('');}catch{onChange(event.target.value);setError('Enter a JSON object.');}}}/>{error&&<span role="alert">{error}</span>}</label>;}
function ScalarField({label,value,onChange}:{label:string;value:unknown;onChange:(value:unknown)=>void}){const type=value===null?'null':typeof value==='number'?'number':typeof value==='boolean'?'boolean':'string';return <fieldset className="space-y-2"><legend className="text-sm">{label}</legend><label className="flex flex-col gap-1 text-sm">Value type<select className={field} value={type} onChange={event=>onChange(event.target.value==='number'?0:event.target.value==='boolean'?false:event.target.value==='null'?null:'')}>{['string','number','boolean','null'].map(option=><option key={option}>{option}</option>)}</select></label>{type!=='null'&&<ResourceFields rule={{type}} value={value} label={label} path="value" resources={[]} onChange={onChange}/>}</fieldset>;}
