import {useEffect,useRef,useState} from 'react';
import {applyPackPlan,createPackPlan,packRequest,rollbackPlan,uninstallPlan,type Installation,type PackOperation,type PackPlan,type PackRelease} from './workspacePackService';
import {validateManifest,type PackManifest} from '../blueprint/pack/packManifest';
import {CAPABILITY_LABELS} from '../blueprint/capabilities';
import {createCoreCatalog} from '../blueprint/nodeCatalog';
const field='border border-border bg-background px-3 py-2 text-sm rounded';
export function WorkspacePacks(){
  const [installed,setInstalled]=useState<Installation[]>([]);const [history,setHistory]=useState<PackOperation[]>([]);const [page,setPage]=useState(0);
  const [manifest,setManifest]=useState('');const [demo,setDemo]=useState(false);const [plan,setPlan]=useState<PackPlan>();const [confirmed,setConfirmed]=useState(false);
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [releases,setReleases]=useState<Record<string,PackRelease[]>>({});const [revision,setRevision]=useState(0);const applying=useRef(false);
  useEffect(()=>{let active=true;Promise.all([packRequest<Installation[]>(''),packRequest<PackOperation[]>(`/history?page=${page}`)]).then(([packs,operations])=>{if(active){setInstalled(packs);setHistory(operations);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[page,revision]);
  async function prepare(action:()=>Promise<PackPlan>){setBusy(true);setError('');setNotice('');setPlan(undefined);setConfirmed(false);try{setPlan(await action());}catch(e){setError(e instanceof Error?e.message:'Unable to prepare pack.');}finally{setBusy(false);}}
  function preview(){prepare(async()=>{const value=JSON.parse(manifest) as PackManifest;const check=validateManifest(value,createCoreCatalog());if(!check.ok)throw new Error(check.reason);if(value.manifestVersion!==2)throw new Error('Use the legacy pack manager for v1 manifests.');return createPackPlan(value,demo);});}
  async function apply(){if(!plan||!confirmed||applying.current)return;applying.current=true;setBusy(true);setError('');try{const result=await applyPackPlan(plan);setPlan(result);setConfirmed(false);setNotice('Pack operation completed. Your existing content was preserved.');setRevision(value=>value+1);}catch(e){setError(e instanceof Error?e.message:'Unable to apply pack.');try{const current=await packRequest<PackPlan>(`/plans/${plan.id}`);setPlan(current);if(current.status==='SUCCEEDED'){setError('');setNotice('Pack operation completed. Your existing content was preserved.');}}catch{setPlan(undefined);}setConfirmed(false);setRevision(value=>value+1);}finally{applying.current=false;setBusy(false);}}
  return <main className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><h1 className="text-xl font-semibold">Workspace packs</h1>
    {error&&<p role="alert" className="my-3">{error}</p>}{notice&&<p role="status" className="my-3">{notice}</p>}
    <section className="my-5"><h2 className="font-medium">Install or upgrade</h2><label className="mt-3 flex flex-col gap-1 text-sm">Pack manifest<textarea className={`${field} min-h-40 font-mono`} value={manifest} disabled={busy} onChange={event=>{setManifest(event.target.value);setPlan(undefined);setConfirmed(false);}} placeholder="Paste a v2 pack manifest"/></label>
      <label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={demo} disabled={busy} onChange={event=>{setDemo(event.target.checked);setPlan(undefined);setConfirmed(false);}}/>Create optional demo notes. They become your content and remain after uninstall.</label>
      <button className={field} disabled={busy||!manifest.trim()} onClick={preview}>Review install plan</button>
    </section>
    {plan&&<section aria-label="Pack operation plan" className="my-5 border-y border-border py-4"><h2 className="font-medium">{plan.kind} · {plan.pack_key}</h2><p className="my-2 text-sm">Status: {plan.status}</p><ul className="space-y-1 text-sm">{plan.plan.changes.map(change=><li key={change.resource}>{change.resource} · {change.kind} · {change.action.replace(/_/g,' ').toLowerCase()}</li>)}</ul>
      <h3 className="mt-4 font-medium">Requested capabilities</h3>{plan.plan.requiredCapabilities.length?<ul className="my-2 text-sm">{plan.plan.requiredCapabilities.map(capability=><li key={capability}>{CAPABILITY_LABELS[capability]?.label || capability}</li>)}</ul>:<p className="my-2 text-sm">No new capabilities requested.</p>}
      <p className="my-2 text-sm">Demo notes: {plan.plan.includeDemo?'included':'not included'}. Existing user content is preserved. {plan.kind==='UNINSTALL'?'Edited workflows remain yours and may continue running after removal.':'Contributed Blueprint triggers will be enabled.'}</p>
      {plan.status==='PLANNED'&&<><label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={event=>setConfirmed(event.target.checked)}/>I approve these configuration changes and requested capabilities.</label><button className={field} disabled={busy||!confirmed} onClick={apply}>{busy?'Applying…':'Apply reviewed plan'}</button></>}
    </section>}
    <section className="my-6"><div className="flex items-center justify-between"><h2 className="font-medium">Installed packs</h2><button className="text-sm underline" onClick={()=>setRevision(value=>value+1)}>Refresh</button></div>
      {!installed.length&&<p className="my-3 text-sm">No workspace packs installed.</p>}<ul className="divide-y divide-border">{installed.map(pack=><li key={pack.id} className="py-4"><div className="flex flex-wrap gap-3"><strong>{pack.pack_key}</strong><span>{pack.version} · {pack.state}</span></div>
        {pack.runtime_pending>0&&<p role="status" className="my-2 text-sm">{pack.runtime_pending} runtime updates pending. <button className="underline" onClick={()=>packRequest(`/${encodeURIComponent(pack.pack_key)}/retry-runtime`,{method:'POST'}).then(()=>setRevision(value=>value+1)).catch(e=>setError(e.message))}>Retry runtime updates</button></p>}
        <div className="my-2 flex flex-wrap gap-3"><button className={field} disabled={busy} onClick={()=>packRequest<PackRelease[]>(`/${encodeURIComponent(pack.pack_key)}/releases`).then(value=>setReleases(old=>({...old,[pack.pack_key]:value}))).catch(e=>setError(e.message))}>Release history</button>{pack.state==='ACTIVE'&&<button className={field} disabled={busy} onClick={()=>prepare(()=>uninstallPlan(pack.pack_key))}>Review uninstall</button>}</div>
        {releases[pack.pack_key]&&<ul className="space-y-2 text-sm">{releases[pack.pack_key].map(release=><li key={release.id} className="flex flex-wrap items-center gap-3"><span>Version {release.version}</span>{release.id===pack.active_release?<span>Active</span>:<button className="underline" disabled={busy} onClick={()=>prepare(()=>rollbackPlan(pack.pack_key,release.id))}>Review rollback to {release.version}</button>}</li>)}</ul>}
      </li>)}</ul>
    </section>
    <section><h2 className="font-medium">Install history</h2><ol className="my-3 divide-y divide-border">{history.map(operation=><li key={operation.id} className="py-3 text-sm"><button className="underline" disabled={busy} onClick={()=>packRequest<PackPlan>(`/plans/${operation.id}`).then(value=>{setPlan(value);setConfirmed(false);}).catch(e=>setError(e.message))}>{operation.pack_key} · {operation.kind}</button><p>{operation.status}{operation.failure_code?` · ${operation.failure_code}`:''} · {new Date(operation.created_at).toLocaleString()}</p></li>)}</ol>
      <nav aria-label="Install history pages" className="flex items-center gap-3 text-sm"><button className={field} disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page+1}</span><button className={field} disabled={history.length<100} onClick={()=>setPage(value=>value+1)}>Next</button></nav>
    </section>
  </main>;
}
